window.PUTTERY_OPERATIONAL_STATUS = Object.freeze({
  schemaVersion: 1,
  snapshotDate: "2026-09-04",
  snapshotLabel: "Verified September 4, 2026",
  productionState: "hold",
  stateLabel: "Production held",
  currentGate: "Vendor registration",
  headline: "Receiver verified. Vendor registration is next.",
  summary: "The Puttery NYC route is bound to the correct Tock business, and both local delivery layers pass their current automated checks. No production reservation feed is connected yet.",
  readinessExplainer: "Tock registration, one controlled NYC event, and the remaining launch approvals still gate production.",
  accountRoute: "28086 / 37824",
  accountRouteDetail: "Business group / NYC business",
  receiverTests: "13 / 13",
  receiverTestsDetail: "Receiver checks passed locally",
  relayTests: "18 / 18",
  relayTestsDetail: "Relay checks passed locally",
  liveFeed: "Not connected",
  liveFeedDetail: "No guest or reservation data here",
  nextAction: "Tock confirms access to the restricted setup packet, rotates the prior credential through an approved secure route, registers the Reservation Webhook for Puttery NYC, sends one controlled Business 37824 event, and confirms the Data Exports route.",
  dataBoundary: "This public review page receives no webhook payloads and exposes no guest data. Production also remains gated by approved durable hosting, commercial approval, measurement definitions, consent ownership, and exact analytics and advertising account mapping.",
  milestones: [
    {
      state: "complete",
      statusLabel: "Verified",
      label: "Identifiers bound",
      detail: "Business group 28086 routes downstream only when business.id equals 37824.",
    },
    {
      state: "complete",
      statusLabel: "Verified",
      label: "Local delivery layers",
      detail: "The SQLite receiver and protected relay passed all 31 current automated checks on September 4.",
    },
    {
      state: "complete",
      statusLabel: "Sent",
      label: "Secure vendor handoff",
      detail: "The restricted setup packet was shared and the registration, rotation, test, and export confirmations were requested.",
    },
    {
      state: "current",
      statusLabel: "Waiting on Tock",
      label: "Webhook registration",
      detail: "The Reservation Webhook is not registered to an approved production endpoint yet.",
    },
    {
      state: "waiting",
      statusLabel: "Not run",
      label: "Controlled NYC event",
      detail: "One real Business 37824 delivery must reconcile before any live feed or booking value is claimed.",
    },
    {
      state: "locked",
      statusLabel: "Held",
      label: "Production reporting",
      detail: "Dashboard ingestion and advertising feedback stay off until the launch gates pass.",
    },
  ],
});
