[CmdletBinding()]
param(
    [switch]$SkipLiveChecks
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$portalId = '50612503'
$callRailAccountId = '671942387'
$taskName = 'Momentum360-Daily-Agent-Health'
$accessRegistryPath = 'C:\Users\dillo\AppData\Local\Codex\AccessBroker\registry.json'
$hubSpotLauncher = 'C:\Users\dillo\Documents\Codex\2026-07-12\hubspot-agent-set-jasonhubspottoken-ps1-hubspot\hubspot-agent\Invoke-HubSpotAgent.ps1'
$skillRoot = 'C:\Users\dillo\.codex\skills'
$modelCachePath = 'C:\Users\dillo\.codex\models_cache.json'
$promptPath = Join-Path $PSScriptRoot 'PROMPT.md'

$checks = [System.Collections.Generic.List[object]]::new()

function Add-Check {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][bool]$Ok,
        [Parameter(Mandatory)][string]$Category,
        [Parameter(Mandatory)][string]$Detail,
        [bool]$BlocksFullVerification = $false
    )

    $checks.Add([pscustomobject]@{
        name = $Name
        ok = $Ok
        category = $Category
        detail = $Detail
        blocksFullVerification = $BlocksFullVerification
    })
}

function Get-RegisteredSystem {
    param(
        [Parameter(Mandatory)]$Registry,
        [Parameter(Mandatory)][string]$SystemId
    )

    foreach ($client in @($Registry.clients)) {
        foreach ($system in @($client.systems)) {
            if ($system.id -eq $SystemId) {
                return [pscustomobject]@{ clientId = $client.id; system = $system }
            }
        }
    }
    return $null
}

if (-not (Test-Path -LiteralPath $promptPath)) {
    Add-Check -Name 'prompt' -Ok $false -Category 'LOCAL_CONFIGURATION' -Detail 'PROMPT.md is missing.' -BlocksFullVerification $true
} else {
    $promptText = Get-Content -LiteralPath $promptPath -Raw -Encoding UTF8
    $badEncodingMarkers = @(
        (-join @([char]0x00E2, [char]0x20AC, [char]0x201D)),
        (-join @([char]0x00E2, [char]0x20AC, [char]0x201C)),
        (-join @([char]0x00EF, [char]0x00BF, [char]0x00BD)),
        [string][char]0xFFFD
    )
    $encodingClean = @($badEncodingMarkers | Where-Object { $promptText.Contains($_) }).Count -eq 0
    Add-Check -Name 'prompt-encoding' -Ok $encodingClean -Category 'LOCAL_CONFIGURATION' -Detail $(if ($encodingClean) { 'Prompt text is UTF-8 clean.' } else { 'Prompt contains mojibake or replacement characters.' }) -BlocksFullVerification (-not $encodingClean)
}

$invalidSkills = @()
if (Test-Path -LiteralPath $skillRoot) {
    $invalidSkills = @(Get-ChildItem -LiteralPath $skillRoot -Recurse -Filter 'SKILL.md' -File |
        Where-Object { $_.FullName -notlike "$skillRoot\.gemini\*" } |
        Where-Object { (Get-Content -LiteralPath $_.FullName -Raw) -notmatch '^(?:\uFEFF)?---\s*\r?\n' })
}
Add-Check -Name 'codex-skill-metadata' -Ok ($invalidSkills.Count -eq 0) -Category 'CODEX_STARTUP' -Detail $(if ($invalidSkills.Count -eq 0) { 'All active Codex SKILL.md files have YAML frontmatter.' } else { "$($invalidSkills.Count) active SKILL.md file(s) lack YAML frontmatter." }) -BlocksFullVerification $false

$cacheOk = $true
$cacheDetail = 'Model cache is absent and will be regenerated by Codex.'
if (Test-Path -LiteralPath $modelCachePath) {
    try {
        $modelCache = Get-Content -LiteralPath $modelCachePath -Raw | ConvertFrom-Json
        $missingBaseInstructions = @($modelCache.models | Where-Object {
            -not ($_.PSObject.Properties.Name -contains 'base_instructions') -or
            $null -eq $_.base_instructions -or
            $_.base_instructions -isnot [string]
        })
        $cacheOk = $missingBaseInstructions.Count -eq 0
        $cacheDetail = if ($cacheOk) { 'Model cache JSON and base_instructions compatibility fields are valid.' } else { "$($missingBaseInstructions.Count) cached model(s) lack a string base_instructions compatibility field." }
    } catch {
        $cacheOk = $false
        $cacheDetail = 'Model cache JSON is invalid for startup use.'
    }
}
Add-Check -Name 'codex-model-cache' -Ok $cacheOk -Category 'CODEX_STARTUP' -Detail $cacheDetail -BlocksFullVerification $false

if (-not (Test-Path -LiteralPath $accessRegistryPath)) {
    Add-Check -Name 'access-registry' -Ok $false -Category 'ACCESS' -Detail 'Access Broker registry is missing.' -BlocksFullVerification $true
} else {
    $registry = Get-Content -LiteralPath $accessRegistryPath -Raw | ConvertFrom-Json
    $hubSpotRoute = Get-RegisteredSystem -Registry $registry -SystemId 'hubspot-jason-momentum-50612503'
    $hubSpotRouteOk = $null -ne $hubSpotRoute -and [string]$hubSpotRoute.system.hub_id -eq $portalId
    Add-Check -Name 'hubspot-route' -Ok $hubSpotRouteOk -Category 'ACCESS' -Detail $(if ($hubSpotRouteOk) { 'Access Broker resolves Momentum HubSpot portal 50612503.' } else { 'Momentum HubSpot portal route is missing or mismatched.' }) -BlocksFullVerification (-not $hubSpotRouteOk)

    $hubSpotBrowserRoute = Get-RegisteredSystem -Registry $registry -SystemId 'hubspot-jason-momentum-browser-50612503'
    $hubSpotBrowserState = if ($null -ne $hubSpotBrowserRoute) { [string]$hubSpotBrowserRoute.system.access_state } else { 'missing-browser-route' }
    $hubSpotBrowserOk = $null -ne $hubSpotBrowserRoute -and $hubSpotBrowserState -notmatch '^blocked-'
    Add-Check -Name 'hubspot-browser-session' -Ok $hubSpotBrowserOk -Category 'HUBSPOT_BROWSER_SESSION' -Detail $(if ($hubSpotBrowserOk) { 'The Momentum HubSpot browser session is registered as available.' } else { "Momentum HubSpot browser session is blocked: $hubSpotBrowserState." }) -BlocksFullVerification (-not $hubSpotBrowserOk)

    $callRailRoute = Get-RegisteredSystem -Registry $registry -SystemId 'callrail-momentum-digital-671942387'
    $callRailRouteOk = $null -ne $callRailRoute -and [string]$callRailRoute.system.account_id -eq $callRailAccountId
    Add-Check -Name 'callrail-route' -Ok $callRailRouteOk -Category 'ACCESS' -Detail $(if ($callRailRouteOk) { 'Access Broker resolves only Momentum Digital LLC account 671942387.' } else { 'Momentum Digital LLC CallRail route is missing or mismatched.' }) -BlocksFullVerification (-not $callRailRouteOk)

    if ($callRailRouteOk) {
        $callRailState = [string]$callRailRoute.system.access_state
        $callRailDirect = $callRailState -notmatch '^blocked-'
        Add-Check -Name 'callrail-direct-access' -Ok $callRailDirect -Category 'CALLRAIL_DIRECT_ACCESS' -Detail $(if ($callRailDirect) { 'Direct CallRail account access is registered as available.' } else { "Direct CallRail access is blocked: $callRailState. Fallback telemetry cannot prove routing or Mia SMS." }) -BlocksFullVerification (-not $callRailDirect)
    }
}

$task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($null -eq $task) {
    Add-Check -Name 'scheduled-task' -Ok $false -Category 'AUTOMATION' -Detail 'Momentum360-Daily-Agent-Health is not installed.' -BlocksFullVerification $true
} else {
    $taskInfo = Get-ScheduledTaskInfo -TaskName $taskName
    $actionOk = $task.Actions[0].Execute -eq 'C:\Windows\System32\wscript.exe' -and $task.Actions[0].Arguments -match [regex]::Escape($taskName)
    $taskOk = $task.State -ne 'Disabled' -and $actionOk -and $task.Settings.RestartCount -eq 3
    Add-Check -Name 'scheduled-task' -Ok $taskOk -Category 'AUTOMATION' -Detail $(if ($taskOk) { "Task is enabled, console-free, and configured for three retries. Last result: $($taskInfo.LastTaskResult)." } else { 'Scheduled task state, hidden action, or retry contract is incorrect.' }) -BlocksFullVerification (-not $taskOk)
}

if ($SkipLiveChecks) {
    Add-Check -Name 'hubspot-private-token' -Ok $true -Category 'HUBSPOT_API' -Detail 'Live HubSpot checks skipped by caller.' -BlocksFullVerification $false
    Add-Check -Name 'hubspot-conversations-read' -Ok $false -Category 'HUBSPOT_CONVERSATIONS_SCOPE' -Detail 'Live Conversations scope check skipped by caller.' -BlocksFullVerification $true
} elseif (-not (Test-Path -LiteralPath $hubSpotLauncher)) {
    Add-Check -Name 'hubspot-private-token' -Ok $false -Category 'HUBSPOT_API' -Detail 'Protected Momentum HubSpot launcher is missing.' -BlocksFullVerification $true
} else {
    try {
        $identity = (& $hubSpotLauncher jason-check-token | Out-String) | ConvertFrom-Json
        $identityOk = $identity.valid -eq $true -and [string]$identity.portalId -eq $portalId
        Add-Check -Name 'hubspot-private-token' -Ok $identityOk -Category 'HUBSPOT_API' -Detail $(if ($identityOk) { 'Protected private token validates against portal 50612503.' } else { 'Protected private token failed the portal guard.' }) -BlocksFullVerification (-not $identityOk)

        $conversationProbe = (& $hubSpotLauncher jason-conversations-probe | Out-String) | ConvertFrom-Json
        $conversationOk = @($conversationProbe.checks | Where-Object { $_.ok -ne $true }).Count -eq 0
        $missingScope = @($conversationProbe.checks | Where-Object { $_.category -eq 'MISSING_SCOPES' }).Count -gt 0
        $conversationDetail = if ($conversationOk) {
            'Conversations channels and threads are readable.'
        } elseif ($missingScope) {
            'The valid Momentum private app lacks conversations.read; channels and threads return HTTP 403.'
        } else {
            'Conversations channels or threads are unavailable for a reason other than a missing scope.'
        }
        Add-Check -Name 'hubspot-conversations-read' -Ok $conversationOk -Category 'HUBSPOT_CONVERSATIONS_SCOPE' -Detail $conversationDetail -BlocksFullVerification (-not $conversationOk)
    } catch {
        Add-Check -Name 'hubspot-private-token' -Ok $false -Category 'HUBSPOT_API' -Detail 'Protected Momentum HubSpot live check failed without exposing credentials.' -BlocksFullVerification $true
    }
}

$blocking = @($checks | Where-Object { $_.blocksFullVerification -and -not $_.ok })
$result = [pscustomobject]@{
    schemaVersion = 1
    checkedAt = [DateTimeOffset]::UtcNow.ToString('o')
    portalId = $portalId
    callRailAccountId = $callRailAccountId
    status = if ($blocking.Count -eq 0) { 'READY' } else { 'DEGRADED' }
    blockers = @($blocking | Select-Object name, category, detail)
    checks = $checks
}

$result | ConvertTo-Json -Depth 8
