import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(await fs.readFile(path.join(root, 'system.json'), 'utf8'));
const skill = process.env.MOMENTUM_DECK_SKILL_ROOT || path.join(os.homedir(), config.deckSkillRelativeToHome);
const checking = process.argv.includes('--check');
const hash = data => crypto.createHash('sha256').update(data).digest('hex');
const resolveSource = locator => locator.startsWith('skill:') ? path.resolve(skill, locator.slice(6)) : path.resolve(root, locator);
const sources = {};
for (const [name, locator] of Object.entries(config.sources)) {
  const bytes = await fs.readFile(resolveSource(locator));
  sources[name] = { locator, sha256: hash(bytes) };
}
const brand = JSON.parse(await fs.readFile(resolveSource(config.sources.digitalBrand), 'utf8'));
assert.equal(brand.id, 'momentum-digital');
assert.equal(brand.site, 'needmomentum.com');
assert.equal(config.clientId, 'momentum-360');
assert.equal(new Set(config.surfaces.map(s => s.id)).size, config.surfaces.length);
for (const surface of config.surfaces) assert(sources[surface.source], `Missing source: ${surface.id}`);
const colors = Object.fromEntries(Object.entries(brand.color).map(([key, value]) => [key, '#' + value.toUpperCase()]));
for (const value of Object.values(colors)) assert.match(value, /^#[0-9A-F]{6}$/);
const signature = (await fs.readFile(resolveSource(config.sources.m360Signature), 'utf8')).toLowerCase();
for (const value of Object.values(config.m360Email.color)) assert(signature.includes(value.toLowerCase()), `Signature color source drift: ${value}`);

function luminance(hex) {
  const rgb = hex.slice(1).match(/../g).map(c => parseInt(c, 16) / 255).map(c => c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return rgb[0] * 0.2126 + rgb[1] * 0.7152 + rgb[2] * 0.0722;
}
function contrast(a, b) { const values = [luminance(a), luminance(b)].sort((x,y) => y-x); return (values[0] + 0.05) / (values[1] + 0.05); }
assert.equal(contrast('#000000', '#FFFFFF'), 21);
assert.equal(contrast('#FFFFFF', '#FFFFFF'), 1);
const pairs = [
  ['digital body', colors.ink, colors.paper], ['digital muted', colors.slate, colors.paper],
  ['digital small link', colors.blueDeep, colors.paper], ['digital action', colors.paper, colors.blueDeep],
  ['digital dark text', colors.onDark, colors.navy], ['digital dark secondary', colors.onDarkSoft, colors.navy],
  ['m360 email body', config.m360Email.color.ink, config.m360Email.color.surface],
  ['m360 email link', config.m360Email.color.brand, config.m360Email.color.surface],
  ['m360 email secondary', config.m360Email.color.muted, config.m360Email.color.surface]
].map(([name, foreground, background]) => ({ name, foreground, background, ratio: Number(contrast(foreground, background).toFixed(2)), normalTextPass: contrast(foreground, background) >= 4.5 }));
assert(pairs.every(p => p.normalTextPass), 'A generated semantic text pair fails 4.5:1');
const tokens = {
  version: config.version, clientId: config.clientId, productionReady: false,
  profiles: {
    'digital-presentation': { status: 'incumbent-local-system', source: 'digitalBrand', color: colors, type: brand.type, layoutInches: brand.layout },
    'digital-web-proposal': { status: 'draft-semantic-adapter-admin-unverified', source: ['digitalBrand', 'digitalDeckSources'],
      color: { brand: colors.blue, action: colors.blueDeep, onAction: colors.paper, surface: colors.paper, surfaceAlt: colors.tint, inverse: colors.navy, ink: colors.ink, muted: colors.slate, link: colors.blueDeep, onInverse: colors.onDark, onInverseMuted: colors.onDarkSoft, border: colors.hair },
      type: { body: 'Roboto, Arial, sans-serif', editorial: 'Roboto Slab, Georgia, serif' },
      notes: 'Role assignments are a local proposal. Existing Elementor globals include other blue values; inventory before migration. No new site typography hierarchy is claimed.' },
    'm360-email': { status: 'local-review-draft-incumbent-style', source: 'm360Signature', ...config.m360Email }
  },
  surfaces: config.surfaces,
  withheld: ['m360-website', 'm360-reporting', 'm360-orbit', 'digital-concepts'],
  sourceHashes: sources
};

const cssBlocks = [];
for (const [profileId, profile] of Object.entries(tokens.profiles)) {
  cssBlocks.push(`[data-momentum-profile="${profileId}"] {\n${Object.entries(profile.color).map(([name,value]) => `  --momentum-color-${name.replace(/[A-Z]/g, x=>'-'+x.toLowerCase())}: ${value};`).join('\n')}\n}`);
}
const css = '/* Generated by build-system.mjs. Draft preview adapters; not installed on a website.\n   m360-email variables are for previews only; email requires literal inline values. */\n' + cssBlocks.join('\n\n') + '\n';
const web = tokens.profiles['digital-web-proposal'];
const theme = {
  $schema: 'https://schemas.wp.org/trunk/theme.json', version: 3,
  settings: { color: { palette: Object.entries(web.color).map(([slug, color]) => ({ slug: 'momentum-' + slug.replace(/[A-Z]/g, x=>'-'+x.toLowerCase()), name: slug.replace(/[A-Z]/g, x=>' '+x.toLowerCase()), color })) } }
};
const assets = [];
for (const [role, locator] of Object.entries(brand.logo).filter(([key]) => ['light','dark','mark','markDark'].includes(key))) {
  const bytes = await fs.readFile(path.join(skill, locator));
  assets.push({ brand: 'momentum-digital', role, locator: 'skill:' + locator, sha256: hash(bytes), status: role === 'light' ? 'incumbent-asset' : 'existing-derived-asset' });
}
for (const name of ['m360Logo', 'm360SignatureLogo']) assets.push({ brand: 'momentum-360', role: name, ...sources[name], status: 'source-located-existing-asset' });
const artifacts = {
  'output/tokens.json': JSON.stringify(tokens, null, 2) + '\n',
  'output/tokens.css': css,
  'output/momentum-digital.theme-fragment.json': JSON.stringify(theme, null, 2) + '\n',
  'output/assets.json': JSON.stringify(assets, null, 2) + '\n',
  'evidence/contrast.json': JSON.stringify({ formula: 'WCAG relative luminance', threshold: 4.5, pairs, primitiveCautions: [ { role: 'logo blue on white', ratio: Number(contrast(colors.blue, colors.paper).toFixed(2)), use: 'Preserve artwork. Use blueDeep for normal-size text and button surfaces.' } ] }, null, 2) + '\n'
};
for (const [relative, content] of Object.entries(artifacts)) {
  const target = path.join(root, relative);
  if (checking) assert.equal(await fs.readFile(target, 'utf8'), content, `Generated artifact stale: ${relative}`);
  else { await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, content); }
}
console.log(JSON.stringify({ status: checking ? 'verified-current' : 'built', profiles: Object.keys(tokens.profiles), sourceFiles: Object.keys(sources).length, assets: assets.length, contrastChecks: pairs.length, contrastPass: pairs.every(p=>p.normalTextPass), productionReady: false, artifacts: Object.keys(artifacts) }));
