// Local-only reading exercises and finite semantic service motion. No integration calls.
const motionRoles=['search','phone','build','operations','audience','proof'];
function motionStudy(role){const art={search:'<g class="text-lines"><path d="M65 20h90M65 35h70M65 50h85"/></g><g class="scanner"><circle cx="35" cy="30" r="14"/><path d="m45 40 12 12"/></g>',phone:'<path d="M35 18q-8 18 12 32l9-8-8-7-6 5q-8-7-5-13l5-5z"/><g class="sound-rings"><path d="M77 20q15 15 0 30M92 12q24 23 0 46M110 5q30 30 0 60"/></g>',build:'<g class="assembly"><rect x="38" y="35" width="30" height="24"/><rect x="75" y="35" width="30" height="24"/><rect x="112" y="35" width="30" height="24"/><path d="M38 24h104"/></g>',operations:'<g class="gear-one"><circle cx="65" cy="35" r="20"/><path d="M65 8v12M65 50v12M38 35h12M80 35h12M46 16l9 9m20 20 9 9m0-38-9 9M55 45l-9 9"/></g><g class="gear-two"><circle cx="118" cy="35" r="14"/><path d="M118 15v9M118 46v9M98 35h9M129 35h9"/></g>',audience:'<g class="audience-nodes"><circle cx="45" cy="30" r="11"/><circle cx="90" cy="30" r="11"/><circle cx="135" cy="30" r="11"/><path d="M30 57q15-20 30 0m15 0q15-20 30 0m15 0q15-20 30 0"/></g><rect class="audience-focus" x="23" y="10" width="44" height="52" rx="7"/>',proof:'<path d="M45 10h95v50H45zM55 22h35M55 35h25M55 48h35"/><path class="proof-check" d="m103 35 10 10 19-24"/>'};return `<div class="motion-study" data-motion-role="${role}"><svg viewBox="0 0 190 70" aria-hidden="true">${art[role]}</svg><button type="button" class="motion-replay">Replay ${role} motion</button></div>`}
function bindMotion(root){root.querySelectorAll('.motion-replay').forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='true';button.addEventListener('click',()=>{const study=button.closest('.motion-study');study.classList.remove('play');void study.offsetWidth;study.classList.add('play');const card=study.closest('figure');if(card){card.classList.remove('role-play');void card.offsetWidth;card.classList.add('role-play')}})})}
const assetGallery=document.getElementById('brand-gallery');if(assetGallery){const refresh=()=>{observer.disconnect();if(assetGallery.dataset.category==='services')assetGallery.querySelectorAll('figure').forEach((f,i)=>{if(!f.querySelector('.motion-study')){f.classList.add('motion-card-'+motionRoles[i]);f.insertAdjacentHTML('beforeend',motionStudy(motionRoles[i]))}});bindMotion(assetGallery);observer.observe(assetGallery,{childList:true})};const observer=new MutationObserver(refresh);refresh()}
function downloadLocal(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const exercise=document.getElementById('exercise-root');if(exercise){const book=JSON.parse(document.getElementById('book-data').textContent),index=Number(book.slug.slice(0,2))-1,key='momentum-v3-exercise:'+book.slug;let state={};try{state=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
const field=(name,label,type='text')=>`<label>${label}<input name="${name}" type="${type}" ${type==='number'?'min="0" step="1"':''} required></label>`;
const select=(name,label,options)=>`<label>${label}<select name="${name}" required>${options.map(x=>`<option value="${x}">${x||'Choose…'}</option>`).join('')}</select></label>`;
const titles=['Your AI visibility log','Your lead-intake test report','Your creative release review','Your workflow brief','Your lead reconciliation'];
const intros=['Record a question, the engine you checked and what you observed. This is a manual evidence log, not a live AI-search scan.','Record five manual test cases. These selections document your review; this page does not call, text or connect to a phone system.','Record the asset and the human review checks needed before release. Checking a box never publishes an asset.','Specify one workflow before choosing a tool. Save the inputs and the human escalation route in a portable brief.','Enter whole-number counts from your own evidence. This is a comparison of user-entered counts, not a verified CRM or attribution match.'];
const cases=['Normal inquiry','Missing contact details','Duplicate inquiry','After-hours request','Escalation required'];
let inputs='';if(index===0)inputs=field('question','Question you tested')+field('engine','Engine or assistant')+select('observed','Observed status',['','Business cited','Business mentioned, not cited','Business not observed','Unable to verify']);
if(index===1)inputs=cases.map((c,i)=>select('case'+i,c,['Not run','Pass','Fail'])).join('');
if(index===2)inputs=field('asset','Asset name')+['Source recorded','Exact logo verified','Visual review complete','Channel and dimensions checked'].map((c,i)=>select('review'+i,c,['Not reviewed','Pass','Needs revision'])).join('');
if(index===3)inputs=['Trigger','Input','Owner','Output','Escalation'].map(n=>`<label>${n}<textarea name="${n.toLowerCase()}" rows="2" required></textarea></label>`).join('');
if(index===4)inputs=field('platform','Platform events','number')+field('crm','Unique CRM leads','number')+field('qualified','Qualified leads','number');
exercise.innerHTML=`<h2>${titles[index]}</h2><p>${intros[index]}</p>${motionStudy(motionRoles[index])}<form id="specific-exercise" class="exercise-form">${inputs}<div class="exercise-actions"><button class="button" type="submit">${index===0?'Add observed row':index===4?'Calculate & save':'Save review'}</button><button class="button secondary" type="button" id="exercise-download">Download ${index===0?'CSV':'report'}</button><button class="button secondary" type="button" id="exercise-reset">Reset this exercise</button></div></form><div class="exercise-output" id="exercise-output" aria-live="polite"></div><p class="exercise-save" id="exercise-save" role="status">Local browser storage only. Nothing is sent.</p>`;
bindMotion(exercise);const form=document.getElementById('specific-exercise'),output=document.getElementById('exercise-output'),status=document.getElementById('exercise-save');for(const [name,value]of Object.entries(state.fields||{})){if(form.elements[name])form.elements[name].value=value}
function show(){output.replaceChildren();if(index===0){const rows=state.rows||[];const table=document.createElement('table');table.innerHTML='<thead><tr><th>Question</th><th>Engine</th><th>Observation</th></tr></thead>';const body=document.createElement('tbody');rows.forEach(r=>{const tr=document.createElement('tr');[r.question,r.engine,r.observed].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)});table.append(body);if(rows.length)output.append(table);else output.textContent='No observations recorded yet.'}else if(index===4&&state.result){const p=document.createElement('p');p.textContent=state.result;output.append(p)}else if(state.fields){const p=document.createElement('p');p.textContent='Saved user-entered review. Download the report to inspect every field.';output.append(p)}}
function save(){try{localStorage.setItem(key,JSON.stringify(state));status.textContent='Saved in this browser. User-entered evidence; nothing sent.'}catch{status.textContent='Browser storage unavailable. Download your report before leaving.'}}
form.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));if(Object.values(values).some(v=>!v.trim())){status.textContent='Complete the required fields before saving.';return}if(index===4){const nums=Object.values(values).map(Number);if(nums.some(n=>!Number.isSafeInteger(n)||n<0)){status.textContent='Enter nonnegative whole integers.';return}if(Number(values.qualified)>Number(values.crm)){status.textContent='Qualified leads cannot exceed unique CRM leads. Check the entries.';return}const diff=Number(values.platform)-Number(values.crm);state.result=`User-entered counts: ${values.platform} platform events; ${values.crm} unique CRM leads; ${values.qualified} qualified leads. Event-to-lead difference: ${diff}. Unmatched count gap: ${Math.abs(diff)} (${diff>=0?'more platform events':'more CRM leads'}). A count gap is not a record-level match or proof of missing leads.`}state.fields=values;if(index===0){state.rows=state.rows||[];state.rows.push(values)}save();show()});
document.getElementById('exercise-download').addEventListener('click',()=>{if(!state.fields&&!(state.rows||[]).length){status.textContent='Save an observation or review before downloading.';return}if(index===0){const quote=v=>'"'+String(v).replaceAll('"','""')+'"';const csv='Question,Engine,Observed status\r\n'+state.rows.map(r=>[r.question,r.engine,r.observed].map(quote).join(',')).join('\r\n');downloadLocal(book.slug+'-visibility-log.csv',csv,'text/csv')}else downloadLocal(book.slug+'-review.txt',titles[index]+'\nUser-entered manual evidence. No external integration or release performed.\n\n'+Object.entries(state.fields||{}).map(([k,v])=>((index===1&&k.startsWith('case'))?cases[Number(k.slice(4))]:(index===2&&k.startsWith('review'))?['Source recorded','Exact logo verified','Visual review complete','Channel and dimensions checked'][Number(k.slice(6))]:k)+': '+v).join('\n')+(state.result?'\n\n'+state.result:''))});
document.getElementById('exercise-reset').addEventListener('click',()=>{state={};form.reset();try{localStorage.removeItem(key)}catch{}show();status.textContent='This exercise was reset. Nothing was sent.'});show();}
