const {chromium}=require('C:/Users/dillo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true}); const p=await b.newPage({viewport:{width:1440,height:1000}}); const result={errors:[],images:[],gallery:[],overflow:[]};p.on('pageerror',e=>result.errors.push(e.message)); p.on('response',r=>{if(r.status()>=400)result.errors.push(r.status()+' '+r.url())});
async function go(path){await p.goto('http://127.0.0.1:52365/netlify-site/'+path);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(1100)}
async function shot(name){await p.screenshot({path:'evidence/'+name+'.png'})}
await go('index.html');await shot('root-library-hero');await p.locator('#library').scrollIntoViewIfNeeded();await p.waitForTimeout(1000);await shot('root-library-books');result.headerLogo=await p.locator('.small-logo').evaluate(e=>getComputedStyle(e).opacity);
await go('brand.html');await shot('root-brand-hero');await p.locator('#identity-demo').scrollIntoViewIfNeeded();await shot('root-brand-identity');await p.locator('#identity-replay').click();await p.waitForTimeout(1000);result.identityBox=await p.locator('#identity-demo img').boundingBox();await shot('root-brand-identity-small');for(const category of ['agents','services','imagery']){await p.locator('[data-gallery="'+category+'"]').click();await p.locator('#brand-gallery').scrollIntoViewIfNeeded();await p.locator('#brand-gallery img').evaluateAll(async es=>{for(const e of es){e.loading='eager';await e.decode()}});result.gallery.push({category,count:await p.locator('#brand-gallery img').count()});await shot('root-brand-'+category)}
const manifest=JSON.parse(fs.readFileSync('books-manifest.json'));for(const item of manifest.books){await go(item.url);await p.locator('img').evaluateAll(async es=>{for(const e of es){e.loading='eager';await e.decode()}});result.images.push({book:item.url,ok:await p.locator('img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth))});result.overflow.push({book:item.url,width:await p.evaluate(()=>document.documentElement.scrollWidth),viewport:1440});}
await go(manifest.books[0].url);await shot('root-book-hero');await p.locator('.chapter-links a').nth(5).click();await p.waitForTimeout(1100);result.chapterJump=await p.locator('#chapter-6>h2').boundingBox();await shot('root-book-middle');await p.locator('.reader-tools').first().scrollIntoViewIfNeeded();await shot('root-book-tools');await p.locator('#motion-toggle').click();result.pause=await p.locator('#motion-toggle').getAttribute('aria-pressed');
await p.setViewportSize({width:390,height:844});await go(manifest.books[0].url);await shot('root-book-mobile');result.mobileOverflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await p.keyboard.press('Tab');result.focus=await p.evaluate(()=>document.activeElement.outerHTML.slice(0,200));await p.emulateMedia({reducedMotion:'reduce'});result.reduced=await p.locator('.small-logo').evaluate(e=>getComputedStyle(e).transitionDuration);await go('brand.html');await shot('root-brand-mobile');result.brandMobileOverflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await p.locator('[data-gallery="services"]').click();await p.locator('#brand-gallery').scrollIntoViewIfNeeded();await p.locator('#brand-gallery img').evaluateAll(async es=>{for(const e of es){e.loading='eager';await e.decode()}});await shot('root-icons-mobile');fs.writeFileSync('evidence/netlify-local-final-checks.json',JSON.stringify(result,null,2));await b.close();console.log(JSON.stringify(result));})().catch(e=>{console.error(e);process.exit(1)});
