export const posts = [
  {
    id: 1,
    date: "2026-08-17",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Custom concrete construction",
    slug: "custom-concrete-foundation",
    image: "01-custom-concrete.jpg",
    layout: "split-left",
    eyebrow: "CUSTOM CONCRETE",
    headline: "BUILT BELOW\nTHE SURFACE",
    subhead: "A strong concrete project starts long before the finish goes on.",
    proof: "COMPACTED BASE  •  REBAR  •  4,500 PSI MIX",
    caption: `The finish gets the attention. The preparation earns the lifespan.\n\nOmega begins custom concrete work with the parts that matter below the surface: proper grading, a compacted base, rebar reinforcement, fiber mesh, and a minimum 4,500 PSI concrete mix. That foundation helps patios, driveways, walkways, and flatwork stand up to Colorado soil and freeze thaw cycles.\n\nPlanning a concrete project in the Colorado Springs area? Request a free estimate through our website.\n\n#ColoradoSpringsConcrete #ConcreteContractor #CustomConcrete #ColoradoHomes #OmegaLandscaping`
  },
  {
    id: 2,
    date: "2026-08-19",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Decorative and stamped concrete",
    slug: "stamped-concrete-character",
    image: "02-stamped-concrete.jpg",
    layout: "photo-hero",
    eyebrow: "STAMPED + COLORED CONCRETE",
    headline: "CONCRETE\nWITH CHARACTER",
    subhead: "Stone, slate, wood, and tile inspired finishes with the strength of concrete.",
    proof: "PATTERNS ALIGNED. TEXTURE DEFINED. COLOR PLANNED.",
    caption: `Decorative concrete can give an outdoor space the look of natural stone, slate, wood, or tile with a surface designed for everyday use.\n\nOmega plans the pattern, color, texture, and transitions as one system so the finished patio or walkway feels intentional beside the home. Careful layout matters just as much as the stamp itself.\n\nWant to explore stamped or colored concrete for your patio, walkway, or outdoor living space? Request a free estimate through our website.\n\n#StampedConcrete #DecorativeConcrete #ColoradoSprings #PatioIdeas #OmegaLandscaping`
  },
  {
    id: 3,
    date: "2026-08-21",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "2D and 3D landscape design",
    slug: "design-before-build",
    image: "13-faq-oct09.jpg",
    layout: "diagonal",
    eyebrow: "LANDSCAPE DESIGN",
    headline: "SEE THE WHOLE\nYARD FIRST",
    subhead: "Plan the layout, materials, planting, and movement before construction begins.",
    proof: "2D PLANS  •  3D RENDERINGS  •  ONE BUILD TEAM",
    caption: `A better outdoor project begins with a clear plan.\n\nOmega offers professional 2D plans and 3D renderings for larger design build projects, helping homeowners see how patios, planting areas, turf, rock, drainage, and paths work together before construction starts.\n\nThat early coordination makes decisions easier and keeps the final space connected from one zone to the next.\n\nHave a full yard transformation in mind? Start with a free estimate through our website.\n\n#LandscapeDesign #3DLandscapeDesign #ColoradoSpringsLandscaping #OutdoorLiving #OmegaLandscaping`
  },
  {
    id: 4,
    date: "2026-08-23",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Turf systems and putting greens",
    slug: "turf-putting-greens",
    image: "04-turf-putting.jpg",
    layout: "gallery",
    eyebrow: "TURF SYSTEMS",
    headline: "GREEN WITHOUT\nTHE WEEKLY GRIND",
    subhead: "Engineered base, reliable drainage, and a clean year round surface.",
    proof: "BACKYARDS  •  PET AREAS  •  PUTTING GREENS",
    caption: `Synthetic turf works best when the installation below it is as carefully planned as the surface above it.\n\nOmega builds turf systems with an engineered base, drainage layers, and clean seams for backyards, pet areas, commercial spaces, and custom putting greens. The result stays green without mowing, watering, or muddy patches.\n\nFor golf lovers, custom contours and chipping zones can turn unused yard space into a practical place to play.\n\nRequest a free estimate through our website.\n\n#ArtificialTurf #PuttingGreen #ColoradoSpringsLandscaping #LowMaintenanceYard #OmegaLandscaping`
  },
  {
    id: 5,
    date: "2026-08-24",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Concrete built for Colorado",
    slug: "colorado-concrete-durability",
    image: "05-retaining-wall.jpg",
    layout: "split-left",
    eyebrow: "COLORADO DURABILITY",
    headline: "BUILT FOR\nCOLORADO",
    subhead: "Materials and preparation chosen for local soil, weather, and freeze thaw cycles.",
    proof: "STRUCTURE FIRST. FINISH SECOND. VALUE FOR YEARS.",
    caption: `Colorado concrete has to handle more than foot traffic. Temperature swings, freeze thaw cycles, drainage, and soil movement all put the structure to work.\n\nOmega treats proper base preparation, reinforcement, grading, and high performance concrete as the standard for a lasting project, not optional upgrades.\n\nWhether the project is a driveway, patio, walkway, or structural flatwork, durability starts with the build process.\n\nRequest a free estimate through our website.\n\n#ColoradoConcrete #ColoradoSpringsContractor #ConcreteDriveway #ConcretePatio #OmegaLandscaping`
  },
  {
    id: 6,
    date: "2026-08-26",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Concrete edge detailing",
    slug: "concrete-edge-detailing",
    image: "14-faq-sep05.jpg",
    layout: "photo-hero",
    eyebrow: "CONCRETE DETAILS",
    headline: "CLEAN EDGES.\nCLEAN FINISH.",
    subhead: "Borders, joints, and transitions should look intentional from every angle.",
    proof: "FORM IT RIGHT. FINISH IT CLEAN. CONNECT THE SURFACES.",
    caption: `A polished concrete project is defined by the details at its edges.\n\nBorders, control joints, steps, and transitions need to line up with the home and the surrounding landscape. Clean forming and careful finishing help each surface feel intentional instead of added on.\n\nOmega coordinates concrete with patios, walkways, planting areas, rock, and turf so the connections work visually and functionally.\n\nRequest a free estimate through our website.\n\n#ConcreteDetails #CustomConcrete #ColoradoSpringsConcrete #HardscapeDesign #OmegaLandscaping`
  },
  {
    id: 7,
    date: "2026-08-28",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Drainage solutions",
    slug: "drainage-plan",
    image: "06-lighting-drainage.jpg",
    layout: "diagonal",
    eyebrow: "DRAINAGE SOLUTIONS",
    headline: "WATER NEEDS\nA PLAN",
    subhead: "Protect the yard by coordinating grade, collection, and flow before finish materials go in.",
    proof: "GRADE IT. ROUTE IT. PROTECT THE FINISH.",
    caption: `Drainage is one of the most important parts of an outdoor project, even when it is barely visible after the work is complete.\n\nA good plan looks at where water enters the property, how the grade moves it, where hard surfaces shed it, and how it leaves without damaging beds, turf, walls, or concrete.\n\nOmega coordinates drainage with grading, rock, edging, planting, patios, and complete landscape construction so the whole site works together.\n\nRequest a free estimate through our website.\n\n#LandscapeDrainage #YardDrainage #ColoradoSpringsLandscaping #Grading #OmegaLandscaping`
  },
  {
    id: 8,
    date: "2026-08-30",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Fire pits and seating areas",
    slug: "fire-pits-seating",
    image: "07-fire-feature.jpg",
    layout: "gallery",
    eyebrow: "FIRE + SEATING",
    headline: "MAKE THE FIRE\nTHE CENTERPIECE",
    subhead: "Built in warmth and gathering space for Colorado evenings.",
    proof: "GAS OR WOOD  •  SEATING WALLS  •  COMPLETE SURROUNDS",
    caption: `A fire feature can turn a quiet corner of the yard into the place everyone naturally gathers.\n\nOmega builds gas and wood burning fire pits, fireplaces, integrated seating walls, and the surrounding patio or paver space as one coordinated outdoor living area. Placement, circulation, materials, and comfortable seating all matter to the final experience.\n\nThinking about a fire feature for fall evenings in Colorado? Request a free estimate through our website.\n\n#FirePit #OutdoorLiving #BackyardDesign #ColoradoSpringsLandscaping #OmegaLandscaping`
  },
  {
    id: 9,
    date: "2026-08-31",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Custom edging and borders",
    slug: "custom-edging-borders",
    image: "08-edging.jpg",
    layout: "split-left",
    eyebrow: "CUSTOM EDGING",
    headline: "DETAILS DRAW\nTHE LINE",
    subhead: "Keep concrete, turf, rock, mulch, and planting beds cleanly separated.",
    proof: "STEEL  •  STONE  •  CURBING  •  SOLDIER COURSES",
    caption: `Clean borders do more than make a landscape look finished. They help keep rock, mulch, turf, and planting soil where they belong.\n\nOmega installs concrete curbing, steel edging, stone borders, and decorative soldier courses around patios and driveways. The right detail can define transitions, support drainage flow, and reduce material movement over time.\n\nIf your yard feels unfinished at the edges, request a free estimate through our website.\n\n#LandscapeEdging #HardscapeDetails #ColoradoSpringsLandscaping #LandscapeConstruction #OmegaLandscaping`
  },
  {
    id: 10,
    date: "2026-09-02",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "One team design build",
    slug: "one-team-design-build",
    image: "15-home-project.jpg",
    layout: "photo-hero",
    eyebrow: "DESIGN BUILD",
    headline: "ONE TEAM.\nSTART TO FINISH.",
    subhead: "Design, engineering, and construction stay aligned from consultation to walkthrough.",
    proof: "ONE PLAN. ONE BUILD TEAM. ONE POINT OF ACCOUNTABILITY.",
    caption: `Outdoor projects move more smoothly when the design and construction teams are working from the same plan.\n\nOmega handles design, engineering, and construction in house, from the first consultation and 3D planning through site work, installation, and the final walkthrough. That creates clearer communication and keeps every part of the project connected to the original vision.\n\nReady to plan a complete outdoor transformation? Request a free estimate through our website.\n\n#DesignBuild #LandscapeContractor #OutdoorTransformation #ColoradoSprings #OmegaLandscaping`
  },
  {
    id: 11,
    date: "2026-09-04",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Contractor concrete partnerships",
    slug: "contractor-concrete-partnerships",
    image: "09-contractor-work.jpg",
    layout: "diagonal",
    eyebrow: "BUILDER PARTNERSHIPS",
    headline: "BUILT TO\nCOORDINATE",
    subhead: "Dependable structural concrete and flatwork for custom homes and complex sites.",
    proof: "FOUNDATIONS  •  FLATWORK  •  CUSTOM HOME SUPPORT",
    caption: `Complex construction needs concrete partners who can coordinate with the larger build.\n\nOmega works with general contractors on structural concrete, foundation systems, custom home projects, and professionally executed flatwork. The focus stays on dependable preparation, clear coordination, and a finished product that supports the project around it.\n\nContractors and developers can use our website to discuss an upcoming Colorado Springs area project.\n\n#GeneralContractor #StructuralConcrete #ConcreteFlatwork #ColoradoConstruction #OmegaLandscaping`
  },
  {
    id: 12,
    date: "2026-09-06",
    time: "10:00 AM",
    timezone: "America/Denver",
    topic: "Fall project planning",
    slug: "fall-project-planning",
    image: "03-full-landscape.jpg",
    layout: "gallery",
    eyebrow: "START THE CONVERSATION",
    headline: "START WITH A\nBETTER PLAN",
    subhead: "Bring the patio, landscape, concrete, drainage, and lighting into one clear project.",
    proof: "FREE INITIAL ESTIMATES  •  COLORADO SPRINGS AREA",
    caption: `The best time to simplify an outdoor project is before construction begins.\n\nStart by identifying how you want to use the space, what needs to change, and which parts should be designed together. Patios, concrete, drainage, lighting, turf, planting, rock, and circulation all work better when they share one plan.\n\nOmega serves Colorado Springs, Monument, Falcon, Peyton, Black Forest, and nearby communities.\n\nRequest a free initial estimate through our website.\n\n#ColoradoSpringsLandscaping #OutdoorLiving #LandscapeDesign #ConcreteContractor #OmegaLandscaping`
  }
];
