export const contentBySlug = {
  'advance-exterior': {
    tagline: 'Protect the home. Finish the exterior well.',
    hero: 'Roofing and siding projects begin with a careful look at the property, a direct explanation of the options, and a plan that respects the home beneath the work.',
    servicesTitle: 'Exterior work built around the condition of your home',
    services: [
      ['Roof inspections', 'A thorough inspection helps separate a repairable problem from a roof that is nearing the end of its useful life. The goal is a clear recommendation, not a rushed decision.'],
      ['Roof repair and replacement', 'From isolated leaks and storm damage to complete replacement, the scope is shaped around the roof system, the materials, and the long-term protection the property needs.'],
      ['Siding repair and replacement', 'Exterior siding work can address damaged areas, weather exposure, and a tired appearance while creating a more complete, better-protected envelope for the home.'],
    ],
    missionTitle: 'Straight answers before the first shingle moves',
    mission: 'Advance Exterior Solutions is presented as a local exterior contractor for homeowners who want to understand what is happening above and around their home. The mission is simple: inspect carefully, explain the condition in plain language, and recommend work that fits the property rather than forcing every customer into the same package.',
    feature: ['A plan for the whole exterior', 'Roofing and siding affect one another. Looking at flashing, transitions, drainage, penetrations, and exposed wall surfaces together can reveal the source of a problem and help the finished work feel intentional from curb to ridge.'],
    spotlight: ['Repair when repair makes sense', 'Not every stain or missing shingle requires a complete replacement. A useful contractor explains what can be repaired, what should be watched, and what would justify a larger project later.'],
    catalog: [['Inspection and assessment', 'Begin with the condition of the roof and a practical conversation about priorities.'], ['Residential roofing', 'Explore repair and replacement paths for the main protective system of the home.'], ['Siding solutions', 'Address damaged siding, weather exposure, and exterior continuity with one coordinated plan.']],
  },
  'al-tacos-locos': {
    tagline: 'Bright flavors, generous plates, zero fuss.',
    hero: 'Tacos, carne asada, fresh toppings, and familiar Mexican favorites come together in a neighborhood restaurant made for quick lunches, relaxed dinners, and food worth sharing.',
    servicesTitle: 'A menu that gives every craving somewhere to land',
    services: [
      ['Tacos made to order', 'Choose the filling, bring on the cilantro and lime, and build a plate that is simple, colorful, and satisfying from the first bite to the last.'],
      ['Full meals and house favorites', 'Go beyond tacos with hearty entrées, sides, and combinations that make lunch or dinner easy for one person, a family, or a table of friends.'],
      ['Catering for the group', 'A catering menu turns the same bold flavors into a flexible spread for office lunches, birthdays, family gatherings, and casual celebrations.'],
    ],
    missionTitle: 'Make Jenkintown hungry before the menu even opens',
    mission: 'Al Tacos Locos should feel as welcoming online as a favorite counter around the corner. The experience leads with the food, keeps ordering paths obvious, and gives visitors enough detail to decide what sounds good without burying the appetite under restaurant jargon.',
    feature: ['Color, heat, acid, crunch', 'The pleasure is in the contrast: seared meat against cool toppings, bright lime against rich fillings, and crisp textures alongside warm tortillas. Every plate should look as lively as it tastes.'],
    spotlight: ['Easy to order, easy to share', 'Whether the plan is a fast pickup or food for a full table, the next step should stay clear. Browse the current menu, call with a question, or start a catering conversation from the official site.'],
    catalog: [['Taco menu', 'Find the combinations, fillings, and toppings that fit the meal you want today.'], ['Entrées and sides', 'Round out the order with satisfying plates and shareable additions.'], ['Catering menu', 'Plan a spread that travels well and gives a group plenty of choice.']],
  },
  'bala-financial': {
    tagline: 'Perspective for the decisions that shape a life.',
    hero: 'Financial planning should connect the numbers to the person behind them. Bala Financial Group brings investment planning, retirement conversations, and long-range coordination into one understandable view.',
    servicesTitle: 'Guidance organized around milestones, not products',
    services: [
      ['Investment planning', 'Build an investment approach around time horizon, priorities, risk tolerance, and the role each account plays in the larger financial picture.'],
      ['Retirement strategy', 'Turn retirement from a distant date into a working plan that considers savings, income needs, taxes, insurance, and the life you expect to fund.'],
      ['Family and legacy planning', 'Coordinate the financial pieces that support a growing family, a business transition, charitable goals, or the transfer of assets to the people and causes that matter.'],
    ],
    missionTitle: 'Reliable care with room for the whole conversation',
    mission: 'Bala Financial Group serves professionals, growing families, and retirees who need more than a collection of accounts. The work is framed around tailored solutions, ongoing education, and the steady guidance required when markets move, priorities change, or a major life decision comes into view.',
    feature: ['A plan should move when life moves', 'Marriage, a career change, a business decision, retirement, or a new responsibility can alter the financial picture. Regular review keeps the strategy connected to current goals instead of leaving it frozen in the year it was created.'],
    spotlight: ['Useful resources between meetings', 'Market updates, calculators, tax resources, and plain-language financial education can help clients arrive at conversations with better questions and a clearer sense of the choices in front of them.'],
    catalog: [['Retirement planning', 'Connect savings, income, risk, and timing in one coordinated retirement view.'], ['Investment strategy', 'Clarify the purpose of each investment and how it supports the plan.'], ['Resource center', 'Use practical tools and education to prepare for the next financial conversation.']],
  },
  'balance-studios': {
    tagline: 'Train with skill. Leave with confidence.',
    hero: 'Brazilian Jiu-Jitsu, Muay Thai, kids programs, and practical self-defense come together in a school designed to help beginners start comfortably and experienced students keep growing.',
    servicesTitle: 'A place to learn, practice, and belong',
    services: [
      ['Gracie Brazilian Jiu-Jitsu', 'Learn leverage, positioning, control, and problem-solving through structured instruction that gives new students a clear foundation and advanced students room to refine.'],
      ['Muay Thai kickboxing', 'Develop striking fundamentals, conditioning, timing, and composure in classes that reward consistency and make every round an opportunity to improve.'],
      ['Kids and women’s programs', 'Purpose-built classes create an approachable route into martial arts, self-defense, discipline, and confidence for students who want the right learning environment.'],
    ],
    missionTitle: 'Serious instruction without an intimidating first step',
    mission: 'Balance Studios is a family-focused martial arts community with level-specific training and a positive atmosphere. Its mission is not to make newcomers prove they belong. It is to give each student a safe, structured place to learn difficult skills, train with good partners, and build confidence over time.',
    feature: ['Start beside people at your level', 'Beginner-friendly classes make the first week easier to understand. Students can focus on posture, movement, safety, and core technique before complexity or intensity becomes the center of the experience.'],
    spotlight: ['Progress is a practice', 'Martial arts growth comes from small technical gains repeated consistently. Coaching, live practice, and a supportive room help turn those repetitions into calm decision-making on and off the mat.'],
    catalog: [['Brazilian Jiu-Jitsu', 'Build a technical ground game through structured, progressive instruction.'], ['Muay Thai', 'Train striking, movement, and conditioning in a focused class environment.'], ['Try a free week', 'Meet the coaches, see the room, and experience the training before choosing a program.']],
  },
  'boyle-energy': {
    tagline: 'Comfort, fuel, and service from one local team.',
    hero: 'Heating, cooling, oil, and propane needs rarely arrive on the same schedule. Boyle Energy brings delivery, maintenance, repair, and equipment guidance together for homes across the Philadelphia region.',
    servicesTitle: 'Home comfort support through every season',
    services: [
      ['Heating and cooling service', 'From routine tune-ups to an unexpected loss of heating or air conditioning, responsive service helps restore comfort and keep equipment operating as intended.'],
      ['Oil and propane delivery', 'Reliable fuel delivery and clear account options make it easier to plan for the months when the home depends on steady energy every day.'],
      ['Equipment and service plans', 'Compare products, preventive maintenance, and service-plan options with guidance that considers the home, the system, and the owner’s priorities.'],
    ],
    missionTitle: 'Keep the house comfortable and the next step clear',
    mission: 'Boyle Energy serves homeowners who need practical answers about fuel, HVAC equipment, maintenance, and repairs. The mission is to make home energy easier to manage through dependable delivery, knowledgeable service, and long-term relationships that extend beyond a single appointment.',
    feature: ['Preventive care before peak weather', 'A tune-up can surface worn components, airflow problems, or performance issues before the hottest or coldest stretch of the year. It also gives the homeowner time to make a reasoned decision instead of an emergency one.'],
    spotlight: ['One conversation across the comfort system', 'Fuel supply, equipment condition, service history, and household needs all influence comfort. Bringing those pieces together helps a customer understand both today’s fix and tomorrow’s maintenance plan.'],
    catalog: [['HVAC service', 'Schedule maintenance, diagnosis, or repair for heating and cooling equipment.'], ['Fuel delivery', 'Review oil and propane delivery options for the home.'], ['Service plans', 'Compare ongoing care designed to reduce surprises and support system reliability.']],
  },
  'brandywine-auto-parts': {
    tagline: 'The right part keeps the whole job moving.',
    hero: 'Brandywine Auto Parts is built for drivers, technicians, and shops that need a clear answer at the counter, a dependable way to source parts, and less time lost chasing the wrong fit.',
    servicesTitle: 'Parts support for the repair in front of you',
    services: [
      ['Parts lookup and sourcing', 'Start with the vehicle details and the job at hand. A careful lookup helps narrow the options and reduces the frustration of leaving with a part that does not match.'],
      ['Everyday repair components', 'Find the maintenance and replacement parts that keep common repairs moving, from wear items and filters to electrical, cooling, and under-hood needs.'],
      ['Counter help for local shops', 'Repair professionals need quick communication, practical alternatives, and a supplier who understands that a vehicle occupying a bay cannot wait all day for an answer.'],
    ],
    missionTitle: 'Useful knowledge belongs at the counter',
    mission: 'A parts store earns loyalty by helping people solve the problem, not simply by pointing toward an aisle. Brandywine Auto Parts is presented as a local resource where the conversation starts with fit, availability, and the real repair the customer is trying to complete.',
    feature: ['Bring the details that prevent guesswork', 'Year, make, model, engine, trim, and the old part itself can all help narrow a search. The more accurately the vehicle is identified, the faster the counter can get from a broad catalog to a useful option.'],
    spotlight: ['Keep the bay and the weekend on schedule', 'For a professional shop, a delayed part means lost time. For a home mechanic, it can consume the only free afternoon available. Clear sourcing and honest availability matter because the repair has a clock.'],
    catalog: [['Find a part', 'Call with the vehicle details and the component you are trying to replace.'], ['Shop essentials', 'Ask about the maintenance items and supplies that support routine repair work.'], ['Professional counter support', 'Build a direct parts relationship for recurring shop and fleet needs.']],
  },
  'caise-benefits': {
    tagline: 'Insurance choices explained like a conversation.',
    hero: 'Health, life, disability, Medicare, dental, vision, personal, and business coverage can be difficult to compare. Caise Benefits helps clients understand the options and keep plans aligned as needs change.',
    servicesTitle: 'Coverage for people, families, and businesses',
    services: [
      ['Health and Medicare guidance', 'Review plan structures, networks, costs, and enrollment considerations with a professional who can help translate the details into a practical choice.'],
      ['Life and disability coverage', 'Protect income, responsibilities, and the people who depend on you with coverage shaped around the role it needs to play in the broader plan.'],
      ['Employee and business benefits', 'Support recruiting and retention with benefit options that account for workforce needs, administration, budget, and changes to the team throughout the year.'],
    ],
    missionTitle: 'Treat every policy as part of someone’s life',
    mission: 'Caise Benefits describes its clients as family. That promise becomes meaningful when plans are reviewed, questions receive direct answers, and changes such as adding employees or adjusting coverage are handled with care. The mission is to make insurance simpler without pretending the decisions are small.',
    feature: ['Review the plan after life changes', 'A new job, a growing family, a business hire, retirement, or a change in health needs can alter what suitable coverage looks like. A periodic review keeps the policy connected to the person or organization it serves.'],
    spotlight: ['Cost matters. Fit matters too.', 'The lowest premium is not always the best value if the network, benefits, limits, or administration do not support the real need. A useful comparison looks at the complete tradeoff.'],
    catalog: [['Personal coverage', 'Explore health, life, disability, dental, vision, Medicare, and personal-line options.'], ['Business insurance', 'Review protection and benefits designed around the needs of an organization.'], ['Request a quote', 'Start with the people, priorities, and budget the coverage needs to support.']],
  },
  'captain-car-wash': {
    tagline: 'A clean car changes the whole drive.',
    hero: 'Captain Car Wash turns an everyday errand into a quick reset for the vehicle. Choose a wash, pull through, and leave with the grime gone and the finish looking cared for.',
    servicesTitle: 'A straightforward route to a cleaner car',
    services: [
      ['Single washes', 'Pick the wash that matches the day, whether the goal is a routine clean or extra attention after weather, road salt, pollen, or a long week of driving.'],
      ['Unlimited Club', 'Frequent drivers can wash more often for one monthly price, making it easier to keep the vehicle clean instead of waiting for the buildup to become obvious.'],
      ['Plan management online', 'Join, review, or manage an Unlimited Club plan online so the account stays as convenient as the wash itself.'],
    ],
    missionTitle: 'Cleanliness should feel easy enough to repeat',
    mission: 'Captain Car Wash connects vehicle care with the simple lift people feel when they step into a clean car. The mission is to provide a friendly, dependable wash experience that fits an ordinary schedule and makes regular maintenance feel less like a chore.',
    feature: ['Wash after the weather, not weeks later', 'Rain film, road salt, pollen, dust, and everyday traffic can dull a vehicle quickly. Convenient hours and a repeatable process make it easier to respond while the mess is fresh.'],
    spotlight: ['Built for the frequent driver', 'Commuters and busy households see the road every day. An unlimited plan can make sense when a customer values a consistently clean vehicle and wants the freedom to wash whenever conditions call for it.'],
    catalog: [['Choose a wash', 'Compare current wash options and select the level of care that fits the vehicle.'], ['Join the Unlimited Club', 'Turn regular washes into one simple monthly routine.'], ['Manage your plan', 'Handle membership details online without adding another errand.']],
  },
  'custom-it-solutions': {
    tagline: 'Technology should move the business, not slow it down.',
    hero: 'Custom IT Solutions aligns managed services, security, Microsoft cloud tools, and enterprise systems with the way a company works today and the way it plans to grow.',
    servicesTitle: 'Business technology with an operating purpose',
    services: [
      ['Managed services and security', 'Support endpoints, servers, users, and security controls with a plan designed to improve reliability, strengthen protection, and reduce avoidable interruptions.'],
      ['Microsoft 365 and Business Central', 'Plan migrations, collaboration, cloud operations, and business-management workflows with guidance that helps teams use the platform instead of merely owning licenses.'],
      ['Infor XA and custom integration', 'Connect EDI, enterprise data, self-service portals, and custom software to improve visibility and reduce the manual work between established systems.'],
    ],
    missionTitle: 'Build lasting partnerships around business outcomes',
    mission: 'Custom IT Solutions positions technology as a business tool rather than a collection of disconnected products. The mission is to understand the client’s operational goals, shape a support plan around real constraints, and create a clearer return on the time and money invested in IT.',
    feature: ['Security belongs inside everyday operations', 'Protection is stronger when patching, endpoint controls, access, backup, monitoring, and staff workflows reinforce one another. A managed approach turns those moving pieces into a repeatable operating discipline.'],
    spotlight: ['Modernize without abandoning what already works', 'Many organizations depend on mature systems while adopting newer cloud and collaboration tools. Thoughtful integration can extend the value of core platforms and create better access without forcing change for its own sake.'],
    catalog: [['Managed IT', 'Create a support and security plan around users, devices, systems, and compliance needs.'], ['Microsoft solutions', 'Improve collaboration and business operations with Microsoft 365 and Business Central.'], ['Enterprise integration', 'Connect Infor XA, EDI, portals, and custom workflows around the work teams perform.']],
  },
  'dirt-work-solutions': {
    tagline: 'Start with the ground. Build from there.',
    hero: 'Excavation, grading, site preparation, and drainage work create the conditions every later trade depends on. Dirt Work Solutions approaches the job from the first cut to the final contour.',
    servicesTitle: 'Site work shaped around what comes next',
    services: [
      ['Excavation and site preparation', 'Clear, cut, and prepare the working area with attention to access, elevations, existing conditions, and the construction that will follow.'],
      ['Grading and drainage', 'Move water with intention by shaping the site, correcting low areas, and preparing surfaces that support stable use over time.'],
      ['Trenching and utility support', 'Create clean, properly planned routes for utility, drainage, and infrastructure work while coordinating the excavation with the larger project.'],
    ],
    missionTitle: 'Family-owned work with the owners in the field',
    mission: 'Dirt Work Solutions describes the company as a family operation where customers and team members work with the owners, not at a distance from them. That hands-on approach suits site work, where changing ground conditions and the needs of the next trade require practical decisions in real time.',
    feature: ['Good site work is work the next crew can trust', 'The finished excavation is not only about what has been removed. It is about whether the grades, access, compaction, drainage, and prepared areas make the next phase safer and more predictable.'],
    spotlight: ['Plan for water before water finds the problem', 'Drainage issues can undermine lawns, drives, foundations, and outdoor projects. Reading the slope and planning where runoff should travel is a core part of responsible earthwork.'],
    catalog: [['Excavation', 'Discuss the cut, access, and site conditions for the project ahead.'], ['Grading', 'Shape elevations and finished surfaces around use, stability, and drainage.'], ['Project consultation', 'Bring the plans, property details, and schedule into one practical site-work conversation.']],
  },
  'ember-and-ale': {
    tagline: 'Fire, dough, and a good drink at the table.',
    hero: 'Artisan pizza, Italian-inspired dishes, sandwiches, salads, cocktails, and beer make Ember & Ale a place for the quick weeknight meal and the evening that turns into another round.',
    servicesTitle: 'A menu built for the whole table',
    services: [
      ['Brick-oven and artisan pizza', 'Crisp edges, thoughtful toppings, and the comfort of a hot pie give the table a centerpiece that is easy to share and hard to stop eating.'],
      ['Italian-inspired plates', 'Sandwiches, fresh salads, and satisfying house dishes offer enough range for a casual lunch, a full dinner, or the person who did not come for pizza.'],
      ['Craft cocktails and beer', 'A considered drink list gives the food a partner, whether the mood calls for a bright cocktail, a cold beer, or one more reason to stay awhile.'],
    ],
    missionTitle: 'Give Collegeville a meal people want to talk about',
    mission: 'Ember & Ale is presented as a neighborhood gathering place where simple food receives serious attention. The mission is not to overcomplicate Italian comfort. It is to make the dough, flavors, drinks, and hospitality memorable enough that guests return with someone new.',
    feature: ['The best table order has contrast', 'Pair a rich pizza with a crisp salad, a cheesy loaf with something bright, or a savory sandwich with a well-chosen drink. The menu works best when everyone can reach across the table.'],
    spotlight: ['Order online or settle in', 'Some nights call for a box on the way home. Others deserve a drink, a warm plate, and time at the table. Clear ordering and location details should support both.'],
    catalog: [['View the menu', 'Explore current pizzas, sandwiches, salads, plates, and drinks before the visit.'], ['Order online', 'Start a pickup order directly from the restaurant’s current ordering path.'], ['Plan the table', 'Check hours, directions, and contact details for the Collegeville location.']],
  },
  'euphoria-nail-bar': {
    tagline: 'A polished hour in the middle of a busy week.',
    hero: 'Manicures, pedicures, and waxing services give Manayunk a place to slow down, choose the details, and leave feeling more put together than when the appointment began.',
    servicesTitle: 'Care for the details people notice first',
    services: [
      ['Manicures', 'Shape, cuticle care, color, and a clean finish turn a routine appointment into a small but visible reset for hands that do a lot every day.'],
      ['Pedicures', 'Settle in for foot and nail care designed to refresh, smooth, and finish with a color or natural look that suits the season.'],
      ['Waxing services', 'Targeted waxing can help maintain a polished look with an appointment that is direct, comfortable, and easy to fit into the rest of the day.'],
    ],
    missionTitle: 'Make self-care feel welcoming, not complicated',
    mission: 'Euphoria Nail Bar is positioned as a neighborhood salon where clients can choose a service, ask questions, and enjoy the appointment without decoding an overwhelming experience. The mission is to pair careful beauty services with a calm atmosphere and a finish clients are happy to wear out the door.',
    feature: ['Bring the idea or ask for guidance', 'A reference color, an upcoming event, a preferred shape, or simply a request for something easy to maintain gives the technician a useful starting point for the service.'],
    spotlight: ['Book around the life you already have', 'With evening and weekend hours listed, the salon can fit into a workweek, a Saturday plan, or the preparation before an occasion. Call to confirm current availability.'],
    catalog: [['Manicures', 'Choose a clean, polished finish for everyday wear or a specific occasion.'], ['Pedicures', 'Refresh feet and nails with care designed for comfort and a lasting result.'], ['Waxing', 'Ask about current waxing services and select the appointment that matches your needs.']],
  },
  'fusion-gyms': {
    tagline: 'Train on your terms. Keep raising the standard.',
    hero: 'Premium equipment, specialized training areas, and round-the-clock access give powerlifters, boxers, students, and everyday athletes the freedom to train when and how they work best.',
    servicesTitle: 'A gym designed around serious variety',
    services: [
      ['Strength and performance training', 'Use purpose-built equipment and dedicated space to develop strength, power, and technical consistency without waiting for a limited training setup.'],
      ['Boxing and specialized zones', 'Move beyond the standard cardio row with environments that support striking practice, athletic conditioning, and more focused styles of training.'],
      ['Flexible membership access', 'No-contract options and 24/7 access at the Grant Avenue location make it easier to build training around school, shifts, family, and real life.'],
    ],
    missionTitle: 'Remove the excuses that come from the facility',
    mission: 'Fusion Gyms states a clear mission: invest in high-quality equipment, create training environments that inspire results, and keep access convenient and affordable. The gym supports first-timers and committed athletes by giving both enough room and enough tools to pursue their own definition of progress.',
    feature: ['The room should match the goal', 'A powerlifter, boxer, student, and general fitness member do not need identical environments. Distinct training zones let each person focus while still drawing energy from one active gym.'],
    spotlight: ['Access matters when motivation arrives early or late', 'A schedule should not decide whether a workout happens. Around-the-clock access helps members protect consistency when workdays change, classes run late, or the best training hour falls outside a typical timetable.'],
    catalog: [['Explore memberships', 'Compare current access and membership options without a long-term contract.'], ['Tour the gym', 'See the equipment, training areas, and atmosphere before choosing where to train.'], ['Grant Avenue location', 'Find directions, contact information, and current location details.']],
  },
  'golden-sea': {
    tagline: 'Chinese favorites made for the table at home.',
    hero: 'Golden Sea brings a broad Chinese menu to Blue Bell with the comfort of a family-run kitchen and the convenience of a takeout order planned around lunch, dinner, or a full family spread.',
    servicesTitle: 'Build the order around how the table eats',
    services: [
      ['Classic entrées', 'Choose familiar chicken, beef, pork, seafood, and vegetable dishes that give everyone a dependable favorite while leaving room to try something new.'],
      ['Rice, noodles, and starters', 'Round out the meal with fried rice, lo mein, soups, dumplings, rolls, and shareable starters that make one order feel complete.'],
      ['Takeout for one or many', 'Plan a quick individual meal or combine several dishes family-style so the table can sample a little of everything.'],
    ],
    missionTitle: 'Keep a family kitchen connected to its community',
    mission: 'Golden Sea describes itself as a family-owned restaurant that has served the community since 1992. The mission is carried in familiar food, generous choice, and the kind of dependable local presence that turns a restaurant into part of a household’s regular rotation.',
    feature: ['Order for variety, not just volume', 'A balanced takeout spread can mix a savory entrée, a vegetable dish, rice or noodles, and a few starters. That variety keeps the meal interesting and gives different preferences a place at the table.'],
    spotlight: ['Confirm today’s service before the drive', 'The current site emphasizes takeout and publishes specific weekly hours. Call or use the official site to confirm the latest service details before visiting.'],
    catalog: [['Browse the menu', 'Review current entrées, starters, soups, rice, noodles, and vegetable dishes.'], ['Plan a family order', 'Combine complementary dishes into a shareable meal with plenty of variety.'], ['Call for takeout', 'Confirm timing and place the order directly with the Blue Bell restaurant.']],
  },
  'ivc-wealth': {
    tagline: 'Retirement plans made personal at every level.',
    hero: 'IVC Wealth Advisors supports plan sponsors and participants with investment management, retirement-plan guidance, and service designed to connect institutional structure with individual outcomes.',
    servicesTitle: 'Retirement guidance for the organization and the individual',
    services: [
      ['Plan sponsor support', 'Help fiduciaries and employers evaluate plan design, investment structure, participant needs, and the ongoing work required to keep a retirement program useful.'],
      ['Participant engagement', 'Turn retirement-plan access into informed action through education, personalization, and guidance that helps each participant understand the next decision.'],
      ['Investment management', 'Align investment strategies with stated objectives, time horizon, risk considerations, and the broader responsibilities of the plan or individual investor.'],
    ],
    missionTitle: 'Put the client’s stated objective at the center',
    mission: 'IVC Wealth Advisors presents a service-centered approach built on understanding the client’s vision. Its mission is to combine experience, intelligent investment management, automation, and personal attention so retirement plans work better for the organizations that offer them and the people counting on them.',
    feature: ['Personalization makes a plan usable', 'A retirement program can be well designed and still underperform for participants who do not know how to act. Clear education and individualized guidance help turn an available benefit into a working part of someone’s future.'],
    spotlight: ['Values can sit alongside financial objectives', 'Charitable gifting and long-range legacy goals may belong in the same conversation as investment strategy. Coordinating those priorities can help the plan reflect both practical needs and personal intent.'],
    catalog: [['Plan sponsor services', 'Review plan structure, investments, governance, and participant support.'], ['Participant guidance', 'Give employees a clearer route from enrollment to informed retirement decisions.'], ['Investment approach', 'Understand how objectives and service shape the recommended strategy.']],
  },
  'mings-chinese': {
    tagline: 'Hatboro’s Chinese favorites, prepared with range.',
    hero: 'Egg rolls, dumplings, soups, fried rice, lo mein, vegetables, chicken, beef, and house specialties give Ming’s a menu with room for the familiar order and the next dish to try.',
    servicesTitle: 'A full menu for different appetites',
    services: [
      ['Classic Chinese dishes', 'Build the meal around comforting favorites such as sesame chicken, beef with broccoli, chow mein, fried rice, or a well-loved house combination.'],
      ['Vegetable and tofu options', 'A broad menu makes it easier to choose meat-free dishes, fresh vegetables, tofu preparations, and sides that still feel like a complete dinner.'],
      ['Soups, dumplings, and noodles', 'Start with something warm or make noodles the center of the order with wonton soup, dumplings, lo mein, and other shareable staples.'],
    ],
    missionTitle: 'Give every regular a favorite and every newcomer a place to begin',
    mission: 'Ming’s Restaurant is presented as a Hatboro kitchen with a wide-ranging Chinese menu and a loyal local following. The mission is to make ordering easy, keep the food recognizable, and offer enough depth that the same household can return without repeating the same meal every time.',
    feature: ['Start with the table, then choose the dishes', 'One crisp starter, one vegetable dish, one noodle or rice option, and a pair of contrasting entrées can create a balanced family-style order without turning the menu into a puzzle.'],
    spotlight: ['Please confirm the current service notice', 'The existing restaurant site displays a temporary closure notice. Check the official site or call before planning a visit so the latest reopening and ordering information is clear.'],
    catalog: [['See the menu', 'Explore the current range of entrées, soups, dumplings, noodles, and rice dishes.'], ['Build a family order', 'Mix familiar favorites with a dish the table has not tried before.'], ['Check current status', 'Confirm reopening, hours, and service availability before traveling to the restaurant.']],
  },
  'ooka-hibachi': {
    tagline: 'Hibachi energy. Sushi precision. One shared table.',
    hero: 'Ooka brings sushi, hibachi, and Japanese dining to Willow Grove and neighboring communities with options for the lively group dinner, the quiet roll at the bar, and everything between.',
    servicesTitle: 'Choose the experience that fits the occasion',
    services: [
      ['Hibachi dining', 'Gather around the grill for a meal where cooking, conversation, and the pace of the table become part of the experience.'],
      ['Sushi and sashimi', 'Explore rolls, nigiri, sashimi, and combinations shaped around clean flavors, careful presentation, and the pleasure of choosing several pieces to share.'],
      ['Lunch and dinner', 'Plan a focused midday meal or settle in for an evening with appetizers, entrées, sushi, and room for the table to take its time.'],
    ],
    missionTitle: 'Make the meal feel like the occasion',
    mission: 'Ooka is positioned around two complementary forms of Japanese dining: the theater and shared energy of hibachi, and the detail-driven experience of sushi. The mission is to create a polished restaurant visit that works for celebrations, family meals, date nights, and the guest who simply knows exactly what roll they want.',
    feature: ['Hibachi is built for the group', 'The grill gives everyone a common focal point while individual entrée choices keep the meal personal. It is a natural fit when the table wants more interaction than a standard dinner service.'],
    spotlight: ['Four towns, one starting point', 'The current Ooka presence references Doylestown, Willow Grove, Montgomeryville, and Riverside. Use the official site to confirm the right location, current menu, reservations, and hours.'],
    catalog: [['Willow Grove', 'Find contact, directions, and current service details for the Easton Road location.'], ['Hibachi', 'Plan a grill-side meal for the family, a group, or a celebration.'], ['Sushi', 'Explore rolls, sashimi, nigiri, and combinations for lunch or dinner.']],
  },
  'owm-law': {
    tagline: 'Regional counsel for personal and consequential matters.',
    hero: 'O’Donnell, Weiss & Mattei brings a full-service legal team to individuals and families facing decisions in elder law, family law, criminal defense, injury matters, and other areas where clear counsel matters.',
    servicesTitle: 'Legal guidance that begins with the matter in front of you',
    services: [
      ['Elder law and benefits', 'Navigate guardianship, Medicaid, Social Security Disability, veterans benefits, and the legal planning that can accompany changing care and family responsibilities.'],
      ['Family law', 'Approach custody, divorce, support, property division, and modifications with counsel focused on the legal issues and the practical consequences for the family.'],
      ['Criminal defense', 'Respond to DUI, traffic violations, drug charges, and other criminal matters with an attorney who can explain the process, the stakes, and the available defense path.'],
    ],
    missionTitle: 'Dedication is measured in preparation and communication',
    mission: 'O’Donnell, Weiss & Mattei presents itself as a committed regional law firm with attorneys across multiple practice areas. The mission is to meet a client at a difficult or important moment, define the legal problem clearly, and bring the right experience to the work that follows.',
    feature: ['Start with the facts and the deadline', 'Legal options can depend on timing, documents, prior orders, notices, medical records, or the exact history of an event. An early conversation helps identify what must be preserved and what needs attention first.'],
    spotlight: ['The right attorney depends on the matter', 'A full-service firm can route a client toward counsel whose practice aligns with the issue. That matters when family, financial, health, and legal questions overlap.'],
    catalog: [['Meet the attorneys', 'Review the firm’s legal team and the experience connected to each practice area.'], ['Explore practice areas', 'Find the legal service that most closely matches the issue you need to discuss.'], ['Request a consultation', 'Share the basic matter and connect with the Pottstown office about next steps.']],
  },
  'red-hill-greenhouse': {
    tagline: 'Flowers that say what the card cannot.',
    hero: 'Seasonal bouquets, roses, plants, gifts, and occasion-specific arrangements help customers celebrate, comfort, thank, welcome, and brighten someone’s day from a local Red Hill florist.',
    servicesTitle: 'Choose the feeling first. Build the flowers from there.',
    services: [
      ['Everyday and seasonal bouquets', 'Mark the season or send an unexpected lift with fresh color, varied texture, and an arrangement designed to feel generous without needing a formal occasion.'],
      ['Flowers for life’s occasions', 'Find an appropriate direction for birthdays, anniversaries, new babies, romance, gratitude, get-well wishes, sympathy, and the moments that deserve care.'],
      ['Plants, roses, and gifts', 'Go beyond a mixed bouquet with a lasting plant, a classic rose arrangement, or a gift presentation that suits the recipient and the message.'],
    ],
    missionTitle: 'Make the gesture feel personal before it arrives',
    mission: 'Red Hill Greenhouse & Florist gives customers a local way to turn emotion into something tangible. The mission is to help each sender choose flowers that fit the person, the occasion, and the tone, then present them with the care the gesture deserves.',
    feature: ['The occasion guides more than the color', 'A celebratory arrangement can be bright and expansive. Sympathy flowers may call for calm structure and restraint. A florist can help translate the relationship and the message into an appropriate design.'],
    spotlight: ['Local guidance helps when words are difficult', 'Not every customer arrives knowing the flower names or the right style. Sharing who the arrangement is for, why it is being sent, and what you hope it communicates gives the designer a meaningful starting point.'],
    catalog: [['Shop best sellers', 'Start with popular arrangements and adapt the choice to the recipient.'], ['Browse by occasion', 'Find flowers organized around the moment and the message you want to send.'], ['Plants and gifts', 'Choose a lasting alternative or add a thoughtful extra to the delivery.']],
  },
  'roccos-brick-oven': {
    tagline: 'Brick-oven pizza, fresh ingredients, familiar comfort.',
    hero: 'Rocco’s brings house-made sauces, brick-oven pizzas, Italian favorites, imported meats and cheeses, and homemade desserts to Collegeville with a simple belief that better ingredients make a better meal.',
    servicesTitle: 'The kind of menu that solves dinner',
    services: [
      ['Brick-oven pizzas', 'A hot oven, a well-made crust, and balanced toppings create the crisp, satisfying center of the menu, ready for one person or the whole table.'],
      ['Italian favorites', 'Round out the order with sandwiches, entrées, salads, and comforting dishes built around fresh preparation and familiar flavors.'],
      ['House-made extras', 'Sauces, cheesecakes, and thoughtfully sourced meats and cheeses add the details that make a neighborhood pizzeria feel like its own place.'],
    ],
    missionTitle: 'Prepare it the old-fashioned way: fresh and simple',
    mission: 'Rocco’s Brick Oven Pizzeria centers its food on quality ingredients and straightforward preparation. The mission is to give Collegeville a dependable place for pizza and Italian comfort, where a casual pickup can still taste considered and a table can find more than one reason to stay.',
    feature: ['Let the oven do what the oven does best', 'Brick-oven pizza is about the relationship between heat, crust, sauce, cheese, and timing. When those elements stay balanced, even a simple pie has character.'],
    spotlight: ['From quick pickup to full family dinner', 'One pizza can answer a busy night. A larger order of pies, salads, entrées, and dessert can turn the same kitchen into a complete meal for the table.'],
    catalog: [['View the menu', 'Explore current pizzas, Italian dishes, sandwiches, salads, and desserts.'], ['Order from Collegeville', 'Use the official site or phone to confirm current ordering options.'], ['Plan a family meal', 'Mix pizzas and house favorites so everyone at the table has a choice.']],
  },
  'sangillo-tire': {
    tagline: 'Tire care from a family shop that knows the road.',
    hero: 'Sangillo Tire Center helps Delaware Valley drivers choose, maintain, and replace the tires connecting every mile of braking, turning, commuting, and weekend travel to the pavement.',
    servicesTitle: 'Start with how the vehicle is driven',
    services: [
      ['Tire selection and replacement', 'Compare tire options around vehicle fit, driving conditions, mileage expectations, ride, weather, and budget instead of treating every driver like the same customer.'],
      ['Tire inspection and care', 'Regular attention to pressure, tread, wear patterns, and rotation can help drivers spot concerns earlier and get more consistent performance from the set.'],
      ['Local service and advice', 'A family-owned tire shop can explain what it sees, answer questions directly, and help a customer decide what is urgent, what can wait, and what belongs in the maintenance plan.'],
    ],
    missionTitle: 'Serve the driver, not just the tire size',
    mission: 'Sangillo Tire Center describes more than sixty years of family-owned service in the Delaware Valley. The mission is to pair that local continuity with useful tire guidance, careful work, and the kind of relationship that brings a customer back before the next set is already worn out.',
    feature: ['Wear patterns tell a story', 'Uneven tread can point toward pressure, rotation, alignment, suspension, or driving-condition issues. Looking at the pattern helps the conversation move beyond simply installing another set.'],
    spotlight: ['The best option fits the vehicle and the routine', 'Highway commuting, local errands, seasonal weather, work use, and annual mileage all shape what a good tire choice looks like. Price is part of the decision, but it is not the entire decision.'],
    catalog: [['Tire brands', 'Compare current options that fit the vehicle, driving needs, and budget.'], ['Tire care', 'Ask about inspection, pressure, tread, rotation, and visible wear.'], ['Schedule service', 'Call the Folsom shop to discuss availability and the work the vehicle needs.']],
  },
  'specks-chicken': {
    tagline: 'Broasted chicken with Collegeville roots.',
    hero: 'Family-owned since 1953, Speck’s serves broasted chicken, sandwiches, daily specials, sides, garden salads, and its secret-recipe coleslaw for pickup, delivery, and the family table.',
    servicesTitle: 'Comfort food that knows exactly what it is',
    services: [
      ['Broasted chicken', 'Crisp outside, juicy inside, and built to travel, the signature chicken is the order people plan around and the reason many customers already know the name.'],
      ['Sandwiches, sides, and salads', 'Round out lunch or dinner with familiar supporting players, from hearty sandwiches and daily specials to garden salads and the house coleslaw.'],
      ['Family and party orders', 'Scale the same Collegeville comfort into an easy group meal, whether the food is headed home, to an event, or onto a table where nobody wants to cook.'],
    ],
    missionTitle: 'Keep a family tradition useful to today’s family',
    mission: 'Speck’s has lasted because the food fits real life: recognizable, satisfying, easy to pick up, and generous enough to share. The mission is to preserve the identity of a long-running drive-in while keeping ordering and group meals convenient for the way Collegeville eats now.',
    feature: ['The sides turn chicken into dinner', 'A full meal comes together when the main order has contrast: something crisp, something cool, something savory, and enough variety that every plate at the table feels complete.'],
    spotlight: ['Pickup, delivery, or a larger order', 'Customers can call for pickup and use the delivery links published by the restaurant. Party orders offer a practical route when the guest list is longer than the kitchen table.'],
    catalog: [['See the menu', 'Browse chicken, sandwiches, specials, sides, salads, and family options.'], ['Order for pickup', 'Call ahead and collect the meal from the Ridge Pike drive-in.'], ['Plan a party order', 'Match quantities and sides to the size and style of the gathering.']],
  },
  'trend-auto-trader': {
    tagline: 'A better used-car search starts with clear choices.',
    hero: 'Trend Auto Trader brings affordable pre-owned vehicles, online search, financing paths, and direct dealership support together for Quakertown drivers ready to compare the options.',
    servicesTitle: 'Move from browsing to a confident test drive',
    services: [
      ['Pre-owned vehicle inventory', 'Search across available cars by the factors that matter to you, then review the details that help a promising listing earn a closer look.'],
      ['Financing and pre-qualification', 'Explore a financing route before the visit so monthly budget, available terms, and the realistic vehicle range are easier to discuss at the dealership.'],
      ['Trade-in conversation', 'Bring the current vehicle into the plan and ask how its condition, mileage, history, and market fit may affect the next purchase.'],
    ],
    missionTitle: 'Make the buying path easier to understand',
    mission: 'Trend Auto Trader is positioned as a Quakertown source for quality used vehicles at accessible prices. The mission is to help shoppers narrow the inventory, understand the financing path, and arrive at the lot ready to evaluate a vehicle rather than restart the search from scratch.',
    feature: ['A listing is the beginning of the inspection', 'Photos, mileage, equipment, history, and price help identify candidates. The test drive and in-person review are where comfort, condition, visibility, controls, and the feel of the vehicle become clear.'],
    spotlight: ['Set the budget before falling for the car', 'Pre-qualification and a complete ownership budget can keep the search grounded. Payment, insurance, taxes, maintenance, and fuel all belong in the decision.'],
    catalog: [['Search inventory', 'Filter current pre-owned vehicles and identify the ones worth a closer look.'], ['Apply online', 'Begin a pre-qualification path before planning the dealership visit.'], ['Value a trade', 'Discuss how the current vehicle may fit into the next purchase.']],
  },
  'union-jacks': {
    tagline: 'Good food, a serious draft list, and no need to dress it up.',
    hero: 'Union Jack’s Olde Congo Hotel is a Barto bar for craft beer, cocktails, changing specials, and food made for meat eaters, vegetarians, vegans, friends, and whoever joins the table next.',
    servicesTitle: 'A neighborhood bar with range behind the taps and in the kitchen',
    services: [
      ['Craft beer and drafts', 'An ever-changing draft list rewards the regular who wants something new and the guest who simply wants a good pour with dinner.'],
      ['Cocktails and bar favorites', 'Settle in with a cocktail and food that understands the assignment: satisfying, social, and easy to enjoy without turning the evening into a production.'],
      ['Daily specials for every appetite', 'Changing specials and options for vegan, vegetarian, and meat-eating guests give mixed groups a reason to choose one table instead of three different plans.'],
    ],
    missionTitle: 'Be the friendly local bar Barto can call its own',
    mission: 'Union Jack’s Congo describes itself with humor, confidence, and affection for local ingredients, craft beer, and good food. The mission is to stay relaxed without becoming forgettable: a place where friends and families can eat well, discover the latest special, and feel welcome without performing for the room.',
    feature: ['The daily special keeps the regular visit interesting', 'A changing board gives the kitchen room to respond to ingredients, ideas, and the season. It also gives returning guests something to check before defaulting to the same order.'],
    spotlight: ['Follow the current specials where they are posted', 'The restaurant directs guests to its social channels for changing daily specials. Check the latest post or call before the drive if one particular dish is the reason for the visit.'],
    catalog: [['Food and specials', 'See what the kitchen is serving and what has changed today.'], ['Drafts and cocktails', 'Find a drink to pair with the table, the game, or the conversation.'], ['Plan a visit', 'Check current hours, directions, and contact details for the Barto location.']],
  },
  'weathers-motors': {
    tagline: 'Find the right pre-owned vehicle without losing the plot.',
    hero: 'Weathers Motors combines a broad pre-owned inventory with shopping tools, vehicle research, service scheduling, trade-in options, and direct help from its Media dealership.',
    servicesTitle: 'Support for the search, the purchase, and the miles after',
    services: [
      ['Shop pre-owned inventory', 'Browse by price, brand, body style, ownership history, fuel efficiency, and other priorities to turn a large inventory into a manageable shortlist.'],
      ['Trade or sell a vehicle', 'Start with an online value path, then bring the vehicle details and condition into a direct conversation about selling or using it toward the next purchase.'],
      ['Schedule vehicle service', 'Keep maintenance and repair connected to the dealership with an online scheduling path and resources for current owners.'],
    ],
    missionTitle: 'Give every shopper a clear next move',
    mission: 'Weathers Motors serves customers at different points in the ownership cycle: some are researching, some are comparing a short list, some are ready to trade, and others already need service. The mission is to make each path easy to find and useful enough to move the customer forward.',
    feature: ['Shop by the constraint that matters most', 'Price may lead the search, but body style, fuel use, mileage, features, ownership history, and everyday fit can matter just as much. Good filters help the buyer compare vehicles on the criteria that will still matter after the first month.'],
    spotlight: ['Hybrids and EVs change the research questions', 'Charging, range, driving routine, efficiency, incentives, and long-term ownership needs can alter the comparison. Education helps shoppers decide whether an electrified vehicle fits their real use.'],
    catalog: [['Browse inventory', 'Search current pre-owned vehicles by price, brand, body style, and other priorities.'], ['Trade or sell', 'Start a value conversation for the vehicle you currently own.'], ['Schedule service', 'Plan maintenance or repair with the dealership’s current service department.']],
  },
};
