export const period = "August 1–31, 2026";
export const observedAt = "August 31, 2026";
export const leadAccounting = "Platform activity is reported separately from qualified inquiries, appointments, estimates, bookings, and revenue. Conversion reporting remains pending validation wherever the exact action definition, attribution window, or downstream outcome is not fully reconciled.";

const benchmarkUrl = "https://www.wordstream.com/blog/2026-google-ads-benchmarks";

export const reports = [
  {
    id: "kimberly-james-bridal",
    client: "Kimberly James Bridal",
    descriptor: "Google Search, Meta lead generation, and appointment follow-up",
    logo: "kimberly-james-bridal.png",
    logoBackground: "light",
    accent: "#E6C85C",
    accentBright: "#F5D978",
    status: "Full-month Google delivery verified; Meta evidence covers two confirmed weekly windows",
    signal: "Google Search generated 138 clicks from 2,393 impressions on $504.49 in August spend. Two verified Meta reporting windows added 11 paid form leads, while the full-month Meta spend total remains pending validation.",
    goal: "Connect every paid inquiry to contact and appointment outcomes, then use appointment quality to guide September budget and creative decisions.",
    kpis: [
      ["Google spend", "$504.49", "Aug 1–31 · account 814-550-6229"],
      ["Google clicks", "138", "2,393 impressions"],
      ["Google CTR", "5.77%", "$3.66 average CPC"],
      ["Verified Meta leads", "11", "Two confirmed weekly windows"],
    ],
    benchmark: { percentage: "18% lower", detail: "August Google CPC than the 2026 Apparel / Fashion & Jewelry search benchmark of $4.44.", url: benchmarkUrl },
    work: [
      "Delivered weekly paid-media reports with Google and Meta kept as separate evidence lanes.",
      "Prepared private lead handoffs so contact details stayed out of shared client reporting.",
      "Maintained the Higher Intent Meta form and its qualification fields to improve inquiry quality.",
      "Mapped the inquiry-to-appointment follow-up path so September decisions can use boutique outcomes.",
    ],
    analysis: [
      "Google Search produced a stable full-month traffic signal at $3.66 per click. The cost is efficient for the category, while appointment quality remains the decision metric that matters most.",
      "The Meta evidence is useful but incomplete for the full month: Aug 3–9 recorded two leads at $34.40 per lead and Aug 17–23 recorded nine leads at $7.72 per lead. Those windows are not represented as a complete monthly total.",
    ],
    platforms: [
      {
        name: "Google Ads",
        state: "Verified · Aug 1–31",
        note: "The Philadelphia Search campaign spent $504.49 for 138 clicks from 2,393 impressions, producing a 5.77% click-through rate and $3.66 average cost per click. Conversion reporting is pending validation.",
        metrics: [["Spend", "$504.49"], ["Clicks", "138"], ["Impressions", "2,393"], ["CTR", "5.77%"]],
        rows: [["Local Bridal · Philadelphia", "Active", "$504.49", "138 clicks", "$3.66 CPC"]],
      },
      {
        name: "Meta Ads",
        state: "Partial monthly evidence",
        note: "Two verified weekly reads recorded 11 paid form leads on $138.28 in spend. Direct full-month Meta access was unavailable, so this is a coverage floor rather than a monthly total.",
        metrics: [["Verified spend", "$138.28"], ["Verified leads", "11"], ["Windows", "2"], ["Full month", "Pending"]],
        rows: [["Aug 3–9", "Verified", "$68.80", "2 leads", "$34.40 CPL"], ["Aug 17–23", "Verified", "$69.48", "9 leads", "$7.72 CPL"]],
      },
    ],
    outcome: {
      platform: "Google delivered 138 clicks on $504.49 in full-month spend. Two verified Meta windows delivered 11 paid form leads.",
      business: "Contact, consultation, and booked-appointment outcomes are not yet reconciled to the monthly platform activity.",
      measurement: "Match each inquiry to contact and appointment status, then evaluate budget and form quality from booked-consultation evidence.",
    },
    workstreams: [["Reporting", "Two weekly performance packets and private lead updates", "Delivered"], ["Lead quality", "Higher Intent form and qualification fields", "Active"], ["Search", "Philadelphia campaign monthly read", "Verified"], ["Appointments", "Inquiry-to-consultation reconciliation", "Next"]],
    detailedWork: [["Reports", "Delivered separate Google and Meta performance reads.", "Keeps channel evidence clear and prevents blended claims.", "Delivered"], ["Leads", "Prepared private Meta lead handoffs for client follow-up.", "Protects contact information while accelerating outreach.", "Delivered"], ["Form", "Maintained Higher Intent qualification fields.", "Supports stronger inquiry screening before appointments.", "Active"], ["Measurement", "Preserved the appointment outcome path.", "Moves decisions from traffic toward consultations.", "Next"]],
    wins: ["Google CPC finished below the current category benchmark.", "The later verified Meta window produced nine leads at $7.72 per lead."],
    augustFocus: ["Reconcile the 11 verified Meta leads and Google inquiries to consultation status.", "Review search terms, location quality, and creative only after appointment outcomes are visible."],
    nextMoves: [["Reconcile", "Kim + Momentum", "Record contact and appointment status for each current inquiry.", "Early September"], ["Review", "Paid media", "Check search-term and location quality from the full-month Google window.", "Weekly"], ["Decide", "Kim + Momentum", "Adjust budget or form settings only from appointment-quality evidence.", "After follow-up"]],
    sources: ["Google Ads account 814-550-6229 · Aug 1–31 live read · Aug 31", "Weekly report source data · Aug 3–9 and Aug 17–23", "August session-history evidence index", "WordStream / LocaliQ 2026 Search Advertising Benchmarks"],
  },
  {
    id: "replenish-7-eleven",
    client: "Replenish / 7-Eleven",
    descriptor: "Nine-store Google Ads program and location reporting",
    logo: "replenish-7-eleven.png",
    logoBackground: "light",
    accent: "#EF3C2F",
    accentBright: "#FF8A79",
    status: "Full-month Google delivery verified; click-to-directions remains a separate site reporting KPI",
    signal: "The Replenish account generated 705 clicks from 38,690 impressions on $684.74 in August spend. Average cost per click was $0.97 across the store program.",
    goal: "Give Mia one clear Replenish-only monthly view, preserve location-level detail, and add the site-based click-to-directions KPI before final client presentation.",
    kpis: [["Google spend", "$684.74", "Aug 1–31 · account 627-501-4654"], ["Google clicks", "705", "38,690 impressions"], ["Average CPC", "$0.97", "1.82% account CTR"], ["Store campaigns", "9", "Requested reporting scope"]],
    benchmark: { percentage: "53% lower", detail: "August Google CPC than the 2026 Restaurants & Food search benchmark of $2.05.", url: benchmarkUrl },
    work: [
      "Kept Replenish and 7-Eleven reporting completely separate from Fresh Blends.",
      "Delivered two weekly reporting packets and maintained the location-level campaign structure.",
      "Reconciled billing, account access, and campaign-readiness follow-ups during the month.",
      "Prepared the monthly top-line KPI handoff and reserved click-to-directions for the existing site reporting layer.",
    ],
    analysis: [
      "Replenish delivered the largest click volume in the current Google portfolio at less than one dollar per click. The strongest campaign-level click-through rates were Carmel Mountain at 2.81% and Torrey Del Mar at 2.37%.",
      "The client view remains intentionally brand-specific. Fresh Blends is not running in this report, and the monthly presentation should contain one Replenish PowerPoint only.",
    ],
    platforms: [
      {
        name: "Google Ads",
        state: "Verified · Aug 1–31",
        note: "Nine store campaigns generated 705 clicks from 38,690 impressions on $684.74 in spend. The account averaged $0.97 per click.",
        metrics: [["Spend", "$684.74"], ["Clicks", "705"], ["Impressions", "38,690"], ["Avg. CPC", "$0.97"]],
        rows: [["Torrey Del Mar", "Active", "$127.25", "176 clicks", "2.37% CTR"], ["Carmel Mountain", "Active", "$110.78", "99 clicks", "2.81% CTR"], ["Coral Springs", "Active", "$85.72", "26 clicks", "0.46% CTR"], ["Boca", "Active", "$82.68", "51 clicks", "1.40% CTR"], ["Pompano", "Active", "$67.80", "95 clicks", "2.11% CTR"]],
      },
      {
        name: "Reporting and attribution",
        state: "Monthly handoff in progress",
        note: "The top-line campaign KPIs are complete. Click-to-directions remains a separate site-based KPI because it is embedded in the existing reporting path.",
        metrics: [["Top-line KPIs", "Complete"], ["Directions KPI", "Pending"], ["Decks", "1"], ["Fresh Blends", "Excluded"]],
        rows: [["Replenish PDF", "Built", "Monthly", "Google KPIs", "Client-ready"], ["Replenish PowerPoint", "Built", "One deck", "Location view", "Client-ready"], ["Click-to-directions", "Owner handoff", "—", "Site reporting", "Pending"]],
      },
    ],
    outcome: { platform: "Google delivered 705 clicks at a $0.97 average CPC across the August store program.", business: "Store visits, direction clicks, and downstream sales are not represented as Google conversions in this report.", measurement: "Add the site-based click-to-directions read separately, then use location-level traffic and visit signals to prioritize the next campaign review." },
    workstreams: [["Paid media", "Nine-store monthly Google read", "Verified"], ["Reporting", "Two weekly packets plus monthly PDF", "Delivered"], ["Presentation", "One Replenish-only PowerPoint", "Built"], ["Directions", "Site-based click-to-directions KPI", "Pending owner"]],
    detailedWork: [["Boundary", "Kept Replenish separate from Fresh Blends.", "Protects brand, spend, and KPI accuracy.", "Verified"], ["Access", "Followed billing and campaign-access items.", "Restored a reliable monthly reporting route.", "Advanced"], ["Reporting", "Completed location-level top-line KPI reporting.", "Makes store performance reviewable in one view.", "Complete"], ["Directions", "Reserved the site-based KPI for Dillon.", "Preserves the embedded measurement logic.", "Pending"]],
    wins: ["August average CPC was materially below the current restaurant category benchmark.", "Torrey Del Mar and Carmel Mountain led campaign-level engagement."],
    augustFocus: ["Add click-to-directions from the site reporting layer.", "Review lower-engagement locations before adjusting spend distribution."],
    nextMoves: [["Complete", "Dillon", "Add the August click-to-directions KPI from the site reporting source.", "Before client presentation"], ["Review", "Ruben + Momentum", "Own the top-line campaign KPI read by location.", "Early September"], ["Optimize", "Paid media", "Prioritize creative and targeting review for lower-engagement stores.", "After KPI review"]],
    sources: ["Google Ads account 627-501-4654 · Aug 1–31 live read · Aug 31", "Replenish weekly report source data · Aug 3–9 and Aug 17–23", "August session-history evidence index", "WordStream / LocaliQ 2026 Search Advertising Benchmarks"],
  },
  {
    id: "omega-landscaping",
    client: "Omega Landscaping and Concrete",
    descriptor: "High-intent Search, estimate destination, and local project proof",
    logo: "omega-landscaping.png",
    logoBackground: "dark",
    accent: "#2D7BC1",
    accentBright: "#8CB7FF",
    status: "Full-month Google delivery verified; estimate quality remains the next decision layer",
    signal: "Omega generated 174 clicks from approximately 3,730 impressions on $1,318.69 in August spend. Google reported three conversion events, with qualified project status still pending validation.",
    goal: "Reconcile calls and forms to named estimate opportunities, then optimize service and location coverage from qualified project value.",
    kpis: [["Google spend", "$1,318.69", "Aug 1–31 · account 285-398-1364"], ["Google clicks", "174", "Approximately 3,730 impressions"], ["Average CPC", "$7.58", "Approximately 4.67% CTR"], ["Google events", "3", "Qualification pending"]],
    benchmark: { percentage: "9% lower", detail: "August Google CPC than the 2026 Home & Home Improvement search benchmark of $8.33.", url: benchmarkUrl },
    work: [
      "Published the dedicated estimate destination and preserved campaign attribution into the quote path.",
      "Moved the account toward higher-intent Colorado Springs homeowner and project searches.",
      "Delivered weekly performance reports with platform events separated from qualified project outcomes.",
      "Produced the current Google Business Profile project-proof content batch for the local visibility program.",
    ],
    analysis: [
      "The high-intent Search campaign carried nearly all August spend and clicks. Average cost per click remained slightly more efficient than the current home-improvement benchmark.",
      "The next gain is not more activity alone. It is matching calls and forms to named projects so service themes, landing-page refinements, and budget can follow actual estimate quality.",
    ],
    platforms: [
      { name: "Google Ads", state: "Verified · Aug 1–31", note: "The account spent $1,318.69 for 174 clicks and approximately 3,730 impressions. Google reported three conversion events; conversion quality remains pending validation.", metrics: [["Spend", "$1,318.69"], ["Clicks", "174"], ["Avg. CPC", "$7.58"], ["Events", "3"]], rows: [["High Intent · Colorado Springs", "Paused at read", "$1,274.17", "173 clicks", "4.71% CTR"], ["Services · Call Only", "Paused", "$44.52", "1 click", "1.85% CTR"], ["Concrete · Call Only", "Active", "$0.00", "No delivery", "Monitor"]] },
      { name: "Website and local visibility", state: "Published and produced", note: "The dedicated estimate page remained the paid-search destination. A local project-proof content batch was produced for the Aug 17 through Sep 6 publishing rhythm.", metrics: [["Estimate page", "Live"], ["Content batch", "Produced"], ["Market", "Colorado Springs"], ["Lead join", "Pending"]], rows: [["Estimate destination", "Published", "—", "Form route", "Attribution preserved"], ["GBP project proof", "Produced", "—", "Multi-week batch", "Publishing evidence mixed"]] },
    ],
    outcome: { platform: "Google delivered 174 clicks on $1,318.69 and reported three conversion events.", business: "Named inquiries, qualified estimates, booked work, and revenue are not yet reconciled to those events.", measurement: "Match calls and forms to project status before changing budget, campaign mix, or landing-page emphasis." },
    workstreams: [["Search", "High-intent Colorado Springs campaign", "Verified"], ["Landing page", "Dedicated estimate destination", "Published"], ["Local visibility", "Project-proof content batch", "Produced"], ["Lead quality", "Named estimate reconciliation", "Next"]],
    detailedWork: [["Page", "Published the dedicated estimate destination.", "Gives paid traffic a focused quote path.", "Published"], ["Search", "Concentrated delivery around higher-intent service searches.", "Improves alignment with project demand.", "Active in month"], ["Content", "Produced the current local project-proof batch.", "Supports service and location relevance.", "Produced"], ["Quality", "Separated platform events from qualified projects.", "Prevents budget decisions from weak proxy signals.", "Pending"]],
    wins: ["Average CPC finished below the current home-improvement benchmark.", "The estimate destination and local project-proof system are both in place."],
    augustFocus: ["Reconcile current calls and forms to named project opportunities.", "Review search terms and landing-page content by qualified service type."],
    nextMoves: [["Reconcile", "Omega + Momentum", "Match August calls and forms to estimate status.", "Early September"], ["Review", "Paid media", "Prioritize high-intent terms by service and location quality.", "Weekly"], ["Publish", "Content", "Continue the approved local project-proof rhythm.", "Scheduled"]],
    sources: ["Google Ads account 285-398-1364 · Aug 1–31 live read · Aug 31", "Omega weekly report source data · Aug 3–9 and Aug 17–23", "Canonical estimate-page release and GBP batch", "WordStream / LocaliQ 2026 Search Advertising Benchmarks"],
  },
  {
    id: "onsite-concrete-landscape",
    client: "Onsite Concrete & Landscape",
    descriptor: "Google Ads recovery, Fairfield service pages, and estimate quality",
    logo: "onsite-concrete-landscape.png",
    logoBackground: "dark",
    accent: "#F15A4F",
    accentBright: "#FF8B7F",
    status: "August delivery recovered, but the controlled replacement and conversion cleanup remain open",
    signal: "Onsite generated 538 clicks on $88.07 in August spend at a $0.16 average cost per click. Google reported four conversion events, while exact estimate quality and the account's conversion setup remain pending validation.",
    goal: "Finish the controlled Search replacement, validate connected calls and accepted forms, and use qualified estimate quality to guide September delivery.",
    kpis: [["Google spend", "$88.07", "Aug 1–31 · account 103-371-5894"], ["Google clicks", "538", "Approximately 13,400 impressions"], ["Average CPC", "$0.16", "Spending campaign · 4.03% CTR"], ["Google events", "4", "Qualification pending"]],
    benchmark: { percentage: "98% lower", detail: "August blended CPC than the 2026 Home & Home Improvement search benchmark; directional only because Onsite's placement mix differs from pure Search.", url: benchmarkUrl },
    work: [
      "Reconfigured the account after delivery stopped and restored delivery following Google's review.",
      "Completed a call-volume recovery audit and defined a controlled Search replacement around qualified estimates.",
      "Published two Fairfield service pages with focused FAQs and maintained the dedicated paid-search destination.",
      "Kept duplicate call, form, and micro-action events separate from real estimate outcomes.",
    ],
    analysis: [
      "The account produced very inexpensive traffic, but the blended CPC is not directly comparable to a pure Search benchmark because the placement mix differs. Traffic efficiency is therefore a directional strength, not proof of qualified lead efficiency.",
      "The material September decision is measurement quality. Connected service-fit calls and accepted forms must become the primary evidence before the controlled Search replacement is treated as complete.",
    ],
    platforms: [
      { name: "Google Ads", state: "Verified · Aug 1–31", note: "The spending campaign generated 538 clicks on $88.07 at a 4.03% click-through rate. Google reported four conversion events, while conversion actions and enhanced measurement remain pending validation.", metrics: [["Spend", "$88.07"], ["Clicks", "538"], ["Avg. CPC", "$0.16"], ["Events", "4"]], rows: [["Onsite Concrete & Landscape", "Paused at read", "$88.07", "538 clicks", "4.03% CTR"], ["High Intent · Solano County", "Eligible", "$0.00", "No delivery", "Controlled lane"]] },
      { name: "Website and local search", state: "Published", note: "The dedicated paid-search page remained live, and two Fairfield service pages were confirmed published with focused FAQs.", metrics: [["Paid page", "Live"], ["Fairfield pages", "2"], ["FAQs", "Published"], ["Indexing", "Monitor"]], rows: [["Stamped Concrete · Fairfield", "Live", "—", "Service page", "FAQ included"], ["Concrete Repair · Fairfield", "Live", "—", "Service page", "FAQ included"]] },
    ],
    outcome: { platform: "Google delivered 538 clicks on $88.07 and reported four conversion events.", business: "Qualified estimates, booked projects, and revenue are not reconciled to the platform events.", measurement: "Validate connected calls and accepted form receipts, then complete the controlled Search transition without using micro-actions as lead proof." },
    workstreams: [["Recovery", "Campaign reconfiguration and delivery restoration", "Completed"], ["Search", "Controlled replacement plan", "Open"], ["Local pages", "Two Fairfield service pages", "Published"], ["Measurement", "Connected call and accepted-form validation", "Pending"]],
    detailedWork: [["Recovery", "Restored delivery after the account review period.", "Returned the account to measurable activity.", "Completed"], ["Audit", "Completed the call-volume recovery plan.", "Defines a path toward qualified estimates.", "Completed"], ["Pages", "Published two Fairfield service pages with FAQs.", "Expands local service relevance.", "Published"], ["Measurement", "Separated micro-actions from estimate outcomes.", "Protects lead and budget decisions.", "Pending"]],
    wins: ["Delivery returned after the early-August interruption.", "Two Fairfield service destinations are live."],
    augustFocus: ["Validate connected-call and accepted-form evidence.", "Finish the controlled Search transition and monitor the Fairfield pages."],
    nextMoves: [["Validate", "Onsite + Momentum", "Match August phone and form activity to estimate quality.", "Early September"], ["Complete", "Paid media", "Finish the controlled Search transition after live review.", "After validation"], ["Monitor", "SEO", "Check indexing and engagement on the Fairfield pages.", "Weekly"]],
    sources: ["Google Ads account 103-371-5894 · Aug 1–31 live read · Aug 31", "Onsite call-volume recovery audit · Aug 12", "Onsite weekly report source data · Aug 3–9 and Aug 17–23", "WordStream / LocaliQ 2026 Search Advertising Benchmarks"],
  },
  {
    id: "nexla",
    client: "Nexla",
    descriptor: "Google Ads account audit, campaign architecture, and conversion readiness",
    logo: "nexla.svg",
    logoBackground: "light",
    accent: "#6254FF",
    accentBright: "#A69EFF",
    status: "Full-month delivery verified; conversion quality and campaign consolidation remain the primary opportunity",
    signal: "Nexla generated 210 clicks from approximately 6,310 impressions on $742.72 in August spend. Average cost per click was $3.54, and Brand Exact produced a 21.06% click-through rate.",
    goal: "Protect Brand performance, consolidate fragmented nonbrand activity, and validate the primary lead signal before scaling budget.",
    kpis: [["Google spend", "$742.72", "Aug 1–31 · account 791-780-2207"], ["Google clicks", "210", "Approximately 6,310 impressions"], ["Average CPC", "$3.54", "Approximately 3.33% account CTR"], ["Brand Exact CTR", "21.06%", "119 clicks · $355.17 spend"]],
    benchmark: { percentage: "40% lower", detail: "August account CPC than the 2026 Business Services search benchmark of $5.87.", url: benchmarkUrl },
    work: [
      "Completed and delivered the lifetime Google Ads audit with a clear account diagnosis and improvement plan.",
      "Prepared a protected Brand and tightly controlled Nonbrand campaign architecture for the next phase.",
      "Completed a paid-search readiness packet covering landing-page selection, primary conversion definition, and release gates.",
      "Reviewed the embedded lead-form path and current spam-handling needs so reporting can distinguish valid inquiries.",
    ],
    analysis: [
      "Brand Exact remains Nexla's clearest demand signal, producing 119 August clicks at a 21.06% click-through rate. The blended account cost per click was materially below the current Business Services benchmark.",
      "Nonbrand engagement remains uneven across MCP, data integration, and data-product themes. The next step is controlled consolidation with a trustworthy primary conversion rather than broader expansion.",
    ],
    platforms: [
      { name: "Google Ads", state: "Verified · Aug 1–31", note: "Five spending campaigns generated 210 clicks on $742.72. Brand Exact led engagement, while the nonbrand campaigns delivered lower click-through rates and need tighter message-to-landing alignment.", metrics: [["Spend", "$742.72"], ["Clicks", "210"], ["Avg. CPC", "$3.54"], ["Brand CTR", "21.06%"]], rows: [["Brand Exact", "Active", "$355.17", "119 clicks", "21.06% CTR"], ["MCP · Search", "Active", "$280.86", "59 clicks", "1.79% CTR"], ["MCP · Performance Max", "Active", "$47.26", "27 clicks", "2.14% CTR"], ["ETL Pipeline", "Active", "$39.59", "4 clicks", "0.44% CTR"], ["Data Products", "Active", "$19.84", "1 click", "0.88% CTR"]] },
      { name: "Readiness and measurement", state: "Delivered · release gates open", note: "The audit and readiness packet define the Brand and Nonbrand structure, landing-page decisions, and conversion validation needed before expansion.", metrics: [["Audit", "Delivered"], ["Readiness", "Complete"], ["Primary conversion", "Pending"], ["Spam review", "Completed"]], rows: [["Account audit", "Delivered", "Lifetime review", "Client-final PDF", "Aug 20"], ["Campaign architecture", "Prepared", "Brand + Nonbrand", "Controlled proof", "Review"], ["Lead-form quality", "Reviewed", "—", "Spam handling", "Validate"]] },
    ],
    outcome: { platform: "Google delivered 210 clicks on $742.72, led by Brand Exact at a 21.06% click-through rate.", business: "Qualified sales conversations, opportunities, and revenue are not reconciled to August platform activity.", measurement: "Confirm the primary conversion and valid lead criteria, then evaluate Brand and Nonbrand performance against qualified pipeline." },
    workstreams: [["Audit", "Lifetime account review and recommendation plan", "Delivered"], ["Architecture", "Protected Brand plus controlled Nonbrand", "Prepared"], ["Measurement", "Primary conversion and valid-lead definition", "Pending"], ["Lead quality", "Embedded form and spam review", "Completed"]],
    detailedWork: [["Audit", "Delivered the client-final Google Ads audit.", "Creates a defensible baseline and improvement plan.", "Delivered"], ["Plan", "Prepared the next Brand and Nonbrand structure.", "Protects strong intent while controlling tests.", "Prepared"], ["Readiness", "Defined landing-page and release decisions.", "Prevents scale before measurement is reliable.", "Complete"], ["Quality", "Reviewed the lead-form and spam path.", "Supports cleaner pipeline reporting.", "Review complete"]],
    wins: ["Account CPC finished materially below the current Business Services benchmark.", "Brand Exact remained the strongest engagement signal at 21.06% CTR."],
    augustFocus: ["Confirm the primary conversion and valid-lead definition.", "Consolidate nonbrand activity around the strongest high-intent themes."],
    nextMoves: [["Confirm", "Nexla + Momentum", "Approve the primary conversion and valid-lead criteria.", "Early September"], ["Consolidate", "Paid media", "Protect Brand and tighten the Nonbrand proof period.", "After confirmation"], ["Reconcile", "Marketing + sales", "Match campaign activity to qualified conversations and pipeline.", "Monthly"]],
    sources: ["Google Ads account 791-780-2207 · Aug 1–31 live read · Aug 31", "Nexla client-final Google Ads audit · Aug 20", "Nexla paid-search readiness packet · Aug 25", "WordStream / LocaliQ 2026 Search Advertising Benchmarks"],
  },
  {
    id: "puttery",
    client: "Puttery NYC",
    descriptor: "Reservation attribution pilot and Tock measurement readiness",
    logo: "puttery.svg",
    logoBackground: "dark",
    accent: "#F8C341",
    accentBright: "#FFE188",
    status: "Attribution pilot foundation delivered; live paid-media spend and booking attribution are not yet connected",
    signal: "August produced the live Puttery NYC attribution dashboard, two client-ready pilot PDFs, the kickoff and access packet, and the Tock reservation-data implementation specification. No verified Puttery ad-spend source is currently mapped.",
    goal: "Secure the exact Puttery NYC platform access and Tock event route, then validate booking attribution before any live campaign feedback or spend claim.",
    kpis: [["Live dashboard", "1", "Puttery-branded pilot"], ["Discovery questions", "64", "Seven-system review"], ["Pilot blockers", "43", "Evidence tracked"], ["Verified ad spend", "Pending", "No mapped account source"]],
    work: [
      "Published the Puttery-branded attribution pilot dashboard with the seven-system measurement map.",
      "Delivered the Attribution Pilot Brief and Discovery Blocker Worksheet with the exact official logo.",
      "Completed the kickoff analysis, day-zero access packet, execution plan, and two-and-a-half-week build monitor.",
      "Prepared the Tock reservation-event intake specification and the acceptance criteria for the NYC pilot.",
    ],
    analysis: [
      "Puttery entered August as an attribution and measurement build, not a verified paid-media reporting account. The delivered dashboard and discovery package make the remaining access and data decisions explicit.",
      "The local booking-event intake path is ready for controlled validation, but production activation still depends on exact Tock, analytics, ad-account, consent, venue-isolation, and hosting decisions.",
    ],
    platforms: [
      { name: "Attribution pilot", state: "Live · demonstration mode", note: "The dashboard covers the website layer, Tock, Toast, Tripleseat, analytics, Google Ads, and Meta, with 64 discovery questions and 43 identified blockers. Demonstration data is not presented as live performance.", metrics: [["Dashboard", "Live"], ["Systems", "7"], ["Questions", "64"], ["Blockers", "43"]], rows: [["Pilot dashboard", "Live", "—", "Noindex", "Demonstration only"], ["Pilot brief", "Delivered", "—", "PDF", "Client-ready"], ["Blocker worksheet", "Delivered", "—", "PDF", "Discovery-ready"]] },
      { name: "Booking attribution readiness", state: "Prepared · production pending", note: "The NYC booking-event specification and acceptance criteria are prepared. Production use waits on exact account binding, permissions, consent, location isolation, and hosting ownership.", metrics: [["Tock spec", "Prepared"], ["Acceptance", "Defined"], ["Production", "Pending"], ["Ad spend", "Unavailable"]], rows: [["Reservation event intake", "Prepared", "—", "Local validation", "Production pending"], ["Access request", "Prepared", "—", "Owner handoff", "Approval needed"], ["NYC isolation", "Specified", "—", "Venue scope", "Confirm"]] },
    ],
    outcome: { platform: "No verified Puttery Google Ads or Meta spend source is mapped for August, so no media-performance total is claimed.", business: "The dashboard, discovery materials, kickoff package, and reservation-attribution foundation were delivered during August.", measurement: "Connect exact Tock and analytics evidence, validate two venue-days, and confirm the primary booking outcome before activating production reporting." },
    workstreams: [["Dashboard", "Puttery-branded attribution pilot", "Live"], ["Discovery", "Pilot brief and blocker worksheet", "Delivered"], ["Kickoff", "Access packet and execution plan", "Complete"], ["Bookings", "Tock event and venue-isolation specification", "Prepared"]],
    detailedWork: [["Dashboard", "Published the branded attribution pilot.", "Creates one shared view of the measurement system.", "Live"], ["Discovery", "Delivered two client-ready pilot PDFs.", "Turns blockers into owned decisions.", "Delivered"], ["Kickoff", "Completed access and execution materials.", "Sets the production sequence and responsibilities.", "Complete"], ["Bookings", "Prepared the reservation-event specification.", "Makes booking attribution testable once access is approved.", "Prepared"]],
    wins: ["The pilot dashboard and client discovery package are complete.", "The booking-attribution path now has explicit acceptance criteria and ownership gates."],
    augustFocus: ["Secure exact Tock, analytics, and ad-account access for Puttery NYC.", "Validate booking events and two venue-days before production activation."],
    nextMoves: [["Confirm", "Puttery + Momentum", "Approve exact platform owners, access, consent, and NYC isolation.", "Kickoff follow-up"], ["Validate", "Measurement", "Reconcile two venue-days against Tock booking evidence.", "After access"], ["Activate", "Momentum", "Move from demonstration to production reporting only after the validation gate passes.", "Gate dependent"]],
    sources: ["Live Puttery NYC Attribution Pilot Dashboard", "Puttery Attribution Pilot Brief and Discovery Blocker Worksheet · Aug 5", "Puttery kickoff, access, and execution materials · Aug 27", "Puttery Tock attribution specification and readiness review · Aug 28"],
  },
  {
    id: "fagan-painting",
    client: "Fagan Painting",
    descriptor: "Organic search growth, service-page depth, and site-health readiness",
    logo: "fagan-painting.png",
    logoBackground: "light",
    accent: "#F6B53D",
    accentBright: "#FFD47A",
    status: "Organic growth advanced; paid media remained off; the latest site repair packet awaits publication",
    signal: "Two service-area pages were confirmed published earlier in August. A later weekly update reported one blog and four service pages, while the August 27 baseline documented 512 ranking keywords, 39 top-ten terms, and a prioritized site-health packet.",
    goal: "Publish the approved site fixes, strengthen the highest-intent service pages, and connect organic inquiries to estimate and booked-project outcomes.",
    kpis: [["Ranking keywords", "512", "Latest August organic snapshot"], ["Top-ten terms", "39", "Current ranking coverage"], ["New blog", "1", "Reported Aug 17–23"], ["Paid media", "Off", "No August delivery claimed"]],
    work: [
      "Confirmed the North Hills and Highland Park service-area pages as published.",
      "Advanced the site with one new blog, four reported service-page additions, clearer navigation, and a stronger call path.",
      "Completed the August 27 search baseline and a ten-query monitoring set for the next measurement cycle.",
      "Prepared the FAQ repair, location spelling correction, search markup specification, and crawl-access recommendations for publication.",
    ],
    analysis: [
      "Fagan's August evidence is organic-first. Ranking breadth is established, and the next value comes from publishing the prepared site fixes and strengthening the service pages that already show demand.",
      "Paid media remained off, so no August ad-spend or paid-lead claim is made. One website estimate notification was visible in the month, but attribution and booked-project outcomes remain separate.",
    ],
    platforms: [
      { name: "Organic search", state: "Active · August baseline", note: "The latest organic snapshot recorded 512 ranking keywords and 39 top-ten terms. The Aug 21–25 Search Console window produced 4,306 impressions and established the next monitoring baseline.", metrics: [["Keywords", "512"], ["Top 10", "39"], ["Impressions", "4,306"], ["Query set", "10"]], rows: [["Homepage", "Indexed", "—", "Google fetch confirmed", "Entity repair prepared"], ["North Hills", "Live", "—", "Service-area page", "Published"], ["Highland Park", "Live", "—", "Service-area page", "Published"]] },
      { name: "Website and content", state: "Produced · publication mixed", note: "The later weekly update reported one blog and four service pages. A publication packet now covers the FAQ copy, location spelling, crawl access, and contractor markup repairs.", metrics: [["New blog", "1"], ["Service pages", "4"], ["Repair packet", "Ready"], ["Paid media", "Off"]], rows: [["Service and FAQ structure", "Advanced", "—", "Page system", "In progress"], ["Site repair packet", "Prepared", "—", "Owner handoff", "Publish next"], ["Paid-media lane", "Closed", "$0 claimed", "No delivery", "Organic focus"]] },
    ],
    outcome: { platform: "No August paid-media delivery is claimed. The verified activity is organic visibility, page production, and the prepared site-health packet.", business: "One website estimate notification was visible in August; contact, estimate, booked-project, and revenue outcomes are not attributed here.", measurement: "Publish the prepared fixes, then track ranking movement, page engagement, form inquiries, and booked-estimate quality." },
    workstreams: [["Organic search", "Ranking baseline and monitoring set", "Verified"], ["Content", "Service pages and one blog", "Advanced"], ["Site health", "FAQ, location, crawl, and markup packet", "Prepared"], ["Paid media", "Historical lane", "Off"]],
    detailedWork: [["Pages", "Published two service-area pages and advanced four reported service pages.", "Expands local and service-intent coverage.", "Mixed"], ["Content", "Added one reported blog and improved navigation and call paths.", "Connects search visibility to inquiry action.", "Advanced"], ["Baseline", "Completed the ranking, query, and site-health read.", "Creates an honest before-and-after measurement point.", "Verified"], ["Repairs", "Prepared the FAQ, spelling, crawl, and markup publication packet.", "Removes defects that weaken search clarity.", "Prepared"]],
    wins: ["The latest snapshot recorded 512 ranking keywords and 39 top-ten terms.", "The site now has a concrete repair and measurement packet ready for publication."],
    augustFocus: ["Publish and verify the prepared site fixes.", "Prioritize service pages by inquiry and estimate quality."],
    nextMoves: [["Publish", "Fagan site owner", "Apply the approved FAQ, spelling, crawl, and markup repairs.", "Early September"], ["Verify", "Momentum", "Recheck the live pages and ten-query monitoring set.", "After publication"], ["Reconcile", "Fagan + Momentum", "Match organic inquiries to estimates and booked projects.", "Monthly"]],
    sources: ["Fagan weekly source data · Aug 3–9 and Aug 17–23", "Fagan organic-search baseline · Aug 27", "Fagan site repair and publication packet · Aug 27", "Slack #fagan-painting · Aug 24–30"],
  },
  {
    id: "nkcdc",
    client: "NKCDC",
    descriptor: "Phase Two growth plan, stakeholder follow-up, and pilot selection",
    logo: "nkcdc.png",
    logoBackground: "light",
    accent: "#E56D4C",
    accentBright: "#FFAB89",
    status: "The Phase Two package is complete and review-ready; production remains paused pending a client decision",
    signal: "The twelve-page Phase Two growth package remained the August source of truth. A direct stakeholder follow-up was sent, while implementation and budget decisions stayed paused until the first pilot, owner, and success measure are approved.",
    goal: "Choose one realistic first pilot, assign its owner and success measure, and convert the approved priority into a dated production sequence.",
    kpis: [["Growth package", "12 pages", "Current source of truth"], ["Growth options", "7", "Presented for selection"], ["Stakeholder follow-up", "1", "Sent August 4"], ["Production state", "Paused", "Decision pending"]],
    work: ["Kept the Phase Two growth package as the governing August plan.", "Sent a direct stakeholder follow-up on August 4 to move the review toward a decision.", "Preserved the seven proposed growth lanes without presenting any of them as approved production.", "Held publishing, paid media, and budget work behind a clear client decision and measurement owner."],
    analysis: ["August was a decision month rather than a production month. The strategic package is complete, but the next value depends on selecting a bounded first pilot instead of opening several lanes at once.", "No paid-media delivery or implementation result is claimed while the account remains paused."],
    platforms: [
      { name: "Phase Two growth package", state: "Review-ready", note: "The twelve-page package coordinates seven growth options and remains the active client planning asset.", metrics: [["Pages", "12"], ["Options", "7"], ["Follow-up", "Sent"], ["Decision", "Open"]], rows: [["Growth package", "Ready", "—", "12 pages", "Client review"], ["First pilot", "Pending", "—", "Not selected", "Decision needed"]] },
      { name: "Activation and measurement", state: "Paused · not activated", note: "No channel is represented as live production. The pilot owner, scope, budget, and success definition remain open.", metrics: [["Production", "Paused"], ["Paid media", "Not active"], ["Owner", "Pending"], ["Measurement", "Pending"]], rows: [["Publishing", "Held", "—", "No new release", "Approval first"], ["Measurement contract", "Proposed", "—", "Owner needed", "Before launch"]] },
    ],
    outcome: { platform: "No new paid-media or production delivery is claimed for August.", business: "The Phase Two plan and follow-up are complete; the first approved pilot and its owner remain open.", measurement: "Select the first pilot and define its success measure before implementation begins." },
    workstreams: [["Strategy", "Twelve-page Phase Two package", "Ready"], ["Follow-up", "Stakeholder check-in", "Sent"], ["Pilot", "First approved scope", "Open"], ["Measurement", "Owner and success definition", "Pending"]],
    detailedWork: [["Plan", "Maintained the Phase Two package as the current source of truth.", "Keeps the next decision tied to one approved plan.", "Ready"], ["Follow-up", "Sent the August 4 stakeholder check-in.", "Returns the decision to the client group.", "Sent"], ["Boundaries", "Kept all proposed lanes separate from approved production.", "Prevents work and budget from outrunning authorization.", "Verified"], ["Measurement", "Held the pilot owner and success definition as open decisions.", "Makes the first release measurable.", "Pending"]],
    wins: ["The Phase Two package remains complete and review-ready.", "The proposed lanes stayed clearly separated from approved work."],
    augustFocus: ["Obtain the Phase Two decision and name the first pilot owner.", "Set one success measure before production starts."],
    nextMoves: [["Review", "NKCDC stakeholders", "Confirm feedback and the working-session date.", "Next contact"], ["Select", "NKCDC + Momentum", "Choose one bounded first pilot.", "After review"], ["Measure", "Joint team", "Assign the owner and success definition.", "Before production"]],
    sources: ["NKCDC weekly source data · Aug 3–9 and Aug 17–23", "NKCDC Phase Two Growth Strategy", "Gmail stakeholder follow-up · Aug 4", "Canonical NKCDC client route"],
  },
  {
    id: "hope-wellness-center",
    client: "Hope Wellness Center",
    descriptor: "Local trust, brand content, therapist video, and organic growth planning",
    logo: "hope-wellness-center.png",
    logoBackground: "light",
    accent: "#48A3A1",
    accentBright: "#8ED9D6",
    status: "August review and content work advanced; the first therapist video and implementation priorities remain in review",
    signal: "Hope Wellness moved its fifteen-item implementation queue into active review, advanced therapist video editing, completed the review-cleanup pass, delivered the competitive search-visibility audit, and continued Google Business Profile posting.",
    goal: "Approve the first therapist video, resolve the remaining review flags, and release the first five implementation priorities with clear measurement ownership.",
    kpis: [["Implementation queue", "15", "Five highest-priority actions"], ["Visual library", "17", "Established illustrations"], ["Growth audit", "Delivered", "Organic visibility review"], ["Paid media", "Off", "No August spend claimed"]],
    work: ["Delivered the August plan and carried the fifteen-item implementation queue into review.", "Advanced therapist footage into editing and prepared the first video for client approval.", "Completed the active review-cleanup pass and kept the remaining Rhode Island flags visible for verification.", "Delivered the competitive search-visibility audit and continued the Google Business Profile posting rhythm."],
    analysis: ["August connected the earlier strategy to a practical content and implementation queue. The work is now concentrated around video approval, local trust signals, and the first five site priorities.", "No paid-media performance is claimed. Search, booking, and inquiry outcomes remain pending until the approved actions and measurement routes are live."],
    platforms: [
      { name: "Brand and content", state: "Active review", note: "The therapist video system and established visual library are moving through the review and production sequence.", metrics: [["Video", "In editing"], ["Illustrations", "17"], ["First cut", "Review next"], ["Privacy", "Preserved"]], rows: [["Therapist video", "In review", "—", "First cut", "Approval next"], ["Visual library", "Ready", "—", "17 assets", "Established"]] },
      { name: "Local and organic visibility", state: "Audit delivered · actions pending", note: "The competitive visibility audit, Google Business Profile posts, and review-cleanup work define the next growth sequence.", metrics: [["Audit", "Delivered"], ["Review cleanup", "Completed"], ["GBP posts", "Active"], ["Paid media", "Off"]], rows: [["Competitive visibility audit", "Delivered", "—", "Priority map", "Review"], ["Review cleanup", "Completion pass", "—", "Flags tracked", "Verify"], ["Google Business Profile", "Active", "—", "Posts", "Continue"]] },
    ],
    outcome: { platform: "No fresh paid-media result is claimed. August evidence covers content, local trust, visibility planning, and implementation readiness.", business: "Video approval, booking ownership, and measurable inquiry outcomes remain open.", measurement: "Approve the first content and site actions, then track profile engagement, site inquiries, booking actions, and completed appointments." },
    workstreams: [["Implementation", "Fifteen-item queue and five first actions", "Ready"], ["Video", "Therapist footage and first cut", "In review"], ["Local trust", "Review cleanup and profile posts", "Advanced"], ["Visibility", "Competitive organic audit", "Delivered"]],
    detailedWork: [["Plan", "Moved the fifteen-item queue into active review.", "Turns a broad strategy into an ordered release path.", "Ready"], ["Video", "Advanced therapist footage into the first editing sequence.", "Builds trusted, first-party educational content.", "In review"], ["Trust", "Completed the active review-cleanup pass.", "Protects local credibility while keeping open flags visible.", "Advanced"], ["Growth", "Delivered the competitive visibility audit and profile-posting plan.", "Defines the next organic priorities without inventing results.", "Delivered"]],
    wins: ["The implementation queue is ordered around five first actions.", "The first therapist video and organic visibility plan both moved into review."],
    augustFocus: ["Approve the first therapist video and remaining review flags.", "Release the first five site and local-visibility priorities with measurement owners."],
    nextMoves: [["Approve", "Hope Wellness", "Review the first therapist video and outstanding trust flags.", "Next meeting"], ["Release", "Momentum", "Apply the first approved implementation actions.", "After approval"], ["Measure", "Joint team", "Track profile, inquiry, booking, and appointment outcomes.", "After release"]],
    sources: ["Hope Wellness weekly source data · Aug 3–9 and Aug 17–23", "Slack #hope-wellness-center · Aug 24–31", "Hope Wellness competitive visibility audit", "Hope Wellness implementation queue and content system"],
  },
  {
    id: "bar-crawl-usa",
    client: "Bar Crawl USA",
    descriptor: "Halloween landing pages, ticket-path readiness, and seasonal creative",
    logo: "bar-crawl-usa.webp",
    logoBackground: "dark",
    accent: "#EF3C57",
    accentBright: "#FF8A9B",
    status: "Ten Halloween landing pages are live and technically ready; completed-order reconciliation remains open",
    signal: "Ten city-specific Halloween landing pages moved from draft to live release and averaged a 92 out of 100 readiness score. Each page is indexable, connected to secure Eventbrite checkout, and tested across desktop and mobile.",
    goal: "Complete indexing and order reconciliation, then activate the seasonal promotion plan against verified ticket-path results.",
    kpis: [["Live landing pages", "10", "Halloween city program"], ["Readiness score", "92/100", "Average across ten pages"], ["Cities", "10", "Validated local experiences"], ["Latest teaser", "55 sec", "Creative review sequence"]],
    work: ["Built and released Halloween landing pages for Atlanta, Cleveland, Cincinnati, Columbia, Greenville, Portland, St. Pete, Macon, Roswell, and Sarasota.", "Added city-specific event detail, technical search elements, local copy, internal links, structured event information, and secure ticket paths.", "Updated the Event Tracking Sheet with all ten live URLs, focus terms, metadata, source events, and implementation notes.", "Prepared the seasonal teaser sequence and completed the current launch-readiness scorecard."],
    analysis: ["The August work created a complete ten-city seasonal acquisition surface rather than a planning-only packet. The pages now provide indexable local destinations and a consistent path into Eventbrite checkout.", "Checkout initiation tracking is live. Completed-order reconciliation and manual indexing remain the two permission-dependent steps before ticket revenue or return claims are used."],
    platforms: [
      { name: "Halloween landing-page program", state: "Live · August 27", note: "Ten city pages are live, indexable, included in the sitemap, and connected to secure ticket checkout.", metrics: [["Pages", "10"], ["Cities", "10"], ["Avg. score", "92"], ["Mobile QA", "Passed"]], rows: [["Atlanta–Greenville", "Live", "5 pages", "City-specific", "Ticket paths"], ["Portland–Sarasota", "Live", "5 pages", "City-specific", "Ticket paths"]] },
      { name: "Measurement and creative", state: "Partially complete", note: "Checkout initiation tracking and the seasonal teaser sequence are in place. Completed-order reconciliation and manual indexing remain open.", metrics: [["Checkout start", "Live"], ["Order join", "Pending"], ["Teaser", "55 sec"], ["Index requests", "Pending"]], rows: [["Event Tracking Sheet", "Updated", "—", "10 URLs", "Source map"], ["Seasonal teaser", "Prepared", "—", "Review cut", "Creative"], ["Completed orders", "Pending", "—", "Not joined", "Permission needed"]] },
    ],
    outcome: { platform: "No paid-media spend is claimed. The verified August result is ten live, indexable seasonal pages with checkout-initiation tracking.", business: "Completed ticket orders and revenue are not yet reconciled to page and checkout activity.", measurement: "Join completed orders to city and page, request indexing, and review ticket-path performance before promotion decisions." },
    workstreams: [["Pages", "Ten city-specific Halloween destinations", "Live"], ["Search", "Metadata, local detail, internal links, and sitemap", "Complete"], ["Creative", "Seasonal teaser sequence", "Prepared"], ["Measurement", "Checkout start and completed-order join", "Partial"]],
    detailedWork: [["Build", "Released ten city-specific Halloween pages.", "Creates durable local destinations for seasonal demand.", "Live"], ["Search", "Completed the technical and local launch layer.", "Makes every page indexable and reviewable.", "Complete"], ["Tickets", "Connected secure Eventbrite checkout and checkout-start tracking.", "Creates a measurable path toward ticket action.", "Live"], ["Reconciliation", "Held completed orders and revenue as an open evidence join.", "Prevents unsupported sales claims.", "Pending"]],
    wins: ["All ten Halloween city pages are live with an average 92/100 readiness score.", "The ticket path and checkout-initiation measurement are active."],
    augustFocus: ["Request indexing and reconcile completed orders by city and page.", "Use verified ticket-path evidence to guide the seasonal promotion sequence."],
    nextMoves: [["Index", "Web owner", "Submit the ten live pages for search indexing.", "Early September"], ["Reconcile", "Analytics + Bar Crawl", "Join completed Eventbrite orders to city and page activity.", "Before promotion review"], ["Activate", "Momentum", "Use verified ticket-path results to sequence seasonal promotion.", "After reconciliation"]],
    sources: ["Bar Crawl USA weekly source data · Aug 3–9 and Aug 17–23", "Halloween Landing Page Launch Scorecard · Aug 27", "Slack #bar-crawl-usa · Aug 24–31", "Event Tracking Sheet update and seasonal teaser handoff"],
  },
  {
    id: "va-claims-edge",
    client: "VA Claims Edge",
    descriptor: "Seven-stage claimant journey, Nexus Letter flow, and portal readiness",
    logo: "va-claims-edge.png",
    logoBackground: "light",
    accent: "#D8AA55",
    accentBright: "#F4D184",
    status: "Phase Three advanced through the Nexus Letter flow, tracker updates, and production-readiness handoff",
    signal: "August clarified the seven-stage claimant journey, advanced the Nexus Letter page, updated the Phase Three tracker, prepared the August 20 meeting-readiness package, and confirmed the operating foundation needed for the next connected release.",
    goal: "Apply David and James's feedback, finish the Nexus Letter journey, and verify the next release against the seven-stage operating model before real claimant use expands.",
    kpis: [["Claimant stages", "7", "Owned journey model"], ["Nexus Letter page", "Started", "Phase Three surface"], ["Readiness review", "Aug 20", "Meeting package"], ["Core services", "Confirmed", "Next connection phase"]],
    work: ["Translated the operating process into a seven-stage journey with ownership and event-based progression.", "Started the Nexus Letter page as the next focused claimant-support surface.", "Updated the Phase Three tracker and prepared the August 20 meeting-readiness package for David and James.", "Confirmed the core account, appointment, evidence, messaging, and payment-watch foundation for the next release."],
    analysis: ["The August work moved VA Claims Edge from a visual review surface toward an owned operating journey. The seven stages and Nexus Letter flow now provide a clear basis for the next release.", "The next constraint is review and validation. Informational claims language, claimant privacy, and journey verification remain explicit gates before wider real-world use."],
    platforms: [
      { name: "Claimant portal", state: "Phase Three · active build", note: "The seven-stage journey, Nexus Letter surface, tracker, and current portal state were prepared for the August review sequence.", metrics: [["Stages", "7"], ["Nexus page", "Started"], ["Tracker", "Updated"], ["Review", "Meeting-ready"]], rows: [["Seven-stage journey", "Defined", "—", "Owner model", "Verify"], ["Nexus Letter flow", "Started", "—", "Focused surface", "Finish next"], ["Portal review package", "Delivered", "—", "Aug 20", "Client-ready"]] },
      { name: "Operational readiness", state: "Foundation confirmed · connection next", note: "The core account, appointment, evidence, messaging, and payment-watch services were confirmed for the next connection phase.", metrics: [["Account path", "Confirmed"], ["Appointments", "Confirmed"], ["Evidence", "Confirmed"], ["Real-data use", "Gated"]], rows: [["Core service foundation", "Confirmed", "—", "Production basis", "Connect next"], ["Real claimant use", "Held", "—", "Privacy and review", "Gate remains"]] },
    ],
    outcome: { platform: "No paid-media metric is claimed. August evidence covers the claimant journey, portal surfaces, tracker, and operational readiness.", business: "Claimant progression and completed service outcomes remain pending the finished journey and verified connected release.", measurement: "Validate the seven-stage journey, claimant actions, and operational handoffs before using outcome reporting." },
    workstreams: [["Journey", "Seven-stage operating model", "Defined"], ["Nexus Letter", "Focused claimant-support flow", "Started"], ["Tracker", "Phase Three readiness and meeting package", "Updated"], ["Operations", "Core service foundation", "Confirmed"]],
    detailedWork: [["Journey", "Defined seven owned stages and progression rules.", "Aligns the portal with the real operating process.", "Defined"], ["Nexus", "Started the next claimant-support flow.", "Turns a priority service into a focused experience.", "Started"], ["Review", "Updated the tracker and prepared the Aug 20 package.", "Gives David and James a current decision surface.", "Delivered"], ["Readiness", "Confirmed the operational foundation for the next release.", "Reduces ambiguity before wider use.", "Confirmed"]],
    wins: ["The claimant journey is now organized into seven owned stages.", "The Nexus Letter and operational readiness work both advanced in August."],
    augustFocus: ["Finish the Nexus Letter flow and apply the review feedback.", "Verify the next connected release against the full seven-stage journey."],
    nextMoves: [["Apply", "VA Claims Edge + Momentum", "Resolve David and James's meeting feedback.", "Next review"], ["Finish", "Product team", "Complete the Nexus Letter journey and supporting handoffs.", "Phase Three"], ["Verify", "Joint team", "Test the next release against all seven stages and privacy gates.", "Before wider use"]],
    sources: ["VA Claims Edge weekly source data · Aug 3–9 and Aug 17–23", "Slack #va-claims · Aug 24–30", "VA Claims Edge meeting-readiness package · Aug 20", "VA Claims Edge Phase Three tracker and current portal readback"],
  },
  {
    id: "revive-systems",
    client: "Revive Systems",
    descriptor: "Organic content package, local service positioning, and publication readiness",
    logo: "revive-systems.png",
    logoBackground: "dark",
    accent: "#56C271",
    accentBright: "#93E2A5",
    status: "The five-piece organic package remains ready but unpublished; client approval is still pending",
    signal: "Revive stayed in an organic-first operating mode. The five-piece content and sitemap package remained ready, the Marketing Thoughts document was prepared for review, and paid media stayed off pending approval and route decisions.",
    goal: "Collect client feedback, approve the first publication sequence, establish the organic baseline, and confirm the Local Services Ads readiness gate before any paid activation.",
    kpis: [["Content pieces", "5", "Organic acquisition package"], ["Strategy document", "1", "Prepared August 18"], ["Publishing state", "Pending", "Approval required"], ["Paid media", "Off", "No August spend claimed"]],
    work: ["Delivered the August organic-growth plan and preserved the five-piece content package for review.", "Kept the sitemap and organic acquisition path ready without representing the package as published.", "Prepared the Revive Systems Marketing Thoughts document for client feedback.", "Held paid media and Local Services Ads behind the exact approval, account, and readiness decisions."],
    analysis: ["Revive's August value is a complete organic package and a clear decision path, not a live performance claim. Publication remains the step that turns prepared work into measurable visibility.", "Paid media stayed off. The correct next measure is the post-publication baseline for rankings, organic landing-page activity, inquiries, and booked consultations."],
    platforms: [
      { name: "Organic acquisition", state: "Package ready · publication pending", note: "Five content pieces, the sitemap path, and the current strategy document are ready for an approved publication sequence.", metrics: [["Pieces", "5"], ["Sitemap", "Ready"], ["Strategy", "Prepared"], ["Publish", "Pending"]], rows: [["Five-piece content package", "Ready", "—", "Review set", "Unpublished"], ["Sitemap path", "Ready", "—", "Release support", "Pending"], ["Marketing Thoughts", "Prepared", "—", "Client review", "Aug 18"]] },
      { name: "Paid readiness", state: "Off · approval-gated", note: "No live paid-media activity is claimed. The exact account route, tracking, and Local Services Ads decision remain open.", metrics: [["Paid media", "Off"], ["LSA", "Open"], ["Tracking", "Pending"], ["Approval", "Required"]], rows: [["Paid acquisition", "Held", "$0 claimed", "No live KPI", "Map first"], ["Local Services Ads", "Readiness review", "—", "Not activated", "Decision needed"]] },
    ],
    outcome: { platform: "No August paid-media result is claimed. The verified work is the prepared organic package, sitemap path, and strategy document.", business: "Organic visibility, inquiries, consultations, and revenue remain pending publication and baseline measurement.", measurement: "Publish the approved sequence, record the organic baseline, and confirm the paid-readiness route before activation." },
    workstreams: [["Content", "Five-piece organic package", "Ready"], ["Sitemap", "Organic acquisition path", "Ready"], ["Strategy", "Marketing Thoughts document", "Prepared"], ["Paid readiness", "Local Services Ads and tracking gate", "Open"]],
    detailedWork: [["Content", "Kept the five-piece package ready for review.", "Provides a coherent organic acquisition system.", "Ready"], ["Sitemap", "Preserved the site release path.", "Connects the content to public discovery.", "Ready"], ["Strategy", "Prepared the current client review document.", "Creates one focused approval conversation.", "Prepared"], ["Paid", "Held activation behind account, tracking, and approval gates.", "Keeps readiness separate from live performance.", "Off"]],
    wins: ["The five-piece organic package and sitemap path remain complete.", "Paid readiness is clearly separated from live delivery claims."],
    augustFocus: ["Approve and publish the first organic sequence.", "Confirm the Local Services Ads and tracking route before paid activation."],
    nextMoves: [["Approve", "Revive Systems", "Review the strategy document and select the first publication sequence.", "Next contact"], ["Publish", "Momentum", "Release the approved content and sitemap updates.", "After approval"], ["Baseline", "Organic team", "Record visibility, inquiries, and consultation activity.", "After publication"]],
    sources: ["Revive Systems weekly source data · Aug 3–9 and Aug 17–23", "Revive Systems Marketing Thoughts · Aug 18", "Slack #revive-systems · Aug 24", "Canonical Revive organic content and sitemap package"],
  },
  {
    id: "bridge-software",
    client: "Bridge Software",
    descriptor: "Product experience, role-based journeys, and release readiness",
    logo: "bridge-software.svg",
    logoBackground: "dark",
    accent: "#8D5CF6",
    accentBright: "#C4A8FF",
    status: "Five primary product routes are live; additional Community content and UI refinements are now included in the verified production release",
    signal: "August converted Tori's feedback into a complete product definition, unified five primary product routes, expanded Community with a deeper image-forward sample feed, and established a controlled preview-to-production release path for the client team.",
    goal: "Secure product approval on the five routes, connect the approved experiences to live account and organization data, and verify the full role-based journey before the next production release.",
    kpis: [["Primary routes", "5", "Home, Community, Create, Profile, Explore"], ["Community posts", "20", "Illustrative sample feed"], ["Unique images", "56", "Verified editorial assets"], ["Verification checks", "52", "Desktop and mobile passed"]],
    work: ["Translated Tori's review into the product map, priority journeys, screen requirements, and acceptance criteria.", "Built and unified Home, Community News, Create, My Profile, and Explore into one coherent product experience.", "Expanded Community News to twenty image-led sample posts across twelve sample markets, including promotions, events, product introductions, vendor announcements, education, service updates, and market signals.", "Refined the Community interface with visual and classic feed options, nationwide filters, favorites controls, clearer content density, and a unique editorial image system.", "Established the preview and production release path, documented the handoff, and granted the required client-team access."],
    analysis: ["Bridge's August work is a product-delivery story: five coherent routes, clear role and privacy rules, a more complete Community review surface, and a controlled release path now give the team one shared implementation experience.", "The added Community content demonstrates the intended range without representing live market activity. Product approval and live-data connection remain separate from technical readiness, so no unapproved route is represented as final client direction."],
    platforms: [
      { name: "Product experience", state: "Live · five routes", note: "Home, Community News, Create, My Profile, and Explore are unified in the current Bridge experience with role, privacy, nationwide discovery, and a fuller image-forward Community demonstration.", metrics: [["Routes", "5"], ["Community posts", "20"], ["Sample markets", "12"], ["Approval", "Open"]], rows: [["Home + Community News", "Live", "—", "Image-forward review", "Review"], ["Create + My Profile", "Live", "—", "Protected flows", "Review"], ["Explore", "Live", "—", "50 states + D.C.", "Review"]] },
      { name: "Release and handoff", state: "Established · next connection pending", note: "The preview and production workflow, team access, release documentation, unique image verification, and latest desktop and mobile verification pass are in place.", metrics: [["Checks", "52 passed"], ["Unique assets", "56"], ["Environments", "2"], ["Connection", "Next"]], rows: [["Community UI refresh", "Live", "—", "Grid + classic views", "Review"], ["Production workflow", "Ready", "—", "Controlled promotion", "Active"], ["Team handoff", "Delivered", "—", "Access + documentation", "Accept invites"]] },
    ],
    outcome: { platform: "No paid-media metric is claimed. August evidence covers five live product routes, twenty illustrative Community posts, fifty-six unique editorial assets, two release environments, the team handoff, and the passed verification suite.", business: "Final product approval and real account activity remain pending the client review and live-data connection.", measurement: "Verify the approved role-based journeys, account actions, and organization workflows before the next production promotion." },
    workstreams: [["Definition", "Product map and acceptance criteria", "Complete"], ["Experience", "Five routes plus expanded Community UI", "Live"], ["Privacy", "Role and visibility model", "Defined"], ["Release", "Preview, production, and team handoff", "Established"]],
    detailedWork: [["Definition", "Converted client feedback into the product and acceptance map.", "Gives every route a clear job and review standard.", "Complete"], ["Routes", "Unified the five primary product experiences.", "Creates one coherent client review surface.", "Live"], ["Community", "Expanded content depth, imagery, filters, and feed treatments.", "Makes the nationwide community concept easier to evaluate.", "Live"], ["Roles", "Defined public, verified, organization, and administrator visibility.", "Protects sensitive information and responsibilities.", "Defined"], ["Release", "Established the controlled review and production handoff.", "Makes future changes safer and easier to verify.", "Established"]],
    wins: ["All five primary routes are live in one coherent experience.", "Community now includes twenty sample posts, twelve sample markets, and fifty-six unique editorial assets.", "The latest production release passed fifty-two desktop and mobile checks."],
    augustFocus: ["Obtain product approval on the five primary routes.", "Connect approved journeys to live account and organization data, then verify role behavior."],
    nextMoves: [["Approve", "Tori + Bridge", "Review and approve the five primary product routes.", "Next product review"], ["Connect", "Bridge implementation team", "Connect approved journeys to live account and organization data.", "After approval"], ["Verify", "Momentum", "Test the complete role-based journey before production promotion.", "Before release"]],
    sources: ["Bridge client feedback and Phase Two plan · Aug 1", "Bridge Phase Two Milestone Two work report · Aug 16", "Bridge Milestone Three progress package · Aug 24", "Slack #bridge-software-development · Aug 24–31", "Bridge integration-pipeline approval · Aug 31", "Bridge Community content and UI verification · Aug 31"],
  },
];
