export const period = "August 3 to August 9, 2026";
export const observedAt = "August 10, 2026";
export const leadAccounting = "Platform-reported lead events are shown as whole integers where a current platform read was authorized. Platform activity remains separate from qualified inquiries, booked work, revenue, and other downstream outcomes. Unavailable fields remain pending validation.";

const common = {
  observedAt,
  measurementHeading: "Weekly evidence is separated from downstream business outcomes.",
};

export const reports = [
  {
    ...common,
    id: "kimberly-james-bridal",
    client: "Kimberly James Bridal",
    descriptor: "Meta, Google Search, and appointment measurement",
    logo: "kimberly-james-bridal.png",
    logoBackground: "light",
    accent: "#E6C85C",
    accentBright: "#F5D978",
    status: "Current paid-media read complete; appointment follow-up is the next decision",
    signal: "The Aug 3 to Aug 9 read captured two Meta paid-form leads and a separate Google Search signal. The work this week stayed focused on lead quality, search intent, and connecting inquiries to real bridal appointments.",
    goal: "Match the two current inquiries to contact and appointment outcomes, then use that evidence before changing budgets, bids, or form settings.",
    kpis: [
      ["Meta paid-form leads", "2", "Aug 3 to Aug 9"],
      ["Meta cost per lead", "$34.40", "Higher Intent form"],
      ["Google spend", "$156.61", "Philadelphia Search"],
      ["Google clicks", "46", "676 impressions · 6.80% CTR"],
    ],
    work: [
      "Completed the Aug 3 client report handoff with the Meta and Google lanes kept separate.",
      "Captured the two current Meta form leads with the approved qualification fields and preserved a separate follow-up route.",
      "Reviewed the Philadelphia Search campaign, search-intent controls, and the pending image recommendation without applying a platform change.",
      "Kept the appointment path mapped from ad click through form submission and consultation so the next decision is based on business quality.",
    ],
    analysis: [
      "The account has a clean weekly signal: two Meta form leads, measurable Google Search traffic, and a defined appointment path. The most useful next step is lead follow-up and outcome matching rather than more spend.",
      "Meta and Google remain distinct reporting lanes. Google conversion reporting is pending validation beyond the platform traffic and form signals shown here.",
    ],
    platforms: [
      {
        name: "Meta Ads",
        state: "Active · weekly read",
        note: "The Higher Intent form recorded two paid-form leads in the reporting window. Leads Center showed both in Intake and unassigned at the source read.",
        metrics: [["Paid-form leads", "2"], ["Cost / lead", "$34.40"], ["Form state", "Intake"], ["Follow-up", "Pending"]],
        rows: [["Higher Intent form", "Active", "Pending", "2 leads", "Qualification captured"], ["Leads Center", "Intake", "—", "2 records", "Unassigned at read"]],
      },
      {
        name: "Google Ads",
        state: "Active · weekly read",
        note: "Philadelphia Search recorded $156.61 in spend, 46 clicks, 676 impressions, and a 6.80% click-through rate. No recommendation was applied.",
        metrics: [["Spend", "$156.61"], ["Clicks", "46"], ["Impressions", "676"], ["CTR", "6.80%"]],
        rows: [["Philadelphia Search", "Eligible", "$156.61", "46 clicks", "Image suggestion pending"], ["Appointment path", "Mapped", "—", "—", "Outcome join next"]],
      },
    ],
    outcome: {
      platform: "The current weekly platform read contains two Meta paid-form leads and Google Search traffic from 46 clicks on 676 impressions.",
      business: "Contact, appointment, and booked-consultation outcomes were not reconciled in the platform read.",
      measurement: "Match the two inquiries to contact and appointment status, then use the result to guide the next campaign decision.",
    },
    workstreams: [["Meta", "Higher Intent form and current lead read", "Verified"], ["Google", "Philadelphia Search weekly review", "Verified"], ["Measurement", "Inquiry-to-appointment join", "Next"], ["Communication", "Weekly report and separate lead route", "Delivered"]],
    detailedWork: [
      ["Report", "Delivered the Aug 3 to Aug 9 weekly read with separate Meta and Google lanes.", "Gives the client one current view without blending channels.", "Delivered"],
      ["Lead read", "Captured two Meta paid-form leads and the approved qualification fields.", "Keeps lead quality visible before budget decisions.", "Verified"],
      ["Search", "Reviewed Philadelphia Search delivery and the image recommendation.", "Keeps the current search signal grounded in the authorized account read.", "Read only"],
      ["Appointments", "Held the inquiry-to-consultation match as the next measurement step.", "Moves reporting from activity toward real boutique outcomes.", "Next"],
    ],
    wins: ["The weekly read has a clear two-lead Meta signal.", "The appointment path and channel boundaries remain explicit."],
    augustFocus: ["Follow up on the two current inquiries and record appointment status.", "Use contact quality and consultation outcomes before changing spend or form settings."],
    nextMoves: [["Reconcile", "Dillon + Kim", "Match each inquiry to contact and consultation status", "Next read"], ["Review", "Paid media", "Check Search terms and location quality after learning stabilizes", "Weekly"], ["Decide", "Kim + Momentum", "Keep or adjust the Higher Intent form based on outcome quality", "After follow-up"]],
    sources: ["Meta Ads and Leads Center · account 1249689223687250 · Aug 3 to Aug 9", "Google Ads · customer 814-550-6229 · Aug 3 to Aug 9", "Slack · #kimberly-james-bridal · Aug 3 report handoff", "Gmail · Kimberly James Bridal lead and report threads", "Canonical Meta qualification notes"],
  },
  {
    ...common,
    id: "onsite-concrete-landscape",
    client: "Onsite Concrete and Landscape",
    descriptor: "Google Ads, Fairfield expansion, and measurement readiness",
    logo: "onsite-concrete-landscape.png",
    logoBackground: "dark",
    accent: "#F45B4D",
    accentBright: "#FF8B7F",
    status: "Google Ads restored and running; Fairfield local-content work advanced",
    signal: "The Google Ads campaign temporarily went offline during the Aug 3 to Aug 9 reporting window. The issue was corrected, the ads were relaunched over the weekend, and delivery is now back to normal and running again.",
    goal: "Monitor the restored campaign, finish the page review and publishing path, and match future forms and calls to qualified estimates.",
    kpis: [["Google status", "Running", "Restored over the weekend"], ["Weekly interruption", "Resolved", "Aug 3 to Aug 9"], ["Fairfield pages", "2", "Created Aug 3"], ["Measurement", "Pending", "Form and call setup"]],
    work: [
      "Corrected the temporary Google Ads interruption and relaunched the campaign over the weekend.",
      "Created the Fairfield concrete walkway extension and concrete driveway extension pages.",
      "Preserved the approved service-content batch and schema requirements for the next publishing step.",
      "Kept the qualified-estimate measurement correction plan separate from raw platform activity.",
    ],
    analysis: [
      "The campaign temporarily went offline during the reporting window. It was corrected and relaunched over the weekend, and the ads are now back to normal and running again.",
      "The interruption is resolved. The next paid-media priority is to monitor delivery stability while measurement and qualified-estimate matching are completed.",
    ],
    platforms: [
      { name: "Google Ads", state: "Running · restored after weekly window", note: "The campaign temporarily went offline during Aug 3 to Aug 9. The issue was corrected, ads were relaunched over the weekend, and delivery is now back to normal.", metrics: [["Current status", "Running"], ["Interruption", "Resolved"], ["Relaunch", "Weekend"], ["Delivery", "Normal"]], rows: [["Current campaign overview", "Running", "Existing settings", "Restored", "Back to normal"], ["Conversion setup", "Pending", "—", "—", "Monitor and validate"]] },
      { name: "SEO and local search", state: "In progress", note: "Two Fairfield location pages were created and the approved service-content foundation remains ready for review and publishing.", metrics: [["Fairfield pages", "2"], ["Schema work", "Ready"], ["Service content", "Approved"], ["Outcome", "Pending"]], rows: [["Walkway extension · Fairfield", "Created", "—", "Page ready", "Review"], ["Driveway extension · Fairfield", "Created", "—", "Page ready", "Review"]] },
    ],
    outcome: { platform: "Google Ads temporarily went offline during the Aug 3 to Aug 9 window. The issue was corrected, the ads were relaunched over the weekend, and the campaign is now running normally again.", business: "Qualified estimates, booked work, and revenue were not available in the current window.", measurement: "Monitor the restored campaign and match future forms and calls to named estimates before using paid-media activity to guide budget." },
    workstreams: [["Paid search", "Current Google state and measurement review", "Verified"], ["Local content", "Two Fairfield service pages", "Created"], ["Publishing", "Approved service batch and schema requirements", "Ready"], ["Measurement", "Form, call, and estimate reconciliation", "Pending"]],
    detailedWork: [["Report", "Delivered the weekly report and separated current paid state from prior work.", "Keeps an empty delivery window from being overinterpreted.", "Delivered"], ["Fairfield", "Created concrete walkway and driveway extension pages for Fairfield.", "Expands service-area coverage beyond the current core market.", "Created"], ["Content", "Preserved the approved service batch and schema requirements.", "Creates a controlled publishing path for local-search growth.", "Ready"], ["Measurement", "Held conversion tracking and qualified-estimate matching as the next gate.", "Prevents raw platform events from standing in for business outcomes.", "Pending"]],
    wins: ["Google Ads were corrected, relaunched, and returned to normal delivery.", "Two Fairfield service destinations were created."],
    augustFocus: ["Monitor the restored campaign through the next reporting window.", "Review and publish the Fairfield pages and approved service batch."],
    nextMoves: [["Monitor", "Web + Ads", "Confirm stable delivery after the weekend relaunch", "Next read"], ["Review", "Onsite + Momentum", "Approve Fairfield page copy, links, and schema", "Next read"], ["Reconcile", "Dillon + Onsite", "Match new inquiries to estimate status", "After delivery"]],
    sources: ["Google Ads · customer 103-371-5894 · Aug 3 to Aug 9", "Slack · #onsite-construction · Fairfield handoff and Aug 3 report", "Gmail · Onsite report thread", "Canonical landing-page release record", "Approved service-content batch"],
  },
  {
    ...common,
    id: "omega-landscaping",
    client: "Omega Landscaping and Concrete",
    descriptor: "Google Ads, estimate destination, and local proof",
    logo: "omega-landscaping.png",
    logoBackground: "dark",
    accent: "#4B82D8",
    accentBright: "#8CB7FF",
    status: "High-intent Search reviewed; estimate destination published",
    signal: "Omega's weekly read captured two reported Google conversions alongside a published estimate destination and a continuing local-proof rhythm. The next decision is project quality, not a larger blended total.",
    goal: "Match the two reported conversions and any calls or forms to named inquiries and project status before changing budget or campaign settings.",
    kpis: [["Reported conversions", "2", "Google dashboard"], ["Google clicks", "56", "1,050 impressions · 5.34% CTR"], ["Google spend", "$387.83", "High Intent Search"], ["Optimization score", "84.2%", "Suggestion not applied"]],
    work: [
      "Delivered the Aug 3 weekly report with the current Google lane and local work separated.",
      "Published the dedicated Omega estimate destination on August 5 with form measurement and campaign parameters preserved.",
      "Reviewed the High Intent Search lane read only and left the Display Expansion recommendation unapplied.",
      "Carried forward the Google Business Profile project-proof rhythm and its next creative release.",
    ],
    analysis: [
      "The weekly signal is a usable combination of two reported conversions, 56 clicks, and a live estimate destination. The page release gives future traffic a clearer place to become an inquiry.",
      "Reported conversions still need named-lead and project-quality reconciliation. That join is more decision-useful than changing the campaign from the dashboard signal alone.",
    ],
    platforms: [
      { name: "Google Ads", state: "Active · weekly read", note: "The current read recorded two reported conversions, 1,050 impressions, 56 clicks, and $387.83 in High Intent Search spend. The Display Expansion suggestion was not applied.", metrics: [["Conversions", "2"], ["Clicks", "56"], ["Spend", "$387.83"], ["CTR", "5.34%"]], rows: [["High Intent Search", "Active", "$387.83", "56 clicks", "2 reported conversions"], ["Optimization suggestion", "Held", "—", "—", "Not applied"]] },
      { name: "Estimate destination", state: "Published · Aug 5", note: "The dedicated estimate page went live with form action, tags, and campaign-parameter handling verified in the release record.", metrics: [["Status", "Published"], ["Form", "Wired"], ["Tags", "Verified"], ["Next", "Lead join"]], rows: [["Omega estimate page", "Published", "—", "Form route", "Parameters preserved"], ["Project quality", "Pending", "—", "—", "CRM join next"]] },
    ],
    outcome: { platform: "The weekly Google read recorded two reported conversions, 56 clicks, 1,050 impressions, and $387.83 in spend.", business: "Named inquiries, qualified projects, booked work, and revenue were not reconciled in the current platform read.", measurement: "Match the two reported conversions and any calls or forms to named inquiries and project status before using the signal to guide budget." },
    workstreams: [["Paid search", "High Intent weekly account read", "Verified"], ["Landing page", "Dedicated estimate destination", "Published"], ["Local proof", "GBP project-content rhythm", "Carried forward"], ["Lead quality", "Named inquiry and project join", "Next"]],
    detailedWork: [["Report", "Delivered the weekly report with paid and local lanes separated.", "Keeps current evidence and prior production legible in one read.", "Delivered"], ["Landing page", "Published the dedicated estimate destination and verified its form route.", "Gives current search traffic a clean inquiry destination.", "Published"], ["Search", "Reviewed High Intent Search and held the Display Expansion suggestion.", "Keeps the account decision tied to the approved scope.", "Read only"], ["Lead quality", "Held named-inquiry and project-status matching as the next step.", "Moves the account from platform activity toward opportunity quality.", "Next"]],
    wins: ["The estimate destination is live and wired.", "The current Search signal is measurable without an unapproved recommendation being applied."],
    augustFocus: ["Match reported conversions to named inquiries and project status.", "Continue the local proof rhythm and review Search quality by service and location."],
    nextMoves: [["Reconcile", "Dillon + Omega", "Match current events to calls, forms, inbox, and project records", "Next read"], ["Publish", "Content", "Release the next approved local-proof batch", "Weekly"], ["Decide", "Paid media", "Use project quality before changing budget", "After reconciliation"]],
    sources: ["Google Ads · customer 285-398-1364 · Aug 3 to Aug 9", "Canonical estimate-page release record · published Aug 5", "Slack · #omega-landscape · Aug 3 report and lead-quality follow-up", "Gmail · Omega report thread", "Google Business Profile batch README"],
  },
  {
    ...common,
    id: "replenish-7-eleven",
    client: "Replenish / 7-Eleven",
    descriptor: "Brand-separated reporting, billing, and account readiness",
    logo: "replenish-7-eleven.png",
    logoBackground: "light",
    accent: "#F4B400",
    accentBright: "#FFD45C",
    status: "Report-only lane; Ads delivery held behind billing and account resolution",
    signal: "Replenish stayed a report-only lane this week. The brand-separated presentation was delivered, billing and access follow-ups continued, and Fresh Blends remained completely outside this report.",
    goal: "Resolve billing and account ownership before reactivation, then capture a clean weekly window before making optimization recommendations.",
    kpis: [["Ad delivery", "Paused", "No account inspection"], ["Current spend", "Not reported", "No fresh delivery read"], ["Work completed", "3 follow-ups", "Aug 3 to Aug 6"], ["Next gate", "Billing", "Before reactivation"]],
    work: [
      "Delivered the Replenish and 7-Eleven presentation separately on August 3 with its own logo and reporting boundary.",
      "Followed the billing and access route through the Aug 4 to Aug 6 communication thread.",
      "Kept Fresh Blends and Kwik Trip out of the Replenish totals, logo, and next actions.",
      "Held reactivation and optimization until account resolution produces a clean current-window read.",
    ],
    analysis: [
      "This week's work was control and separation. Replenish has a distinct reporting lane, but no current Ads metrics were available without opening the account, which remains outside the approved scope.",
      "Billing and access are the decision gates. A fresh weekly performance read should begin only after delivery resumes and the account route is confirmed.",
    ],
    platforms: [
      { name: "Google Ads", state: "Paused · report only", note: "The current communication evidence states that delivery is held pending payment and account resolution. The Ads account was not opened for this report.", metrics: [["Status", "Paused"], ["Spend", "Not reported"], ["Leads", "Not reported"], ["Access", "Pending"]], rows: [["Replenish Ads lane", "Held", "—", "No current read", "Billing gate"], ["Reactivation", "Not started", "—", "—", "Approval needed"]] },
      { name: "Client reporting", state: "Delivered · Aug 3", note: "The Replenish presentation was delivered separately, without blending Fresh Blends performance into the client view.", metrics: [["Report", "1"], ["Brand", "Separate"], ["Fresh Blends", "Excluded"], ["Next", "Billing"]], rows: [["Replenish report", "Delivered", "—", "Separate packet", "7-Eleven mark"], ["Fresh Blends", "Excluded", "—", "Separate lane", "No blended totals"]] },
    ],
    outcome: { platform: "No current-week Ads metric is claimed. The authorized evidence supports a paused report-only lane while billing and access are resolved.", business: "Store engagement and downstream outcomes are not reported for this window.", measurement: "Capture a clean Monday through Sunday platform window only after delivery resumes; keep all Fresh Blends evidence separate." },
    workstreams: [["Reporting", "Brand-separated Replenish presentation", "Delivered"], ["Billing", "Account and payment follow-ups", "Open"], ["Boundary", "Fresh Blends exclusion", "Verified"], ["Media", "Reactivation readiness", "Held"]],
    detailedWork: [["Reporting", "Delivered the separate Replenish presentation on Aug 3.", "Keeps the 7-Eleven brand and totals distinct.", "Delivered"], ["Account", "Followed the billing and access thread through Aug 6.", "Identifies the gate before any new delivery read.", "Open"], ["Boundary", "Excluded Fresh Blends from the packet and next actions.", "Prevents cross-brand contamination.", "Verified"], ["Media", "Held reactivation and optimization until account resolution.", "Avoids making recommendations from an unavailable current window.", "Held"]],
    wins: ["The Replenish report stayed brand-separated.", "No unsupported current-week Ads metric was introduced."],
    augustFocus: ["Resolve billing and account ownership.", "Begin a clean weekly performance read after delivery resumes."],
    nextMoves: [["Resolve", "Sean + Mia", "Close the billing and account-access route", "Before reactivation"], ["Read", "Dillon", "Capture the next clean Monday through Sunday window", "After delivery"], ["Optimize", "Momentum", "Use current evidence only after the account is live", "After read"]],
    sources: ["Gmail · Replenish communication thread · Aug 3 to Aug 6", "Slack · #fresh-blends · brand-separated handoff", "Canonical balance-reconciliation package", "User-provided run note · Replenish did not have Ads delivery this week"],
  },
  {
    ...common,
    id: "fresh-blends-kwik-trip",
    client: "Fresh Blends / Kwik Trip",
    descriptor: "Brand separation, Ice Box staging, and September scale planning",
    logo: "fresh-blends.png",
    logoBackground: "light",
    accent: "#E0A24B",
    accentBright: "#FFD487",
    status: "Separate Fresh Blends lane; expansion is held for location and budget approval",
    signal: "Fresh Blends stayed separate from Replenish while the four Ice Box rows remained clearly mapped and the team prepared a September scale-up conversation for more locations.",
    goal: "Confirm locations, budget, landing destinations, and measurement before any expansion or campaign restart.",
    kpis: [["Separate report", "1", "Delivered Aug 3"], ["Ice Box rows", "4", "Fresh Blends perimeter"], ["Scale-up scope", "10+", "September planning"], ["Launch gate", "Pending", "Location and budget approval"]],
    work: [
      "Split the final reporting presentation from Replenish and 7-Eleven on August 3.",
      "Kept the four Kwik Trip Ice Box rows isolated as the Fresh Blends reporting perimeter.",
      "Prepared a September scale-up conversation for more than ten locations while keeping campaign staging behind a green light.",
      "Carried the touchpoint checklist and backend staging forward without representing a restart as live delivery.",
    ],
    analysis: [
      "The important weekly deliverable was control: Fresh Blends now has its own client view and a defined expansion perimeter. The team can plan September without blending the Replenish account.",
      "Location scope, billing, budget, and measurement remain approval gates. No current paid-media total is estimated here.",
    ],
    platforms: [
      { name: "Google Ads", state: "Staged · not expanded", note: "The four Ice Box rows remain the Fresh Blends perimeter. Current expansion and restart timing are held behind location and budget approval.", metrics: [["Rows", "4"], ["Status", "Staged"], ["Spend", "Not reported"], ["Expansion", "Pending"]], rows: [["Ice Box campaign group", "Mapped", "—", "4 rows", "Fresh Blends only"], ["September scale-up", "Planned", "—", "10+ locations", "Approval gate"]] },
      { name: "Planning and operations", state: "In progress", note: "The touchpoint checklist, backend staging, and mid-month planning conversation were carried forward for the September decision.", metrics: [["Touchpoint", "Ready"], ["Backend", "Staged"], ["Sync", "Planned"], ["Green light", "Pending"]], rows: [["September scale-up", "Planning", "—", "10+ locations", "Mid-month sync"], ["Campaign staging", "Ready", "—", "—", "Awaiting approval"]] },
    ],
    outcome: { platform: "No fresh current-week paid-media total is claimed. The authorized work established a separate Fresh Blends perimeter and held expansion behind approval.", business: "Store engagement, purchases, and location outcomes remain pending a confirmed scope and live measurement window.", measurement: "Confirm the location list, budget, destinations, and event definitions before relaunch or scale decisions." },
    workstreams: [["Boundary", "Fresh Blends separated from Replenish", "Verified"], ["Account", "Four Ice Box rows mapped", "Verified"], ["Scale", "September 10-plus location plan", "Planned"], ["Operations", "Touchpoint and backend staging", "Ready"]],
    detailedWork: [["Reporting", "Delivered the Fresh Blends-only presentation on Aug 3.", "Keeps the client view and logo separate from Replenish.", "Delivered"], ["Mapping", "Kept the four Ice Box rows as the Fresh Blends reporting perimeter.", "Prevents cross-brand spend and delivery blending.", "Verified"], ["Scale", "Prepared a September planning route for more than ten locations.", "Turns the next expansion into an explicit scope decision.", "Planned"], ["Operations", "Carried the touchpoint checklist and backend staging forward.", "Keeps the account ready without claiming live restart.", "Ready"]],
    wins: ["Fresh Blends and Replenish are now clearly separate.", "The September expansion conversation has a defined perimeter."],
    augustFocus: ["Confirm location and budget approval for September.", "Keep campaign staging and measurement ready without representing it as live delivery."],
    nextMoves: [["Confirm", "Mia + Sean", "Lock the location list, budget, and timing", "Mid-month"], ["Prepare", "Ruben + Momentum", "Keep staging and touchpoint assets ready", "Before green light"], ["Measure", "Analytics", "Define store and action events before restart", "Before launch"]],
    sources: ["Slack · #fresh-blends · Aug 3 brand-separated handoff and Aug 6 to Aug 8 scale planning", "Gmail · Fresh Blends report thread", "Canonical Fresh Blends launch configuration", "Replenish and Fresh Blends brand-separation record"],
  },
  {
    ...common,
    id: "hope-wellness-center",
    client: "Hope Wellness Center",
    descriptor: "Implementation queue, brand content, and client feedback",
    logo: "hope-wellness-center.png",
    logoBackground: "light",
    accent: "#75C96A",
    accentBright: "#9AE88C",
    status: "Weekly handoff complete; implementation and feedback decisions remain open",
    signal: "The week moved Hope Wellness from a completed strategic package into active review: the report and plan were handed off, video submissions were tracked, and the team routed new feedback on site messaging and local-search work.",
    goal: "Close the highest-priority implementation decisions, confirm measurement ownership, and release the first approved site and booking improvements.",
    kpis: [["Report handoff", "1", "Delivered Aug 3"], ["Implementation items", "15", "5 highest priority"], ["Video system", "Ready", "Submissions tracked"], ["Decision queue", "Open", "Feedback and ownership"]],
    work: [
      "Delivered the Hope Wellness report and August plan on August 3.",
      "Carried the fifteen-item implementation queue and five highest-priority actions into the review path.",
      "Tracked therapist-video submissions and moved the meeting agenda and email-template work forward.",
      "Routed client feedback on site messaging and local-search issues for a controlled decision rather than an unapproved change.",
    ],
    analysis: [
      "This week's work was about turning the completed strategy and creative system into a reviewable implementation queue. The client now has a focused path instead of a broad list of disconnected ideas.",
      "The next constraint is approval and measurement ownership. No live search, booking, or local listing outcome is claimed without the corresponding source access.",
    ],
    platforms: [
      { name: "Search and local surfaces", state: "Strategy · access pending", note: "The current source window contains implementation and feedback work, not a fresh Google, GBP, ranking, or booking export.", metrics: [["Paid media", "Pending"], ["Rankings", "Pending"], ["GBP", "Pending"], ["Booking", "Pending"]], rows: [["Search architecture", "Reviewed", "—", "—", "P0 queue"], ["Booking path", "Pending", "—", "—", "Owner needed"]] },
      { name: "Brand and content", state: "Active review", note: "The brand reel, visual library, therapist video system, and email-template path are moving through review and collection.", metrics: [["Brand reel", "Ready"], ["Illustrations", "17"], ["Video", "Collecting"], ["Emails", "In progress"]], rows: [["Therapist video system", "Collecting", "—", "Submissions", "Review"], ["Email templates", "Planned", "—", "Agenda", "Next meeting"]] },
    ],
    outcome: { platform: "No fresh Google, Meta, ranking, GBP, or booking metric was verified for this weekly report.", business: "Implementation approval, booking ownership, and feedback decisions remain open.", measurement: "Confirm analytics, local-search, form, and booking access before claiming measurable outcome change." },
    workstreams: [["Handoff", "Report and August plan", "Delivered"], ["Implementation", "15-item queue and five first actions", "Ready"], ["Content", "Video and email-template path", "In progress"], ["Decision", "Client feedback and ownership", "Open"]],
    detailedWork: [["Report", "Delivered the weekly client-safe handoff and August next read.", "Gives the team a current review path without inventing metrics.", "Delivered"], ["Implementation", "Carried the fifteen-item queue and five highest-priority actions into review.", "Keeps production ordered around the first decisions.", "Ready"], ["Content", "Tracked video submissions and moved the email-template agenda forward.", "Connects the brand system to the next client-facing work.", "In progress"], ["Feedback", "Routed new site messaging and local-search feedback for decision.", "Prevents unapproved changes from outrunning client direction.", "Open"]],
    wins: ["The report and implementation queue are in the client review path.", "The content system is collecting real team material for the next release."],
    augustFocus: ["Close the first implementation decisions and owners.", "Confirm measurement and booking routes before releasing P0 work."],
    nextMoves: [["Decide", "Joseph + Momentum", "Resolve the first implementation and ownership choices", "Next meeting"], ["Measure", "Analytics owner", "Confirm GA4, GBP, form, and booking routes", "Before release"], ["Release", "Dillon", "Release the first approved actions after route checks", "After approval"]],
    sources: ["Slack · #hope-wellness-center · Aug 3 to Aug 9", "Gmail · Hope Wellness report handoff", "Hope deeper analysis and implementation queue", "Brand reel and therapist-video system notes", "Client feedback and agenda thread"],
  },
  {
    ...common,
    id: "fagan-painting",
    client: "Fagan Painting",
    descriptor: "Organic growth, service pages, and AEO direction",
    logo: "fagan-painting.png",
    logoBackground: "light",
    accent: "#9BB3C5",
    accentBright: "#C8DAE7",
    measurementHeading: "The current weekly read separates the latest organic-search snapshot from historical paid-media activity.",
    leadAccounting: "The paid-media baseline is historical and is not treated as Aug 3 to Aug 9 delivery. Organic-search signals and client work are reported separately.",
    status: "Organic work advanced; paid-media activity remains closed",
    signal: "Fagan's work this week shifted decisively toward organic growth: two service-area pages were published, new service and FAQ pages were advanced, and the next AEO and GEO direction was clarified while paid media remained off.",
    goal: "Continue the approved organic and AI-search work, strengthen service-page structure, and use the Aug 11 meeting to confirm the next production scope.",
    kpis: [["Ranking keywords", "512", "Latest July closeout shared Aug 6"], ["Top-10 terms", "39", "Latest SEO snapshot"], ["Area pages", "2", "North Hills and Highland Park"], ["Paid media", "Off", "Historical lane closed"]],
    work: [
      "Kept the historical Meta closeout separate from the current organic-growth report.",
      "Published North Hills and Highland Park service-area pages and continued the FAQ and service-page structure work.",
      "Advanced the multifamily, exterior, interior, and FAQ page system for clearer residential and commercial intent.",
      "Clarified the next AEO and GEO direction and prepared the Aug 11 client conversation around the next approved scope.",
    ],
    analysis: [
      "The latest organic snapshot shared during the week showed 512 ranking keywords and 39 terms in the top ten, up from the prior comparison. The work now needs to turn that visibility into more organic inquiries.",
      "Paid advertising remains closed. The current client-safe story is organic page production, answer-ready structure, and a clear next-phase discussion.",
    ],
    platforms: [
      { name: "Organic search", state: "Active · weekly update", note: "The team reported 512 ranking organic keywords and 39 top-ten terms in the latest closeout, along with two published service-area pages.", metrics: [["Keywords", "512"], ["Top 10", "39"], ["Area pages", "2"], ["Organic lead", "Reported"]], rows: [["North Hills service area", "Live", "—", "Page published", "Organic structure"], ["Highland Park service area", "Live", "—", "Page published", "Organic structure"]] },
      { name: "Meta Ads", state: "Closed · no current delivery", note: "The paid-media lane remains off. The weekly report does not treat the historical July closeout as current-week delivery.", metrics: [["Status", "Off"], ["Spend", "Not current"], ["Leads", "Historical"], ["Next", "Organic"]], rows: [["Paid-media lane", "Closed", "—", "No current delivery", "Organic focus"], ["AEO / GEO", "Scoping", "—", "Next phase", "Meeting Aug 11"]] },
    ],
    outcome: { platform: "The weekly evidence is an organic-search snapshot and page-production update. No current paid-media delivery is claimed.", business: "A new organic lead was reported in the team update, but broader lead quality and booked-estimate outcomes were not reconciled here.", measurement: "Track page visibility, AI-search citations, organic landing-page activity, and inquiry quality as the new service structure is released." },
    workstreams: [["Organic", "Service-area pages and search snapshot", "Advanced"], ["AEO / GEO", "Next-phase direction", "Clarified"], ["Paid media", "Historical lane", "Closed"], ["Scope", "Aug 11 client meeting", "Scheduled"]],
    detailedWork: [["Pages", "Published North Hills and Highland Park service-area pages.", "Expands local intent coverage with real service destinations.", "Published"], ["Structure", "Advanced FAQ, multifamily, exterior, and interior service-page work.", "Creates clearer residential and commercial topic paths.", "In progress"], ["AEO / GEO", "Clarified the next answer-ready organic direction.", "Keeps the next phase tied to current search behavior.", "Scoping"], ["Meeting", "Prepared the Aug 11 client conversation around the next scope.", "Creates the decision point for continued organic work.", "Scheduled"]],
    wins: ["Two service-area pages were published.", "The latest organic snapshot shows growth in ranking coverage."],
    augustFocus: ["Continue service-page and FAQ improvements.", "Use the Aug 11 meeting to confirm the next AEO and GEO scope."],
    nextMoves: [["Review", "James + Momentum", "Review the new service pages and organic-search read", "Aug 11"], ["Expand", "SEO", "Continue the priority service and FAQ structure", "August"], ["Measure", "Analytics", "Track organic inquiries and page-level movement", "Weekly"]],
    sources: ["Slack · #fagan-painting · Aug 3 to Aug 9", "Fagan organic-search update shared Aug 6", "Canonical AEO and SEO work package", "Historical Meta closeout kept separate", "Gmail · Fagan report thread"],
  },
  {
    ...common,
    id: "nkcdc",
    client: "NKCDC",
    descriptor: "Phase Two proposal, stakeholder follow-up, and pilot decisions",
    logo: "nkcdc.png",
    logoBackground: "light",
    accent: "#E56D4C",
    accentBright: "#FFAB89",
    status: "Proposal follow-up active; first approved pilot remains open",
    signal: "The Aug 3 to Aug 9 work for NKCDC was a decision follow-up: the Phase Two proposal remained the current source of truth and a direct check-in was sent to move the working session toward a first approved pilot.",
    goal: "Collect final feedback, confirm the first approved scope, and set the measurement contract before implementation begins.",
    kpis: [["Proposal", "12 pages", "Current Phase Two package"], ["Follow-up", "1", "Sent Aug 4"], ["Stakeholder group", "3", "Current recipient set"], ["First pilot", "Open", "Awaiting feedback"]],
    work: [
      "Kept the Phase Two growth proposal as the current NKCDC source of truth.",
      "Sent a direct follow-up on August 4 asking whether the team had reviewed the proposal.",
      "Preserved the coordinated options across SEO, GEO, Grants, social, outreach, webinar promotion, and measurement without presenting any lane as approved.",
      "Held implementation and budget decisions behind the working session and client approval.",
    ],
    analysis: [
      "This was a follow-up week rather than a production week. The proposal is complete and review-ready, while the next value is choosing one realistic pilot and a measurement owner.",
      "No new paid-media or implementation outcome is claimed. The report stays focused on stakeholder follow-up and the decision needed to move forward.",
    ],
    platforms: [
      { name: "Growth proposal", state: "Review-ready", note: "The Phase Two package remains the active planning asset. It combines owned search, outreach, and measurement options for client selection.", metrics: [["Pages", "12"], ["Options", "7"], ["Brand", "Updated"], ["Approval", "Open"]], rows: [["Phase Two proposal", "Ready", "—", "12 pages", "Feedback needed"], ["Pilot scope", "Pending", "—", "—", "Working session"]] },
      { name: "Paid and measurement", state: "Not activated", note: "No current Google or Meta campaign result is used as evidence for this weekly report. Measurement is part of the proposed scope and remains pending approval.", metrics: [["Google Ads", "Not current"], ["Meta Ads", "Not mapped"], ["Pilot", "Pending"], ["Measurement", "Pending"]], rows: [["Current platform read", "Not claimed", "—", "—", "No new delivery"], ["Measurement contract", "Proposed", "—", "—", "Owner needed"]] },
    ],
    outcome: { platform: "No new platform delivery metric was verified for Aug 3 to Aug 9.", business: "The first approved pilot, ownership, and downstream outcome definition remain open.", measurement: "Choose the first scope and measurement owner before treating any proposed channel as active work." },
    workstreams: [["Proposal", "Phase Two package and presentation", "Ready"], ["Follow-up", "Direct stakeholder check-in", "Sent"], ["Pilot", "First approved scope", "Open"], ["Measurement", "Owner and contract", "Pending"]],
    detailedWork: [["Proposal", "Kept the twelve-page Phase Two package as the active source of truth.", "Gives NKCDC one coordinated growth direction to review.", "Ready"], ["Follow-up", "Sent a direct check-in on Aug 4 to move the review forward.", "Creates a clear next action without assuming approval.", "Sent"], ["Scope", "Held SEO, GEO, Grants, outreach, social, and webinar options as proposed lanes.", "Keeps recommendations separate from approved implementation.", "Proposed"], ["Measurement", "Held the first-pilot measurement contract as an open decision.", "Prevents activity from outrunning ownership and proof.", "Pending"]],
    wins: ["The Phase Two package remains complete and review-ready.", "The follow-up put the next decision back in front of the stakeholder group."],
    augustFocus: ["Collect feedback on the proposal.", "Choose the first approved pilot, owners, and measurement path."],
    nextMoves: [["Review", "Anthony + NKCDC", "Confirm the proposal feedback and working-session timing", "Next contact"], ["Scope", "Momentum + NKCDC", "Choose one realistic first pilot", "After review"], ["Measure", "Joint team", "Set the owner and success definition", "Before implementation"]],
    sources: ["Gmail · NKCDC Phase Two proposal follow-up · Aug 4", "Canonical NKCDC Phase Two growth proposal and QA", "Gmail · NKCDC report draft", "Client registry and stakeholder routing", "No unambiguous Slack report handoff found for this window"],
  },
  {
    ...common,
    id: "bar-crawl-usa",
    client: "Bar Crawl USA",
    descriptor: "Seasonal event growth plan, GA4, and Semrush evidence",
    logo: "bar-crawl-usa.webp",
    logoBackground: "dark",
    accent: "#D8A85A",
    accentBright: "#F0C77A",
    status: "Weekly report rebuilt with separate seasonal plan and GA4/Semrush attachments",
    signal: "Bar Crawl's Aug 3 to Aug 9 work moved from maintenance into a seasonal operating plan: current event inventory was checked, analytics evidence was assembled, and the October and December growth system was rebuilt around confirmed demand windows.",
    goal: "Approve the seasonal sprint, repair event facts and tracking, and build the campaign-ready conversion and measurement system before activation.",
    kpis: [["Confirmed Oct listings", "12", "Live event inventory"], ["Confirmed Dec listings", "12", "Live event inventory"], ["Plan", "1", "Revised seasonal system"], ["Analysis", "1", "GA4 and Semrush PDF"]],
    work: [
      "Delivered the earlier weekly handoff and then rebuilt the seasonal plan around the client's October and December demand windows.",
      "Validated the current event inventory as twelve October listings and twelve December listings, with November treated as the runway.",
      "Produced the latest analytical GA4 and Semrush report to ground traffic, search, and measurement decisions.",
      "Separated the weekly activity report, revised seasonal plan, and analytical report so the client receives three distinct documents.",
    ],
    analysis: [
      "The latest source record changes the recommendation from generic maintenance to two defined seasonal growth sprints. The plan uses confirmed listings, existing media, city-level activation, lifecycle work, and ticket-path measurement.",
      "The current analytics report supports seasonal traffic and search analysis, but ticket revenue still needs tracking repair and a tested purchase path before revenue, CPA, or ROAS decisions are used.",
    ],
    platforms: [
      { name: "Seasonal growth system", state: "Plan ready · approval needed", note: "The revised plan covers twelve October and twelve December listings, two seasonal hubs, city-level Google Search, creative, lifecycle, partner, and measurement work.", metrics: [["Oct listings", "12"], ["Dec listings", "12"], ["Seasonal hubs", "2"], ["Approval", "Open"]], rows: [["October Halloween sprint", "Planned", "—", "12 listings", "Sep 21 launch window"], ["December Ugly Sweater sprint", "Planned", "—", "12 listings", "Nov runway"]] },
      { name: "GA4 and Semrush", state: "Analysis delivered · tracking repair open", note: "The analytical PDF records the current measurement position, prior seasonal traffic, channel quality, and search opportunities without claiming verified ticket revenue.", metrics: [["Report", "1"], ["GA4", "Reviewed"], ["Semrush", "Reviewed"], ["Revenue", "Pending"]], rows: [["Analytics evidence", "Delivered", "—", "PDF", "Source map"], ["Purchase path", "Pending", "—", "—", "Repair and test"]] },
    ],
    outcome: { platform: "No current Google Ads delivery is claimed for Aug 3 to Aug 9. The weekly work produced a revised seasonal system and a separate GA4/Semrush analytical read.", business: "Ticket revenue is not yet verified by the current measurement path.", measurement: "Repair tracking, validate event facts and ticket URLs, approve scope and budget, then measure ticket-path actions by city and event." },
    workstreams: [["Inventory", "October and December event map", "Verified"], ["Plan", "Revised seasonal growth system", "Ready"], ["Analytics", "GA4 and Semrush report", "Delivered"], ["Activation", "Budget, facts, links, and rights", "Open"]],
    detailedWork: [["Inventory", "Confirmed twelve October and twelve December listings and treated November as runway.", "Creates the correct seasonal operating perimeter.", "Verified"], ["Plan", "Rebuilt the October and December growth system around city, event, creative, lifecycle, and ticket-path work.", "Adds a measurable activation layer beyond maintenance SEO.", "Ready"], ["Analytics", "Produced the latest GA4 and Semrush analytical report.", "Grounds the next conversation in current traffic and search evidence.", "Delivered"], ["Weekly packet", "Kept the weekly report, revised plan, and analytical report separate.", "Gives Andy the right document for each decision.", "Delivered"]],
    augustScopeCallout: { value: "3 documents", title: "Bar Crawl USA delivery set", detail: "The client-safe packet separates the Aug 3 to Aug 9 weekly read, the revised October and December seasonal growth plan, and the analytical GA4 and Semrush report.", items: ["Weekly report", "Seasonal plan", "GA4 evidence", "Semrush evidence"] },
    wins: ["The seasonal plan now reflects confirmed October and December inventory.", "The latest analytics evidence is separated from the plan and weekly work report."],
    augustFocus: ["Approve the seasonal sprint and repair event facts, ticket links, and tracking.", "Build the activation system only after budget, media rights, and scope are confirmed."],
    nextMoves: [["Approve", "Andy + Momentum", "Confirm seasonal scope, budget, ticket facts, and rights", "By Aug 14"], ["Repair", "Web + analytics", "Fix source data and test the purchase path", "Before activation"], ["Build", "Momentum", "Create the campaign, creative, lifecycle, and city measurement system", "After approval"]],
    sources: ["Slack · #bar-crawl-usa · Aug 3 to Aug 5", "Latest GA4 and Semrush report · prepared Aug 9", "Revised October and December seasonal growth plan · communication review through Aug 9", "Gmail · Bar Crawl USA seasonal plan draft", "Live event inventory and client communication evidence"],
  },
  {
    ...common,
    id: "va-claims-edge",
    client: "VA Claims Edge",
    descriptor: "Phase Three schema, pipeline logic, and portal readiness",
    logo: "va-claims-edge.png",
    logoBackground: "light",
    accent: "#C94343",
    accentBright: "#F07474",
    status: "Phase Two remains live; Phase Three pipeline and schema decisions advanced",
    signal: "VA Claims Edge moved from a Phase Two review surface into Phase Three planning this week: the team clarified the seven-stage pipeline, ownership rules, booking inputs, portal subdomain, and compliance questions before real client data is introduced.",
    goal: "Align the approved pipeline and booking rules, complete the schema and backend changes, and instrument the production journey before real claimant data is used.",
    kpis: [["Pipeline stages", "7", "Updated model"], ["Booking rules", "4", "Still require alignment"], ["Portal domain", "1", "portal.vaclaimsedge.com"], ["Phase Three", "Planned", "Schema and pipeline"]],
    work: [
      "Kept the Phase Two weekly report and unified portal review as the current client-facing baseline.",
      "Reviewed David's latest process feedback and translated it into a formal seven-stage pipeline with owners and event-based advancement.",
      "Advanced the schema and pipeline change list, including stop-the-clock handling, stage ownership, alerts, appointments, and client self-registration.",
      "Confirmed the portal subdomain and kept compliance review visible before real claimant data enters the system.",
    ],
    analysis: [
      "This week's work was product and process alignment. The portal foundation is live, while the team is now making the underlying pipeline and booking rules match the approved business process.",
      "The next risk is not visual polish. It is rule alignment, compliance review, and production instrumentation before the system handles real claimant records.",
    ],
    platforms: [
      { name: "Portal and product", state: "Phase Two live · Phase Three planning", note: "The team advanced the seven-stage process, pipeline ownership, booking inputs, and portal routing while preserving the approved product surface.", metrics: [["Stages", "7"], ["Owners", "Defined"], ["Alerts", "Planned"], ["Subdomain", "Confirmed"]], rows: [["Pipeline view", "Updating", "—", "7 stages", "Owner logic"], ["Portal", "Live", "—", "Review surface", "Phase Two baseline"]] },
      { name: "Compliance and measurement", state: "Review required", note: "Security foundations are in place, but formal compliance review and production instrumentation remain open before real claimant data is used.", metrics: [["RLS", "Enabled"], ["HTTPS", "Enabled"], ["Compliance", "Open"], ["Analytics", "Next"]], rows: [["Secure foundation", "Verified", "—", "Protected routes", "Environment ready"], ["Real claimant data", "Held", "—", "Not introduced", "Review first"]] },
    ],
    outcome: { platform: "No paid-media metric is claimed for this weekly report. Product and process work are the verified evidence lanes.", business: "Booking completion and claimant-progress outcomes remain pending the approved rule set and real-data integration.", measurement: "Complete the pipeline and booking alignment, then instrument the verified production journey before using operational outcomes." },
    workstreams: [["Pipeline", "Seven-stage model and ownership rules", "Advanced"], ["Booking", "Four rule mismatches", "Open"], ["Portal", "Subdomain and Phase Two baseline", "Verified"], ["Compliance", "Pre-real-data review", "Open"]],
    detailedWork: [["Pipeline", "Translated feedback into a seven-stage, event-driven process with owners.", "Gives the portal and operations view one shared model.", "Advanced"], ["Booking", "Kept four booking-rule mismatches visible for alignment.", "Prevents the live journey from drifting from the approved process.", "Open"], ["Portal", "Confirmed portal.vaclaimsedge.com as the working route.", "Creates a clear review and production destination.", "Confirmed"], ["Compliance", "Held formal compliance review before real claimant data.", "Protects the transition from demo data to real operations.", "Open"]],
    wins: ["The pipeline is now described as seven owned stages.", "The portal route and production guardrails remain clear."],
    augustFocus: ["Align the seven-stage pipeline and four booking rules.", "Complete compliance and instrumentation checks before real claimant data."],
    nextMoves: [["Align", "David + team", "Confirm the seven-stage process and booking rules", "Next review"], ["Build", "Engineering", "Apply schema, appointments, alerts, and self-registration changes", "Phase Three"], ["Verify", "Web + compliance", "Complete production instrumentation and compliance review", "Before real data"]],
    sources: ["Slack · #va-claims · Aug 3 to Aug 6", "Latest unified portal review and Phase Two handoff", "David's process feedback summarized in Slack", "Portal subdomain confirmation", "Compliance and production-readiness notes"],
  },
  {
    ...common,
    id: "revive-systems",
    client: "Revive Systems",
    descriptor: "AEO, GEO, SEO content, and paid-readiness boundaries",
    logo: "revive-systems.png",
    logoBackground: "dark",
    accent: "#F06A3A",
    accentBright: "#FF9B6D",
    status: "Organic package handed off; publication and LSA route remain open",
    signal: "Revive's Aug 3 to Aug 9 record is a clean handoff week: the five-piece organic package, sitemap plan, and paid-readiness path were delivered, with the next question being publication and the LSA route.",
    goal: "Approve and publish the organic package, record the first visibility baseline, and confirm the exact paid route before activation.",
    kpis: [["Report handoff", "1", "Delivered Aug 3"], ["Content pieces", "5", "AEO, GEO, SEO cluster"], ["Acquisition package", "1", "Sitemap and organic path"], ["LSA route", "Open", "Needs confirmation"]],
    work: [
      "Delivered the Revive weekly report and August organic-growth plan on August 3.",
      "Kept the five-piece AEO, GEO, and SEO cluster visible as the current publication package.",
      "Preserved the organic acquisition and sitemap package as the next controlled release path.",
      "Held paid-media activation behind the exact account, pixel, LSA, and approval route rather than claiming current performance.",
    ],
    analysis: [
      "The weekly evidence supports a completed organic handoff, not a new live-campaign result. The content and sitemap package are ready for an organized review and publication sequence.",
      "The next useful measurement is a baseline of rankings, AI-search citations, and organic landing-page activity after publication. The LSA and paid route still need a clear owner.",
    ],
    platforms: [
      { name: "Organic acquisition", state: "Package ready · publication pending", note: "The five-piece content cluster and sitemap package are the current delivery lane. Publication and measured visibility remain separate states.", metrics: [["Articles", "5"], ["Sitemap", "Ready"], ["Baseline", "Next"], ["Publication", "Pending"]], rows: [["AEO / GEO / SEO cluster", "Complete", "—", "5 pieces", "Review"], ["Organic acquisition", "Ready", "—", "—", "Publish and measure"]] },
      { name: "Paid readiness", state: "Approval-gated", note: "No live Google or Meta performance metric is claimed. The exact paid route, pixel, LSA decision, and approval remain open.", metrics: [["Google Ads", "Not mapped"], ["Meta Ads", "Readiness"], ["Pixel", "Pending"], ["LSA", "Open"]], rows: [["Paid-media route", "Pending", "—", "No live KPI", "Map first"], ["Remarketing readiness", "Assessment", "—", "—", "Pixel check"]] },
    ],
    outcome: { platform: "No live paid-media platform metric was verified for Aug 3 to Aug 9.", business: "Organic rankings, citations, inquiries, and revenue remain pending publication and baseline measurement.", measurement: "Publish the approved package, record the initial organic baseline, and map the paid route before activation claims." },
    workstreams: [["Content", "Five-piece AEO / GEO / SEO cluster", "Handed off"], ["Organic", "Acquisition and sitemap package", "Ready"], ["Paid", "Ads and LSA readiness", "Approval-gated"], ["Measurement", "Visibility baseline", "Next"]],
    detailedWork: [["Report", "Delivered the weekly client-safe handoff on Aug 3.", "Gives the client a current view of the package without invented paid metrics.", "Delivered"], ["Content", "Kept the five-piece organic cluster as the active publication package.", "Creates a coherent answer-ready acquisition system.", "Ready"], ["Sitemap", "Preserved the acquisition and sitemap package for release.", "Connects content production to the public site path.", "Ready"], ["Paid readiness", "Held activation behind exact account, pixel, LSA, and approval mapping.", "Keeps readiness separate from live performance.", "Open"]],
    wins: ["The organic package is complete and ready for review.", "Paid readiness remains clearly separated from live performance claims."],
    augustFocus: ["Approve and publish the organic package.", "Confirm the LSA and paid-media route before activation."],
    nextMoves: [["Publish", "Revive + Momentum", "Approve and release the organic cluster and sitemap package", "Next read"], ["Baseline", "SEO", "Record rankings, citations, and organic landing-page signals", "After publish"], ["Map", "Paid media", "Confirm the exact paid and LSA route", "Before activation"]],
    sources: ["Slack · #revive-systems · Aug 3 report handoff", "Canonical AEO, GEO, and SEO cluster", "Organic acquisition and sitemap package", "Ads-readiness assessment", "Gmail · Revive report thread"],
  },
];

export const portfolio = reports.map((report) => ({ id: report.id, client: report.client, logo: report.logo, status: report.status }));
