[CmdletBinding()]
param([switch]$Detailed)

$ErrorActionPreference='Stop'
$projectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$checks=New-Object System.Collections.Generic.List[object]
$failed=$false
$tempRoot=Join-Path $env:TEMP ('marketing-os-tests-'+[guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($tempRoot)|Out-Null

function Add-Check{param([string]$Name,[bool]$Passed,[string]$Detail);$script:checks.Add([pscustomobject][ordered]@{name=$Name;passed=$Passed;detail=$Detail});if(-not$Passed){$script:failed=$true}}
function Invoke-Script{
    param([string]$ScriptPath,[string[]]$Arguments)
    $previousErrorPreference=$ErrorActionPreference
    try{
        $ErrorActionPreference='Continue'
        $output=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $ScriptPath @Arguments 2>&1
        $exitCode=$LASTEXITCODE
    }
    finally{$ErrorActionPreference=$previousErrorPreference}
    [pscustomobject]@{exitCode=$exitCode;output=($output-join[Environment]::NewLine)}
}
function Add-ExitCheck{param([string]$Name,$Result,[bool]$ShouldPass=$true);$pass=if($ShouldPass){$Result.exitCode-eq0}else{$Result.exitCode-ne0};$detail="exit={0}"-f$Result.exitCode;if(-not$pass-and-not[string]::IsNullOrWhiteSpace([string]$Result.output)){$detail+="; output={0}"-f([string]$Result.output)};Add-Check $Name $pass $detail}
function Write-Utf8Text{param([string]$Path,[string]$Text);$dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir)){[IO.Directory]::CreateDirectory($dir)|Out-Null};[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Write-Utf8Json{param([string]$Path,$Object);Write-Utf8Text $Path (($Object|ConvertTo-Json -Depth 100)+[Environment]::NewLine)}
function Copy-JsonObject{param($Object);return (($Object|ConvertTo-Json -Depth 100)|ConvertFrom-Json)}
function Read-JsonOutput{param($Result);try{return ($Result.output|ConvertFrom-Json)}catch{return $null}}

$queuePath=Join-Path $projectRoot 'queue\work-items.json'
$registryPath=Join-Path $projectRoot 'registry\clients.json'
$controlPath=Join-Path $projectRoot 'CONTROL.md'
$fixturePath=Join-Path $projectRoot 'tests\fixtures\valid-worker-handoff.json'
$queue=Get-Content -LiteralPath $queuePath -Raw -Encoding UTF8|ConvertFrom-Json
$registry=Get-Content -LiteralPath $registryPath -Raw -Encoding UTF8|ConvertFrom-Json

try{
    $jsonPaths=@(
        'queue\work-items.json','registry\clients.json','registry\paid-media-roster.json',
        'workflows\marketing-chief.workflow.json','workflows\marketing-chief-execution-graph.workflow.json','workflows\communication-triggered-ad-launch.workflow.json','workflows\daily-paid-media-optimization.workflow.json',
        'schemas\worker-handoff.schema.json','schemas\marketing-execution-graph.schema.json','schemas\design-contract.schema.json','schemas\ad-launch-request.schema.json','schemas\ad-launch-authority.schema.json','schemas\ad-provider-packet.schema.json','schemas\ad-provider-readiness.schema.json','schemas\paid-media-client-config.schema.json','schemas\paid-media-launch-blueprint.schema.json','schemas\paid-media-roster.schema.json',
        'clients\replenish-7-eleven\paid-media\launch-authority.json','clients\replenish-7-eleven\paid-media\launch-config.json','clients\replenish-7-eleven\paid-media\blueprints\google_ads.json',
        'clients\fresh-blends-kwik-trip\paid-media\launch-authority.json','clients\fresh-blends-kwik-trip\paid-media\launch-config.json','clients\fresh-blends-kwik-trip\paid-media\blueprints\google_ads.json',
        'clients\kimberly-james-bridal\paid-media\launch-authority.json','clients\kimberly-james-bridal\paid-media\launch-config.json','clients\kimberly-james-bridal\paid-media\blueprints\google_ads.json','clients\kimberly-james-bridal\paid-media\blueprints\meta_ads.json',
        'clients\omega-landscaping\paid-media\launch-authority.json','clients\omega-landscaping\paid-media\launch-config.json','clients\omega-landscaping\paid-media\blueprints\google_ads.json',
        'clients\onsite-concrete-landscape\paid-media\launch-authority.json','clients\onsite-concrete-landscape\paid-media\launch-config.json','clients\onsite-concrete-landscape\paid-media\blueprints\google_ads.json',
        'clients\fagan-painting\paid-media\launch-authority.json','clients\fagan-painting\paid-media\launch-config.json','clients\fagan-painting\paid-media\blueprints\meta_ads.json',
        'clients\shadow-heating-cooling\paid-media\launch-authority.json','clients\shadow-heating-cooling\paid-media\launch-config.json','clients\shadow-heating-cooling\paid-media\blueprints\meta_ads.json',
        'intake\index.json','state\intake-sync.json','state\system-health.json','state\task-continuity.json','state\access-coverage.json','state\ad-provider-readiness.json'
    )
    foreach ($path in $jsonPaths){
        $full=Join-Path $projectRoot $path
        try{[void](Get-Content -LiteralPath $full -Raw -Encoding UTF8|ConvertFrom-Json);Add-Check "json:$path" $true 'valid'}catch{Add-Check "json:$path" $false 'invalid-or-missing'}
    }
    foreach ($script in @(Get-ChildItem -LiteralPath $PSScriptRoot -Filter '*.ps1' -File)){
        $parseErrors=$null;[void][Management.Automation.Language.Parser]::ParseFile($script.FullName,[ref]$null,[ref]$parseErrors)
        Add-Check ("powershell-parse:{0}"-f$script.Name) (@($parseErrors).Count-eq0) ("errors={0}"-f@($parseErrors).Count)
    }
    foreach ($script in @(Get-ChildItem -LiteralPath (Join-Path $PSScriptRoot 'providers') -Filter '*.ps1' -File)){
        $parseErrors=$null;[void][Management.Automation.Language.Parser]::ParseFile($script.FullName,[ref]$null,[ref]$parseErrors)
        Add-Check ("powershell-parse:providers/{0}"-f$script.Name) (@($parseErrors).Count-eq0) ("errors={0}"-f@($parseErrors).Count)
    }

    Add-ExitCheck 'client-registry' (Invoke-Script (Join-Path $PSScriptRoot 'Test-ClientRegistry.ps1') @())
    Add-ExitCheck 'paid-media:daily-review-focused-suite' (Invoke-Script (Join-Path $projectRoot 'tests\Test-DailyPaidMediaReview.ps1') @())
    Add-ExitCheck 'execution-graph:focused-suite' (Invoke-Script (Join-Path $projectRoot 'tests\Test-MarketingExecutionGraph.ps1') @())
    $predictionResult=Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-Format','Json','-AsOf',[string]$queue.updatedAt)
    Add-ExitCheck 'next-action-predictor' $predictionResult
    $prediction=Read-JsonOutput $predictionResult
    $predictionProperties=@($prediction.PSObject.Properties.Name);Add-Check 'prediction:three-surfaces' ('nextAutomatic'-in$predictionProperties-and'nextDecision'-in$predictionProperties-and'nextUnblock'-in$predictionProperties) 'automatic-decision-unblock-surfaces-present-even-when-empty'

    $canonicalControlCheck=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @('-Check')
    Add-ExitCheck 'control:canonical-current' $canonicalControlCheck
    $directWriteWithoutRevision=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @()
    Add-ExitCheck 'control:direct-write-requires-revision' $directWriteWithoutRevision $false

    # Stable positive handoff fixture against an isolated queue snapshot.
    $handoffQueue=Copy-JsonObject $queue;$handoffQueue.revision=200;$handoffQueue.updatedAt='2026-07-16T06:00:00Z'
    $handoffItem=@($handoffQueue.workItems|Where-Object{$_.id-eq'wi-20260715-0003'})[0]
    $handoffItem.version=2;$handoffItem.status='ready';$handoffItem.outcome=$null;$handoffItem.approval.tier='automatic';$handoffItem.approval.status='not_required';$handoffItem.approval.approvalRef=$null
    $handoffQueuePath=Join-Path $tempRoot 'handoff\queue.json';$handoffControlPath=Join-Path $tempRoot 'handoff\CONTROL.md';Write-Utf8Json $handoffQueuePath $handoffQueue
    Add-ExitCheck 'handoff:positive-validation' (Invoke-Script (Join-Path $PSScriptRoot 'Test-MarketingHandoff.ps1') @('-HandoffPath',$fixturePath,'-QueuePath',$handoffQueuePath,'-RegistryPath',$registryPath,'-Format','Json'))
    Add-ExitCheck 'handoff:positive-accept-dry-run' (Invoke-Script (Join-Path $PSScriptRoot 'Accept-WorkerHandoff.ps1') @('-HandoffPath',$fixturePath,'-QueuePath',$handoffQueuePath,'-ControlPath',$handoffControlPath,'-RegistryPath',$registryPath,'-ExpectedQueueRevision','200','-DryRun'))

    $baseHandoff=Get-Content -LiteralPath $fixturePath -Raw -Encoding UTF8|ConvertFrom-Json
    $negativeHandoffs=@(
        @{name='unsafe-id';edit={param($h)$h.handoffId='../escape'}},
        @{name='failed-to-done';edit={param($h)$h.status='failed';$h.proposedTransition='done'}},
        @{name='artifact-escape';edit={param($h)$h.artifacts=@('context/DESIGN_STANDARD.md')}},
        @{name='unsafe-evidence';edit={param($h)$h.evidence=@('password: REDACTED')}},
        @{name='phone';edit={param($h)$h.summary='Call 555-123-4567 for verification.'}},
        @{name='stale-version';edit={param($h)$h.expectedWorkItemVersion=999}}
    )
    foreach ($case in $negativeHandoffs){$h=Copy-JsonObject $baseHandoff;&$case.edit $h;$path=Join-Path $tempRoot ("handoff\negative-{0}.json"-f$case.name);Write-Utf8Json $path $h;Add-ExitCheck ("handoff:reject-{0}"-f$case.name) (Invoke-Script (Join-Path $PSScriptRoot 'Test-MarketingHandoff.ps1') @('-HandoffPath',$path,'-QueuePath',$handoffQueuePath,'-RegistryPath',$registryPath,'-Format','Json')) $false}
    $pendingQueue=Copy-JsonObject $handoffQueue;$pendingItem=@($pendingQueue.workItems|Where-Object{$_.id-eq'wi-20260715-0003'})[0];$pendingItem.status='needs_approval';$pendingItem.approval.tier='explicit';$pendingItem.approval.status='pending';$pendingQueuePath=Join-Path $tempRoot 'handoff\pending-queue.json';Write-Utf8Json $pendingQueuePath $pendingQueue
    $pendingHandoff=Copy-JsonObject $baseHandoff;$pendingHandoff.status='completed';$pendingHandoff.proposedTransition='verification';$pendingHandoff.approvalGate='none';$pendingHandoffPath=Join-Path $tempRoot 'handoff\pending-bypass.json';Write-Utf8Json $pendingHandoffPath $pendingHandoff
    Add-ExitCheck 'handoff:reject-pending-approval-bypass' (Invoke-Script (Join-Path $PSScriptRoot 'Test-MarketingHandoff.ps1') @('-HandoffPath',$pendingHandoffPath,'-QueuePath',$pendingQueuePath,'-RegistryPath',$registryPath,'-Format','Json')) $false

    # Queue mutation approval, completion, action-class, and WIP guards.
    $hope=@($queue.workItems|Where-Object{$_.id-eq'wi-20260715-0001'})[0]
    Add-ExitCheck 'queue:update-dry-run' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-WorkItemId',$hope.id,'-ExpectedQueueRevision',[string]$queue.revision,'-ExpectedWorkItemVersion',[string]$hope.version,'-Priority',[string]$hope.priority.level,'-DryRun'))
    Add-ExitCheck 'queue:reject-pending-approval-bypass' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-WorkItemId',$hope.id,'-ExpectedQueueRevision',[string]$queue.revision,'-ExpectedWorkItemVersion',[string]$hope.version,'-Status','in_progress','-DryRun')) $false
    $nkcdc=@($queue.workItems|Where-Object{$_.id-eq'wi-20260715-0003'})[0]
    Add-ExitCheck 'queue:reject-risky-automatic-text' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-WorkItemId',$nkcdc.id,'-ExpectedQueueRevision',[string]$queue.revision,'-ExpectedWorkItemVersion',[string]$nkcdc.version,'-NextAction','Send the deck to the client.','-ActionClass','local_artifact','-DryRun')) $false

    $doneQueue=Copy-JsonObject $queue;$doneQueue.revision=301;$doneItem=@($doneQueue.workItems|Where-Object{$_.id-eq'wi-20260715-0003'})[0];$doneItem.version=20;$doneItem.status='verification';$doneItem.outcome=$null;$doneQueuePath=Join-Path $tempRoot 'queue\done.json';$doneControl=Join-Path $tempRoot 'queue\done-control.md';Write-Utf8Json $doneQueuePath $doneQueue
    Add-ExitCheck 'queue:reject-done-without-outcome' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-QueuePath',$doneQueuePath,'-ControlPath',$doneControl,'-RegistryPath',$registryPath,'-WorkItemId',$doneItem.id,'-ExpectedQueueRevision','301','-ExpectedWorkItemVersion','20','-Status','done','-DryRun')) $false
    Add-ExitCheck 'queue:reject-empty-outcome' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-QueuePath',$doneQueuePath,'-ControlPath',$doneControl,'-RegistryPath',$registryPath,'-WorkItemId',$doneItem.id,'-ExpectedQueueRevision','301','-ExpectedWorkItemVersion','20','-Status','done','-OutcomeSummary','   ','-DryRun')) $false
    $doneItem.outcome=[pscustomobject]@{status='ready';summary='Old unverified note.';verifiedAt='2026-07-16T05:00:00Z'};Write-Utf8Json $doneQueuePath $doneQueue
    Add-ExitCheck 'queue:reject-stale-unverified-outcome' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-QueuePath',$doneQueuePath,'-ControlPath',$doneControl,'-RegistryPath',$registryPath,'-WorkItemId',$doneItem.id,'-ExpectedQueueRevision','301','-ExpectedWorkItemVersion','20','-Status','done','-DryRun')) $false

    $emergencyQueue=Copy-JsonObject $queue;$emergencyQueue.revision=401;$target=@($emergencyQueue.workItems|Where-Object{$_.id-eq'wi-20260715-0003'})[0];$target.version=30;$target.status='ready';$target.outcome=$null;$target.lane='emergency';$target.priority.level='P0';$target|Add-Member -NotePropertyName emergencyRationale -NotePropertyValue 'Time-critical local recovery test.' -Force
    $active=Copy-JsonObject $target;$active.id='wi-test-emergency-active';$active.version=1;$active.status='in_progress';$emergencyQueue.workItems=@($emergencyQueue.workItems)+$active;$emergencyQueuePath=Join-Path $tempRoot 'queue\emergency.json';$emergencyControl=Join-Path $tempRoot 'queue\emergency-control.md';Write-Utf8Json $emergencyQueuePath $emergencyQueue
    Add-ExitCheck 'wip:reject-second-emergency' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-QueuePath',$emergencyQueuePath,'-ControlPath',$emergencyControl,'-RegistryPath',$registryPath,'-WorkItemId',$target.id,'-ExpectedQueueRevision','401','-ExpectedWorkItemVersion','30','-Status','in_progress','-DryRun')) $false
    $emergencyQueue.workItems=@($emergencyQueue.workItems|Where-Object{$_.id-ne'wi-test-emergency-active'});Write-Utf8Json $emergencyQueuePath $emergencyQueue
    Add-ExitCheck 'wip:allow-first-emergency' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingQueue.ps1') @('-QueuePath',$emergencyQueuePath,'-ControlPath',$emergencyControl,'-RegistryPath',$registryPath,'-WorkItemId',$target.id,'-ExpectedQueueRevision','401','-ExpectedWorkItemVersion','30','-Status','in_progress','-DryRun'))

    $newArgs=@('-Client','NKCDC','-DedupeKey','fixture:nkcdc:test-only','-Title','Fixture capture','-RequestedOutcome','Prove exact routing and stale-safe capture.','-SourceType','user','-SourceLocator','fixture://local','-SourceSummary','Synthetic redacted test observation.','-Priority','P3','-PriorityRationale','Test only.','-NextAction','Validate without committing.','-ActionClass','local_test','-DefinitionOfDone','Dry run returns a routed work item.','-ExpectedQueueRevision',[string]$queue.revision,'-DryRun')
    Add-ExitCheck 'queue:new-work-dry-run' (Invoke-Script (Join-Path $PSScriptRoot 'New-MarketingWorkItem.ps1') $newArgs)
    $dedupeArgs=@('-Client','NKCDC','-DedupeKey',('  '+[string]$nkcdc.dedupeKey.ToUpperInvariant()+'  '),'-Title','Duplicate fixture','-RequestedOutcome','Reject normalized duplicate state.','-SourceType','user','-SourceLocator','fixture://local','-SourceSummary','Synthetic redacted test observation.','-Priority','P3','-PriorityRationale','Test only.','-NextAction','Validate without committing.','-ActionClass','local_test','-DefinitionOfDone','Duplicate is rejected.','-ExpectedQueueRevision',[string]$queue.revision,'-DryRun')
    Add-ExitCheck 'queue:reject-normalized-dedupe' (Invoke-Script (Join-Path $PSScriptRoot 'New-MarketingWorkItem.ps1') $dedupeArgs) $false

    # System-state evidence refresh is stale-safe, atomic, version-preserving, and audited.
    $systemQueue=Copy-JsonObject $queue;$systemQueue.revision=601;$systemQueue.updatedAt='2026-07-16T12:45:00Z';$systemFixtureItem=@($systemQueue.systemBacklog|Where-Object{$_.id-eq'sys-20260716-0004'})[0];$systemFixtureItem.status='blocked';$systemFixtureItem.risk='Synthetic blocked access state for transaction testing.';$systemFixtureItem|Add-Member -NotePropertyName nextAction -NotePropertyValue 'Run the isolated system-state transaction fixture.' -Force;if($null-ne$systemFixtureItem.PSObject.Properties['result']){$systemFixtureItem.PSObject.Properties.Remove('result')}
    $systemRoot=Join-Path $tempRoot 'system-state';$systemQueuePath=Join-Path $systemRoot 'queue.json';$systemControlPath=Join-Path $systemRoot 'CONTROL.md';$systemBackupRoot=Join-Path $systemRoot 'backups';$systemMutationLog=Join-Path $systemRoot 'queue-mutations.jsonl';$systemHealthPath=Join-Path $projectRoot 'state\system-health.json';Write-Utf8Json $systemQueuePath $systemQueue
    Add-ExitCheck 'system-state:initial-control-render' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @('-QueuePath',$systemQueuePath,'-OutputPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-AsOf',[string]$systemQueue.updatedAt,'-InternalRender'))
    $systemRisk='Secure bootstrap is present and the open vault identity still requires confirmation before exact item mapping.'
    $systemNextAction='Confirm the primary vault identity, then map exact bw://item/<guid> locators without reading secret values.'
    $systemVaultState='primary-bitwarden-secure-bootstrap-present-chrome-extension-open-identity-unverified-exact-guid-mapping-pending'
    $systemBridgeState='v1.1.2-locked-bootstrap-present-no-secret-output'
    $systemArgs=@('-SystemBacklogId','sys-20260716-0004','-ExpectedQueueRevision','601','-Risk',$systemRisk,'-NextAction',$systemNextAction,'-CredentialVaultState',$systemVaultState,'-CredentialBridgeState',$systemBridgeState,'-QueuePath',$systemQueuePath,'-ControlPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-BackupRoot',$systemBackupRoot,'-MutationLogPath',$systemMutationLog)
    $queueHashBefore=(Get-FileHash -LiteralPath $systemQueuePath -Algorithm SHA256).Hash;$controlHashBefore=(Get-FileHash -LiteralPath $systemControlPath -Algorithm SHA256).Hash
    $systemDryRun=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($systemArgs+@('-DryRun'));Add-ExitCheck 'system-state:dry-run' $systemDryRun;$systemDryRunJson=Read-JsonOutput $systemDryRun
    Add-Check 'system-state:dry-run-contract' ($systemDryRunJson.status-eq'would-update'-and[int]$systemDryRunJson.priorQueueRevision-eq601-and[int]$systemDryRunJson.queueRevision-eq602-and[bool]$systemDryRunJson.clientWorkItemVersionsPreserved) ([string]$systemDryRun.output)
    $queueHashAfter=(Get-FileHash -LiteralPath $systemQueuePath -Algorithm SHA256).Hash;$controlHashAfter=(Get-FileHash -LiteralPath $systemControlPath -Algorithm SHA256).Hash
    Add-Check 'system-state:dry-run-no-write' ($queueHashBefore-ceq$queueHashAfter-and$controlHashBefore-ceq$controlHashAfter-and-not(Test-Path -LiteralPath $systemMutationLog)-and-not(Test-Path -LiteralPath $systemBackupRoot)) 'queue-control-log-backup-unchanged'
    $staleSystemArgs=@($systemArgs);$staleSystemArgs[[array]::IndexOf($staleSystemArgs,'-ExpectedQueueRevision')+1]='600';Add-ExitCheck 'system-state:reject-stale-revision' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($staleSystemArgs+@('-DryRun'))) $false
    $missingSystemArgs=@($systemArgs);$missingSystemArgs[[array]::IndexOf($missingSystemArgs,'-SystemBacklogId')+1]='sys-missing-item';Add-ExitCheck 'system-state:reject-missing-id' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($missingSystemArgs+@('-DryRun'))) $false
    $unsafeSystemArgs=@($systemArgs);$unsafeSystemArgs[[array]::IndexOf($unsafeSystemArgs,'-Risk')+1]='password: REDACTED';Add-ExitCheck 'system-state:reject-unsafe-text' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($unsafeSystemArgs+@('-DryRun'))) $false
    $duplicateSystemQueue=Copy-JsonObject $systemQueue;$duplicateSystemQueue.systemBacklog=@($duplicateSystemQueue.systemBacklog)+(Copy-JsonObject (@($duplicateSystemQueue.systemBacklog|Where-Object{$_.id-eq'sys-20260716-0004'})[0]));$duplicateSystemQueuePath=Join-Path $systemRoot 'duplicate-queue.json';Write-Utf8Json $duplicateSystemQueuePath $duplicateSystemQueue
    $duplicateSystemArgs=@($systemArgs);$duplicateSystemArgs[[array]::IndexOf($duplicateSystemArgs,'-QueuePath')+1]=$duplicateSystemQueuePath;Add-ExitCheck 'system-state:reject-duplicate-id' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($duplicateSystemArgs+@('-DryRun'))) $false

    $clientVersionsBefore=@($systemQueue.workItems|ForEach-Object{'{0}:{1}'-f$_.id,[int]$_.version})-join'|'
    $systemUpdate=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') $systemArgs;Add-ExitCheck 'system-state:isolated-update' $systemUpdate;$systemUpdateJson=Read-JsonOutput $systemUpdate;$updatedSystemQueue=Get-Content -LiteralPath $systemQueuePath -Raw -Encoding UTF8|ConvertFrom-Json;$updatedSystemItem=@($updatedSystemQueue.systemBacklog|Where-Object{$_.id-eq'sys-20260716-0004'})[0];$clientVersionsAfter=@($updatedSystemQueue.workItems|ForEach-Object{'{0}:{1}'-f$_.id,[int]$_.version})-join'|'
    Add-Check 'system-state:root-only-version-increment' ([int]$updatedSystemQueue.revision-eq602-and$clientVersionsBefore-ceq$clientVersionsAfter-and[bool]$systemUpdateJson.clientWorkItemVersionsPreserved) ("revision={0};versions={1}"-f$updatedSystemQueue.revision,$clientVersionsAfter)
    Add-Check 'system-state:truthful-blocked-refresh' ($updatedSystemItem.status-eq'blocked'-and$updatedSystemItem.risk-eq$systemRisk-and$updatedSystemItem.nextAction-eq$systemNextAction-and$updatedSystemQueue.systemHealth.credentialVault-eq$systemVaultState-and$updatedSystemQueue.systemHealth.credentialBridge-eq$systemBridgeState) ([string]$updatedSystemItem.status)
    Add-ExitCheck 'system-state:paired-control-current' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @('-QueuePath',$systemQueuePath,'-OutputPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-Check'))
    $backupPath=[string]$systemUpdateJson.backup;$backupValid=-not[string]::IsNullOrWhiteSpace($backupPath)-and(Test-Path -LiteralPath (Join-Path $backupPath 'work-items.json') -PathType Leaf)-and(Test-Path -LiteralPath (Join-Path $backupPath 'CONTROL.md') -PathType Leaf);Add-Check 'system-state:backup-created' $backupValid $backupPath
    $systemMutation=if(Test-Path -LiteralPath $systemMutationLog){Get-Content -LiteralPath $systemMutationLog -Tail 1|ConvertFrom-Json}else{$null};Add-Check 'system-state:audit-recorded' ($null-ne$systemMutation-and$systemMutation.action-eq'system-state-update'-and$systemMutation.systemBacklogId-eq'sys-20260716-0004'-and$systemMutation.priorSystemBacklogStatus-eq'blocked'-and$systemMutation.systemBacklogStatus-eq'blocked'-and[int]$systemMutation.priorQueueRevision-eq601-and[int]$systemMutation.queueRevision-eq602-and-not[bool]$systemMutation.externalActionTaken) ([string]$systemMutation.action)

    $systemCompletionResult='Authorized client access is operational through exact non-secret routes. Retired-account remediation remains explicitly deferred by the owner.'
    $systemDoneArgs=@('-SystemBacklogId','sys-20260716-0004','-ExpectedQueueRevision','602','-TargetStatus','done','-Result',$systemCompletionResult,'-CredentialVaultState','primary-vault-operational-secondary-remediation-deferred','-CredentialBridgeState',$systemBridgeState,'-QueuePath',$systemQueuePath,'-ControlPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-BackupRoot',$systemBackupRoot,'-MutationLogPath',$systemMutationLog)
    $missingDoneResultArgs=@('-SystemBacklogId','sys-20260716-0004','-ExpectedQueueRevision','602','-TargetStatus','done','-CredentialVaultState','primary-vault-operational-secondary-remediation-deferred','-CredentialBridgeState',$systemBridgeState,'-QueuePath',$systemQueuePath,'-ControlPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-BackupRoot',$systemBackupRoot,'-MutationLogPath',$systemMutationLog,'-DryRun');Add-ExitCheck 'system-state:reject-done-without-result' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') $missingDoneResultArgs) $false
    $unsafeDoneArgs=@($systemDoneArgs);$unsafeDoneArgs[[array]::IndexOf($unsafeDoneArgs,'-Result')+1]='password: REDACTED';Add-ExitCheck 'system-state:reject-unsafe-result' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($unsafeDoneArgs+@('-DryRun'))) $false
    $invalidDoneStatusArgs=@($systemDoneArgs);$invalidDoneStatusArgs[[array]::IndexOf($invalidDoneStatusArgs,'-TargetStatus')+1]='deferred';Add-ExitCheck 'system-state:reject-unsupported-target-status' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($invalidDoneStatusArgs+@('-DryRun'))) $false
    $doneQueueHashBefore=(Get-FileHash -LiteralPath $systemQueuePath -Algorithm SHA256).Hash;$doneControlHashBefore=(Get-FileHash -LiteralPath $systemControlPath -Algorithm SHA256).Hash;$systemDoneDryRun=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($systemDoneArgs+@('-DryRun'));Add-ExitCheck 'system-state:done-dry-run' $systemDoneDryRun;$systemDoneDryRunJson=Read-JsonOutput $systemDoneDryRun
    Add-Check 'system-state:done-dry-run-contract' ($systemDoneDryRunJson.priorSystemBacklogStatus-eq'blocked'-and$systemDoneDryRunJson.systemBacklogStatus-eq'done'-and[int]$systemDoneDryRunJson.priorQueueRevision-eq602-and[int]$systemDoneDryRunJson.queueRevision-eq603) ([string]$systemDoneDryRun.output)
    Add-Check 'system-state:done-dry-run-no-write' ($doneQueueHashBefore-ceq(Get-FileHash -LiteralPath $systemQueuePath -Algorithm SHA256).Hash-and$doneControlHashBefore-ceq(Get-FileHash -LiteralPath $systemControlPath -Algorithm SHA256).Hash) 'queue-and-control-unchanged'
    $clientVersionsBeforeDone=@($updatedSystemQueue.workItems|ForEach-Object{'{0}:{1}'-f$_.id,[int]$_.version})-join'|';$systemDone=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') $systemDoneArgs;Add-ExitCheck 'system-state:done-update' $systemDone;$systemDoneJson=Read-JsonOutput $systemDone;$completedSystemQueue=Get-Content -LiteralPath $systemQueuePath -Raw -Encoding UTF8|ConvertFrom-Json;$completedSystemItem=@($completedSystemQueue.systemBacklog|Where-Object{$_.id-eq'sys-20260716-0004'})[0];$clientVersionsAfterDone=@($completedSystemQueue.workItems|ForEach-Object{'{0}:{1}'-f$_.id,[int]$_.version})-join'|'
    Add-Check 'system-state:truthful-done-shape' ($completedSystemItem.status-eq'done'-and$completedSystemItem.result-eq$systemCompletionResult-and$null-eq$completedSystemItem.risk-and$null-eq$completedSystemItem.PSObject.Properties['nextAction']) ([string]$completedSystemItem.status)
    Add-Check 'system-state:done-root-only-version-increment' ([int]$completedSystemQueue.revision-eq603-and$clientVersionsBeforeDone-ceq$clientVersionsAfterDone-and[bool]$systemDoneJson.clientWorkItemVersionsPreserved) ("revision={0};versions={1}"-f$completedSystemQueue.revision,$clientVersionsAfterDone)
    Add-ExitCheck 'system-state:done-paired-control-current' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @('-QueuePath',$systemQueuePath,'-OutputPath',$systemControlPath,'-HealthPath',$systemHealthPath,'-Check'))
    $doneBackupPath=[string]$systemDoneJson.backup;$doneBackupValid=-not[string]::IsNullOrWhiteSpace($doneBackupPath)-and(Test-Path -LiteralPath (Join-Path $doneBackupPath 'work-items.json') -PathType Leaf)-and(Test-Path -LiteralPath (Join-Path $doneBackupPath 'CONTROL.md') -PathType Leaf);Add-Check 'system-state:done-backup-created' $doneBackupValid $doneBackupPath
    $doneMutation=Get-Content -LiteralPath $systemMutationLog -Tail 1|ConvertFrom-Json;Add-Check 'system-state:done-audit-recorded' ($doneMutation.priorSystemBacklogStatus-eq'blocked'-and$doneMutation.systemBacklogStatus-eq'done'-and[int]$doneMutation.priorQueueRevision-eq602-and[int]$doneMutation.queueRevision-eq603-and-not[bool]$doneMutation.externalActionTaken) ([string]$doneMutation.systemBacklogStatus)
    $repeatDoneArgs=@($systemDoneArgs);$repeatDoneArgs[[array]::IndexOf($repeatDoneArgs,'-ExpectedQueueRevision')+1]='603';Add-ExitCheck 'system-state:reject-repeat-done' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemState.ps1') ($repeatDoneArgs+@('-DryRun'))) $false

    # Predictor fails closed and feedback changes behavior rather than only scores.
    $asOf='2026-07-16T07:00:00Z';$predictQueue=Copy-JsonObject $queue;$predictQueue.revision=500;$predictQueue.updatedAt=$asOf;$predictItem=Copy-JsonObject $nkcdc;$predictItem.version=77;$predictItem.status='ready';$predictItem.lane='normal';$predictItem.nextAction='Review the local artifact against the brief.';$predictItem.routing.status='resolved';$predictItem.routing.registryStatus='active';$predictItem.routing.verifiedAt=$asOf;$predictItem.evidence.asOf=$asOf;$predictItem.evidence.freshness='current';$predictItem.evidence.refs=@('clients/nkcdc/CLIENT.md');$predictItem.approval.tier='automatic';$predictItem.approval.status='not_required';$predictItem.execution.actionClass='local_artifact';$predictItem.execution.automaticEligible=$true;$predictItem.execution.externalAction=$false;$predictItem.execution.reversible=$true;$predictQueue.workItems=@($predictItem);$predictQueuePath=Join-Path $tempRoot 'predictor\queue.json';$feedbackPath=Join-Path $tempRoot 'predictor\feedback.jsonl';Write-Utf8Json $predictQueuePath $predictQueue;Write-Utf8Text $feedbackPath ''
    $basePrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'))
    Add-Check 'predictor:eligible-safe-local' ($basePrediction.nextAutomatic.workItemId-eq$predictItem.id) ([string]$basePrediction.nextAutomatic.workItemId)
    $portfolioQueue=Copy-JsonObject $predictQueue;$vaItem=Copy-JsonObject $predictItem;$vaItem.id='wi-portfolio-va';$vaItem.clientId='va-claims-edge';$vaItem.title='Equal safe VA work';$vaItem.routing.registryStatus='active';$bercosItem=Copy-JsonObject $predictItem;$bercosItem.id='wi-portfolio-bercos';$bercosItem.clientId='bercos-popcorn';$bercosItem.title='Equal safe Bercos work';$bercosItem.routing.registryStatus='active';$portfolioQueue.workItems=@($bercosItem,$vaItem);$portfolioQueuePath=Join-Path $tempRoot 'predictor\portfolio-queue.json';Write-Utf8Json $portfolioQueuePath $portfolioQueue;$portfolioPrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$portfolioQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'predictor:portfolio-priority-orders-equal-safe-work' ($portfolioPrediction.nextAutomatic.workItemId-eq'wi-portfolio-va'-and$portfolioPrediction.nextAutomatic.portfolioTier-eq'critical'-and[int]$portfolioPrediction.nextAutomatic.portfolioRank-eq2-and[int]$portfolioPrediction.nextAutomatic.portfolioWeight-eq80) ("selected={0};rank={1};weight={2}"-f$portfolioPrediction.nextAutomatic.workItemId,$portfolioPrediction.nextAutomatic.portfolioRank,$portfolioPrediction.nextAutomatic.portfolioWeight)
    $inactiveQueue=Copy-JsonObject $predictQueue;$inactiveItem=Copy-JsonObject $predictItem;$inactiveItem.id='wi-portfolio-inactive';$inactiveItem.clientId='zen-spa-tropicana';$inactiveQueue.workItems=@($inactiveItem);$inactiveQueuePath=Join-Path $tempRoot 'predictor\inactive-queue.json';Write-Utf8Json $inactiveQueuePath $inactiveQueue;$inactivePrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$inactiveQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'predictor:inactive-client-never-automatic' ($null-eq$inactivePrediction.nextAutomatic-and$inactivePrediction.nextUnblock.workItemId-eq'wi-portfolio-inactive'-and$null-eq$inactivePrediction.nextUnblock.portfolioRank) ([string]$inactivePrediction.nextUnblock.why)
    foreach ($badApproval in @('rejected','garbled')){$q=Copy-JsonObject $predictQueue;$q.workItems[0].approval.status=$badApproval;$p=Join-Path $tempRoot ("predictor\approval-$badApproval.json");Write-Utf8Json $p $q;$r=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$p,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check ("predictor:reject-approval-$badApproval") ($null-eq$r.nextAutomatic) 'no-automatic'}
    $badLane=Copy-JsonObject $predictQueue;$badLane.workItems[0].lane='other';$badLanePath=Join-Path $tempRoot 'predictor\bad-lane.json';Write-Utf8Json $badLanePath $badLane;$badLaneResult=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$badLanePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'predictor:reject-invalid-lane' ($null-eq$badLaneResult.nextAutomatic) 'no-automatic'
    $risky=Copy-JsonObject $predictQueue;$risky.workItems[0].nextAction='Send the artifact to the client.';$riskyPath=Join-Path $tempRoot 'predictor\risky.json';Write-Utf8Json $riskyPath $risky;$riskyResult=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$riskyPath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'predictor:reject-risky-automatic' ($null-eq$riskyResult.nextAutomatic) 'no-automatic'
    $feedbackBase=[ordered]@{schemaVersion=2;recordedAt=$asOf;workItemId=$predictItem.id;workItemVersion=77;predictionLane='automatic';predictedAction=$predictItem.nextAction;replacementAction=$null}
    $rejectFeedback=[pscustomobject](Copy-JsonObject $feedbackBase);$rejectFeedback|Add-Member decision reject;Write-Utf8Text $feedbackPath (($rejectFeedback|ConvertTo-Json -Compress)+[Environment]::NewLine);$rejectResult=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'feedback:reject-suppresses' ($null-eq$rejectResult.nextAutomatic-and@($rejectResult.suppressed).Count-eq1) 'suppressed-until-version-change'
    $changedVersion=Copy-JsonObject $predictQueue;$changedVersion.workItems[0].version=78;$changedPath=Join-Path $tempRoot 'predictor\changed-version.json';Write-Utf8Json $changedPath $changedVersion;$changedResult=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$changedPath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'feedback:version-change-reenables' ($changedResult.nextAutomatic.workItemId-eq$predictItem.id) 'automatic-restored'
    $modifyFeedback=[pscustomobject](Copy-JsonObject $feedbackBase);$modifyFeedback|Add-Member decision modify;$modifyFeedback.replacementAction='Upload the artifact to the client Drive.';Write-Utf8Text $feedbackPath (($modifyFeedback|ConvertTo-Json -Compress)+[Environment]::NewLine);$modifyResult=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'feedback:modify-requires-reclassification' ($null-eq$modifyResult.nextAutomatic-and@($modifyResult.pendingModifications).Count-eq1) 'held-for-queue-update'
    $acceptFeedback=[pscustomobject](Copy-JsonObject $feedbackBase);$acceptFeedback|Add-Member decision accept;Write-Utf8Text $feedbackPath (($acceptFeedback|ConvertTo-Json -Compress)+[Environment]::NewLine);$acceptPrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'feedback:accept-adjusts-score' ([double]$acceptPrediction.nextAutomatic.score-eq([double]$basePrediction.nextAutomatic.score+10)) ("score={0}"-f$acceptPrediction.nextAutomatic.score)

    $deferredQueue=Copy-JsonObject $predictQueue;$deferredQueue.workItems[0].status='deferred';$deferredQueue.workItems[0].approval.tier='explicit';$deferredQueue.workItems[0].approval.status='pending';$deferredQueuePath=Join-Path $tempRoot 'predictor\deferred.json';Write-Utf8Json $deferredQueuePath $deferredQueue;Write-Utf8Text $feedbackPath '';$deferredPrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$deferredQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'predictor:deferred-never-surfaces-from-stale-approval' ($null-eq$deferredPrediction.nextAutomatic-and$null-eq$deferredPrediction.nextDecision-and$null-eq$deferredPrediction.nextUnblock-and@($deferredPrediction.ranked).Count-eq0) 'no-active-lane'
    $acceptPriorLines=for($i=1;$i-le3;$i++){([ordered]@{schemaVersion=3;recordedAt=$asOf;workItemId=("wi-history-accept-$i");workItemVersion=1;clientId='nkcdc';predictionLane='automatic';actionClass='local_artifact';decision='accept';predictedAction='Historical local artifact action.'}|ConvertTo-Json -Compress)};Write-Utf8Text $feedbackPath (($acceptPriorLines-join[Environment]::NewLine)+[Environment]::NewLine);$acceptPriorPrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'learning:three-comparable-accepts-boost-future-score' ([int]$acceptPriorPrediction.nextAutomatic.learnedSampleCount-eq3-and[int]$acceptPriorPrediction.nextAutomatic.learnedAdjustment-eq9-and[double]$acceptPriorPrediction.nextAutomatic.score-eq([double]$basePrediction.nextAutomatic.score+9)) ("samples={0};adjustment={1}"-f$acceptPriorPrediction.nextAutomatic.learnedSampleCount,$acceptPriorPrediction.nextAutomatic.learnedAdjustment)
    $rejectPriorLines=for($i=1;$i-le3;$i++){([ordered]@{schemaVersion=3;recordedAt=$asOf;workItemId=("wi-history-reject-$i");workItemVersion=1;clientId='nkcdc';predictionLane='automatic';actionClass='local_artifact';decision='reject';predictedAction='Historical local artifact action.'}|ConvertTo-Json -Compress)};Write-Utf8Text $feedbackPath (($rejectPriorLines-join[Environment]::NewLine)+[Environment]::NewLine);$rejectPriorPrediction=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-NextActions.ps1') @('-QueuePath',$predictQueuePath,'-RegistryPath',$registryPath,'-FeedbackPath',$feedbackPath,'-AsOf',$asOf,'-Format','Json'));Add-Check 'learning:three-comparable-rejects-lower-future-score' ([int]$rejectPriorPrediction.nextAutomatic.learnedSampleCount-eq3-and[int]$rejectPriorPrediction.nextAutomatic.learnedAdjustment-eq-10-and[double]$rejectPriorPrediction.nextAutomatic.score-eq([double]$basePrediction.nextAutomatic.score-10)) ("samples={0};adjustment={1}"-f$rejectPriorPrediction.nextAutomatic.learnedSampleCount,$rejectPriorPrediction.nextAutomatic.learnedAdjustment)
    $decisionLedger=Join-Path $tempRoot 'learning\prediction-outcomes.jsonl';$decisionResult=Invoke-Script (Join-Path $PSScriptRoot 'Record-MarketingDecision.ps1') @('-QueuePath',$predictQueuePath,'-WorkItemId',$predictItem.id,'-PredictionLane','automatic','-Decision','accept','-SourceChannel','slack','-TriggerClass','location_launch','-OutcomeClass','approved_execution','-LedgerPath',$decisionLedger);Add-ExitCheck 'learning:decision-v3-recorded' $decisionResult;$decisionEntry=(Get-Content -LiteralPath $decisionLedger -Encoding UTF8|Select-Object -First 1)|ConvertFrom-Json;Add-Check 'learning:decision-v3-comparable-fields' ([int]$decisionEntry.schemaVersion-eq3-and$decisionEntry.actionClass-eq'local_artifact'-and$decisionEntry.sourceChannel-eq'slack'-and$decisionEntry.triggerClass-eq'location_launch'-and$decisionEntry.outcomeClass-eq'approved_execution'-and-not[bool]$decisionEntry.containsSecrets-and-not[bool]$decisionEntry.containsDirectIdentifiers-and-not[bool]$decisionEntry.containsRawCommunications) 'redacted-comparable-outcome'
    $learningSummary=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Get-PredictionLearning.ps1') @('-LedgerPath',$decisionLedger,'-Format','Json'));Add-Check 'learning:summary-requires-three-samples' ([int]$learningSummary.totalOutcomes-eq1-and@($learningSummary.patterns).Count-eq1-and-not[bool]$learningSummary.patterns[0].eligible) 'one-sample-not-active'

    # Communication-triggered ad launches build locally, then fail closed outside an exact active authority envelope.
    $adAsOf=[DateTimeOffset]::UtcNow.ToString('o');$adDryRun=Invoke-Script (Join-Path $PSScriptRoot 'New-AdLaunchRequest.ps1') @('-ClientId','replenish-7-eleven','-SourceChannel','user','-SourceLocator','user-instruction:ad-launch-test','-RequesterRef','user:dillon','-Platform','google_ads','-LocationKey','store-101','-LocationLabel','Store 101 Philadelphia','-Objective','Generate direction intent visits for the approved location.','-ConversionEvent','directions_click','-UtmCampaign','replenish_store_101','-DailyBudget','50','-TotalBudget','500','-CurrentEvidenceAt',$adAsOf,'-ObservedAt',$adAsOf,'-DryRun');Add-ExitCheck 'ad-launch:new-request-dry-run' $adDryRun;$adRequest=(Read-JsonOutput $adDryRun).request;$adRequest.accountRefs=@('access-broker:googleads/replenish/primary');$adRequest.landingPage.artifactRef='clients/replenish-7-eleven/paid-media/landing-pages/store-101';$adRequest.landingPage.destinationRef='deployment:netlify/replenish-locations';$adRequest.state='qa';$adRequestPath=Join-Path $tempRoot 'ad-launch\request.json';Write-Utf8Json $adRequestPath $adRequest;$adRequestFingerprint=([string](& (Join-Path $PSScriptRoot 'Get-AdLaunchRequestFingerprint.ps1') -RequestPath $adRequestPath -Format Plain)).Trim()
    $draftAuthorityPath=Join-Path $projectRoot 'clients\replenish-7-eleven\paid-media\launch-authority.json';$draftValidation=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Test-AdLaunchRequest.ps1') @('-RequestPath',$adRequestPath,'-AuthorityPath',$draftAuthorityPath,'-AsOf',$asOf,'-Format','Json','-AllowFixturePaths'));Add-Check 'ad-launch:draft-authority-allows-local-build-only' ([bool]$draftValidation.validRequest-and[bool]$draftValidation.readyForLocalBuild-and-not[bool]$draftValidation.launchConfig.accountRoutingReady-and-not[bool]$draftValidation.readyForPausedCreate-and-not[bool]$draftValidation.readyToEnable-and$draftValidation.status-eq'ready_for_local_build') ([string]$draftValidation.status)
    $activeAuthority=Get-Content -LiteralPath $draftAuthorityPath -Raw -Encoding UTF8|ConvertFrom-Json;$activeAuthority.status='active';$activeAuthority.allowedAccountRefs=@('access-broker:googleads/replenish/primary');$activeAuthority.permissions.deployLandingPage=$true;$activeAuthority.permissions.createPausedObjects=$true;$activeAuthority.permissions.enableCampaigns=$true;$activeAuthority.permissions.adjustBudget=$true;$activeAuthority.limits.maxDailyPerCampaign=100;$activeAuthority.limits.maxTotalPerRequest=1000;$activeAuthority.limits.maxLocationsPerRequest=10;$activeAuthority.approvedBy='dillon';$activeAuthority.approvedAt='2026-07-16T06:00:00Z';$activeAuthority.expiresAt='2026-08-16T06:00:00Z';$activeAuthority.approvalRef='user-instruction:ad-launch-authority-test';$activeAuthorityPath=Join-Path $tempRoot 'ad-launch\active-authority.json';Write-Utf8Json $activeAuthorityPath $activeAuthority
    $readyProvider=[ordered]@{schemaVersion=1;observedAt=[DateTimeOffset]::UtcNow.ToString('o');providers=[ordered]@{google_ads=[ordered]@{status='ready';verifiedCapabilities=@('fixture');blockers=@();requiresLiveProbe=$false};meta_ads=[ordered]@{status='ready';verifiedCapabilities=@('fixture');blockers=@();requiresLiveProbe=$false}};landingPageDeployment=[ordered]@{staging=[ordered]@{status='ready';verifiedCapabilities=@('fixture');blockers=@();requiresLiveProbe=$false};production=[ordered]@{status='ready';verifiedCapabilities=@('fixture');blockers=@();requiresLiveProbe=$false}};privacy='redacted';containsSecrets=$false;containsDirectIdentifiers=$false};$readyProviderPath=Join-Path $tempRoot 'ad-launch\provider-ready.json';Write-Utf8Json $readyProviderPath $readyProvider
    $canonicalLaunchConfigPath=Join-Path $projectRoot 'clients\replenish-7-eleven\paid-media\launch-config.json';$activeLaunchConfig=Get-Content -LiteralPath $canonicalLaunchConfigPath -Raw -Encoding UTF8|ConvertFrom-Json;$activeLaunchConfig.platforms.google_ads.exactAccountRef='access-broker:googleads/replenish/primary';$activeLaunchConfig.platforms.google_ads.exactAccountIdSha256='d2d02ea74de2c9fab1d802db969c18d409a8663a9697977bb1c98ccdd9de4372';$activeLaunchConfig.platforms.google_ads.executionSurface='provider_api';$activeLaunchConfig.landingPage.stagingDeploymentRef='deployment:netlify/replenish-locations';$activeLaunchConfig.landingPage.status='ready';$activeLaunchConfigPath=Join-Path $tempRoot 'ad-launch\active-launch-config.json';Write-Utf8Json $activeLaunchConfigPath $activeLaunchConfig
    $activeValidation=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Test-AdLaunchRequest.ps1') @('-RequestPath',$adRequestPath,'-AuthorityPath',$activeAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-AsOf',$adAsOf,'-Format','Json','-AllowFixturePaths'));Add-Check 'ad-launch:active-bounded-authority-enables-terminal-lanes' ([bool]$activeValidation.launchConfig.accountRoutingReady-and[bool]$activeValidation.readyForDeploy-and[bool]$activeValidation.readyForPausedCreate-and[bool]$activeValidation.readyToEnable-and$activeValidation.status-eq'ready_to_enable') ([string]$activeValidation.status)
    $runtimeRoot=Join-Path $tempRoot 'ad-launch-runtime';[IO.Directory]::CreateDirectory($runtimeRoot)|Out-Null;$providerPacketPath=Join-Path $runtimeRoot 'packet.json';$providerPacket=[ordered]@{schemaVersion=1;requestId=$adRequest.requestId;requestFingerprint=$adRequestFingerprint;createdAt=$adAsOf;platform='google_ads';exactAccountRef='access-broker:googleads/replenish/primary';executionSurface='provider_api';operations=[ordered]@{validate=@([ordered]@{toolSlug='GOOGLEADS_MUTATE_CAMPAIGNS';account='access-broker:googleads/replenish/primary';arguments=[ordered]@{customer_id='1111111111';validate_only=$true;operations=@([ordered]@{operation_type='create';create=[ordered]@{name='Fixture';status='paused';campaign_budget='customers/1111111111/campaignBudgets/2222222222'}})}});createPaused=@([ordered]@{toolSlug='GOOGLEADS_MUTATE_CAMPAIGNS';account='access-broker:googleads/replenish/primary';arguments=[ordered]@{customer_id='1111111111';validate_only=$false;operations=@([ordered]@{operation_type='create';create=[ordered]@{name='Fixture';status='paused';campaign_budget='customers/1111111111/campaignBudgets/2222222222'}})}});enable=@([ordered]@{toolSlug='GOOGLEADS_MUTATE_CAMPAIGNS';account='access-broker:googleads/replenish/primary';arguments=[ordered]@{customer_id='1111111111';validate_only=$false;operations=@([ordered]@{operation_type='update';update=[ordered]@{resource_name='customers/1111111111/campaigns/3333333333';status='enabled'}})}});readback=@([ordered]@{toolSlug='GOOGLEADS_GET_CAMPAIGN_BY_ID';account='access-broker:googleads/replenish/primary';arguments=[ordered]@{customer_id='1111111111';id='3333333333'}})};containsSecrets=$false};Write-Utf8Json $providerPacketPath $providerPacket
    $fakeAdapter=Join-Path $tempRoot 'ad-launch\fake-provider.ps1';Write-Utf8Text $fakeAdapter "param([string]`$PacketPath,[string]`$Phase,[string]`$OutputPath)`n`$result=[ordered]@{successful=`$true;phase=`$Phase}|ConvertTo-Json -Compress`n[IO.Directory]::CreateDirectory((Split-Path -Parent `$OutputPath))|Out-Null`n[IO.File]::WriteAllText(`$OutputPath,`$result+[Environment]::NewLine,[Text.UTF8Encoding]::new(`$false))`n`$result`n"
    Add-ExitCheck 'ad-launch:terminal-validate-adapter-contract' (Invoke-Script (Join-Path $PSScriptRoot 'Invoke-AdLaunch.ps1') @('-RequestPath',$adRequestPath,'-Mode','Validate','-ProviderPacketPath',$providerPacketPath,'-AuthorityPath',$draftAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-ProviderAdapterPath',$fakeAdapter,'-RuntimeRoot',$runtimeRoot,'-AllowFixturePaths'))
    Add-ExitCheck 'ad-launch:terminal-create-paused-under-active-envelope' (Invoke-Script (Join-Path $PSScriptRoot 'Invoke-AdLaunch.ps1') @('-RequestPath',$adRequestPath,'-Mode','CreatePaused','-ProviderPacketPath',$providerPacketPath,'-AuthorityPath',$activeAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-ProviderAdapterPath',$fakeAdapter,'-RuntimeRoot',$runtimeRoot,'-AllowFixturePaths'))
    Add-ExitCheck 'ad-launch:terminal-readback-after-paused-create' (Invoke-Script (Join-Path $PSScriptRoot 'Invoke-AdLaunch.ps1') @('-RequestPath',$adRequestPath,'-Mode','Readback','-ProviderPacketPath',$providerPacketPath,'-AuthorityPath',$activeAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-ProviderAdapterPath',$fakeAdapter,'-RuntimeRoot',$runtimeRoot,'-AllowFixturePaths'))
    Add-ExitCheck 'ad-launch:terminal-enable-under-active-envelope' (Invoke-Script (Join-Path $PSScriptRoot 'Invoke-AdLaunch.ps1') @('-RequestPath',$adRequestPath,'-Mode','Enable','-ProviderPacketPath',$providerPacketPath,'-AuthorityPath',$activeAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-ProviderAdapterPath',$fakeAdapter,'-RuntimeRoot',$runtimeRoot,'-AllowFixturePaths'))
    Add-ExitCheck 'ad-launch:reject-create-paused-under-draft-envelope' (Invoke-Script (Join-Path $PSScriptRoot 'Invoke-AdLaunch.ps1') @('-RequestPath',$adRequestPath,'-Mode','CreatePaused','-ProviderPacketPath',$providerPacketPath,'-AuthorityPath',$draftAuthorityPath,'-LaunchConfigPath',$activeLaunchConfigPath,'-ProviderReadinessPath',$readyProviderPath,'-ProviderAdapterPath',$fakeAdapter,'-RuntimeRoot',$runtimeRoot,'-AllowFixturePaths')) $false

    $correctionLedger=Join-Path $tempRoot 'learning\corrections.jsonl'
    $canonicalCorrectionsResult=Invoke-Script (Join-Path $PSScriptRoot 'Get-MarketingCorrections.ps1') @('-Format','Json');Add-ExitCheck 'learning:canonical-ledger-valid' $canonicalCorrectionsResult
    $canonicalCorrections=Read-JsonOutput $canonicalCorrectionsResult
    $canonicalLegacy=@($canonicalCorrections.items|Where-Object{[int]$_.schemaVersion-eq1})
    Add-Check 'learning:legacy-six-lessons-preserved' ($canonicalLegacy.Count-eq6-and@($canonicalLegacy|Where-Object{[string]::IsNullOrWhiteSpace([string]$_.recordedAt)-or[string]::IsNullOrWhiteSpace([string]$_.summary)-or[string]::IsNullOrWhiteSpace([string]$_.lesson)-or$_.replacementRule-ne$_.lesson}).Count-eq0) ("legacy={0}"-f$canonicalLegacy.Count)
    $supersedingCorrection=@($canonicalLegacy|Where-Object{$_.correctionId-eq'corr-20260716-0005'})
    Add-Check 'learning:legacy-precedence-preserved' ($supersedingCorrection.Count-eq1-and$supersedingCorrection[0].supersedes-eq'corr-20260715-0001') ([string]$supersedingCorrection[0].supersedes)
    $legacyFixture=Get-Content -LiteralPath (Join-Path $projectRoot 'state\corrections.jsonl') -Encoding UTF8|Select-Object -First 1|ConvertFrom-Json
    foreach($legacyCase in @(
        @{name='source';edit={param($e)$e.signalSource='arbitrary_source'}},
        @{name='trigger';edit={param($e)$e.triggerRef='Call 555-123-4567'}},
        @{name='lesson';edit={param($e)$e.lesson='password: REDACTED'}},
        @{name='client-id';edit={param($e)$e.appliesTo.clientIds=@('person@example.com')}}
    )){$entry=Copy-JsonObject $legacyFixture;&$legacyCase.edit $entry;$legacyBadPath=Join-Path $tempRoot ("learning\legacy-bad-{0}.jsonl"-f$legacyCase.name);Write-Utf8Text $legacyBadPath (($entry|ConvertTo-Json -Compress -Depth 20)+[Environment]::NewLine);Add-ExitCheck ("learning:reject-unsafe-legacy-{0}"-f$legacyCase.name) (Invoke-Script (Join-Path $PSScriptRoot 'Get-MarketingCorrections.ps1') @('-LedgerPath',$legacyBadPath,'-Format','Json')) $false}
    $correctionPositive=Invoke-Script (Join-Path $PSScriptRoot 'Record-MarketingCorrection.ps1') @('-Category','voice','-Source','user_decision','-Lesson','Use the shorter direct opening for this channel.','-ReplacementRule','Lead with the requested outcome in the first sentence.','-ClientId','nkcdc','-WorkItemId',$nkcdc.id,'-EvidenceLocator','context/DILLON_VOICE.md','-LedgerPath',$correctionLedger)
    Add-ExitCheck 'learning:correction-recorded' $correctionPositive
    $correctionEntry=(Get-Content -LiteralPath $correctionLedger -Encoding UTF8|Select-Object -First 1)|ConvertFrom-Json
    Add-Check 'learning:correction-schema-redacted' ([int]$correctionEntry.schemaVersion-eq2-and$correctionEntry.privacy-eq'redacted'-and-not$correctionEntry.containsSecrets-and-not$correctionEntry.containsDirectIdentifiers-and-not$correctionEntry.containsRawCommunications) 'v2-redacted-fixed-flags'
    Add-ExitCheck 'learning:v2-ledger-readable' (Invoke-Script (Join-Path $PSScriptRoot 'Get-MarketingCorrections.ps1') @('-LedgerPath',$correctionLedger,'-Format','Json'))
    Add-ExitCheck 'learning:reject-secret-correction' (Invoke-Script (Join-Path $PSScriptRoot 'Record-MarketingCorrection.ps1') @('-Category','process','-Source','incident','-Lesson','password: REDACTED','-LedgerPath',(Join-Path $tempRoot 'learning\bad-secret.jsonl'))) $false
    Add-ExitCheck 'learning:reject-direct-identifier' (Invoke-Script (Join-Path $PSScriptRoot 'Record-MarketingCorrection.ps1') @('-Category','process','-Source','incident','-Lesson','Call 555-123-4567 next time.','-LedgerPath',(Join-Path $tempRoot 'learning\bad-phone.jsonl'))) $false
    Add-ExitCheck 'learning:reject-actor-injection' (Invoke-Script (Join-Path $PSScriptRoot 'Record-MarketingDecision.ps1') @('-WorkItemId',$nkcdc.id,'-PredictionLane','automatic','-Decision','accept','-Actor','password: REDACTED','-LedgerPath',(Join-Path $tempRoot 'learning\bad-actor.jsonl'))) $false

    # Intake is retrievable, source-bound, recurrence-safe, and race guarded.
    $pendingResult=Invoke-Script (Join-Path $PSScriptRoot 'Get-PendingIntake.ps1') @('-AsJson');Add-ExitCheck 'intake:list-safe' $pendingResult;$pending=Read-JsonOutput $pendingResult
    $locatorsSafe=@($pending.items|Where-Object{$_.sourceLocator-notmatch'^agent-os-run:[A-Za-z0-9][A-Za-z0-9_-]{5,79}/task\.json$'}).Count-eq0
    Add-Check 'intake:retrievable-safe-locators' $locatorsSafe ("count={0}"-f$pending.count)
    Add-ExitCheck 'intake:sync-dry-run' (Invoke-Script (Join-Path $PSScriptRoot 'Sync-AgentOsIntake.ps1') @('-DryRun','-Quiet'))
    $intakeRoot=Join-Path $tempRoot 'intake-positive';[IO.Directory]::CreateDirectory((Join-Path $intakeRoot 'registry'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $intakeRoot 'queue'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $intakeRoot 'intake'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $intakeRoot 'state'))|Out-Null;Copy-Item $registryPath (Join-Path $intakeRoot 'registry\clients.json')
    $intakeIndex=Get-Content -LiteralPath (Join-Path $projectRoot 'intake\index.json') -Raw -Encoding UTF8|ConvertFrom-Json;$targetIntake=Copy-JsonObject (@($intakeIndex.items|Where-Object{$_.clientId-eq'fagan-painting'}|Select-Object -First 1)[0]);$targetIntake.triageState='pending';$targetIntake.promotedWorkItemId=$null;$targetIntake.resolvedAtUtc=$null;$targetIntake.resolutionAction=$null;$intakeIndex.items=@($targetIntake);$intakeIndex.generatedAtUtc='2026-07-16T07:05:00.000Z';Write-Utf8Json (Join-Path $intakeRoot 'intake\index.json') $intakeIndex;Write-Utf8Text (Join-Path $intakeRoot 'intake\summary.md') ''
    $boundQueue=Copy-JsonObject $queue;$boundItem=Copy-JsonObject (@($boundQueue.workItems|Where-Object{$_.id-eq'wi-20260715-0002'})[0]);$boundQueue.workItems=@($boundItem);Write-Utf8Json (Join-Path $intakeRoot 'queue\work-items.json') $boundQueue;Add-ExitCheck 'intake:reject-unrelated-same-client-promotion' (Invoke-Script (Join-Path $PSScriptRoot 'Resolve-IntakeObservation.ps1') @('-CanonicalRoot',$intakeRoot,'-MutexName',('Global\CodexMarketingOsTest'+[guid]::NewGuid().ToString('N')),'-IntakeId',$targetIntake.intakeId,'-Action','promote','-WorkItemId',$boundItem.id,'-ExpectedIndexGeneratedAtUtc','2026-07-16T07:05:00.000Z','-WhatIf')) $false;$boundItem.source.locator=$targetIntake.sourceLocator;$boundQueue.workItems=@($boundItem);Write-Utf8Json (Join-Path $intakeRoot 'queue\work-items.json') $boundQueue
    $resolvePositive=Invoke-Script (Join-Path $PSScriptRoot 'Resolve-IntakeObservation.ps1') @('-CanonicalRoot',$intakeRoot,'-MutexName',('Global\CodexMarketingOsTest'+[guid]::NewGuid().ToString('N')),'-IntakeId',$targetIntake.intakeId,'-Action','promote','-WorkItemId',$boundItem.id,'-ExpectedIndexGeneratedAtUtc','2026-07-16T07:05:00.000Z');Add-ExitCheck 'intake:source-bound-promotion' $resolvePositive;$resolvedIndex=Get-Content -LiteralPath (Join-Path $intakeRoot 'intake\index.json') -Raw|ConvertFrom-Json;Add-Check 'intake:promotion-persisted' ($resolvedIndex.items[0].triageState-eq'resolved'-and$resolvedIndex.items[0].promotedWorkItemId-eq$boundItem.id) 'resolved-and-linked'

    $recRoot=Join-Path $tempRoot 'intake-recurrence';$runs=Join-Path $recRoot 'runs';[IO.Directory]::CreateDirectory((Join-Path $recRoot 'registry'))|Out-Null;Copy-Item $registryPath (Join-Path $recRoot 'registry\clients.json');$now=[DateTimeOffset]::UtcNow;$occurrences=@(@{id='run-old001';at=$now.AddHours(-100)},@{id='run-new001';at=$now.AddHours(-1)},@{id='run-new002';at=$now.AddMinutes(-30)});$seq=0;foreach ($occ in $occurrences){$seq++;$dir=Join-Path $runs $occ.id;[IO.Directory]::CreateDirectory($dir)|Out-Null;$task=[ordered]@{created_at=$occ.at.ToString('o');job_id=("job-$seq");event_key=("gmail:test-$seq");client='Fagan Painting';client_alias='Fagan';requested_output='Prepare the recurring weekly local report.';safe_execution='local_deliverable_only';route='reporting'};Write-Utf8Json (Join-Path $dir 'task.json') $task}
    $recSync=Invoke-Script (Join-Path $PSScriptRoot 'Sync-AgentOsIntake.ps1') @('-SourceRunsPath',$runs,'-CanonicalRoot',$recRoot,'-InitialLookbackHours','168','-SemanticDedupeHours','72','-MutexName',('Global\CodexMarketingOsRecurrence'+[guid]::NewGuid().ToString('N')),'-Quiet');Add-ExitCheck 'intake:recurrence-sync' $recSync;$recIndex=Get-Content -LiteralPath (Join-Path $recRoot 'intake\index.json') -Raw|ConvertFrom-Json;Add-Check 'intake:recurrence-retained-after-window' (@($recIndex.items).Count-eq2-and[int]$recIndex.lastRun.semanticDuplicates-eq1) ("items={0};suppressed={1}"-f@($recIndex.items).Count,$recIndex.lastRun.semanticDuplicates)

    $bridgeIntakeRoot=Join-Path $tempRoot 'intake-bridge-identity';$bridgeRuns=Join-Path $bridgeIntakeRoot 'runs';[IO.Directory]::CreateDirectory((Join-Path $bridgeIntakeRoot 'registry'))|Out-Null;Copy-Item $registryPath (Join-Path $bridgeIntakeRoot 'registry\clients.json');$bridgeNow=[DateTimeOffset]::UtcNow
    $bridgeLegacyDir=Join-Path $bridgeRuns 'run-bridge-legacy';[IO.Directory]::CreateDirectory($bridgeLegacyDir)|Out-Null;$bridgeLegacyTask=[ordered]@{created_at=$bridgeNow.AddMinutes(-2).ToString('o');job_id='bridge-legacy';event_key='gmail:legacy-bridge-label';client='Bridge';client_alias='Bridge';requested_output='Prepare an unrelated newsletter summary.';safe_execution='local_deliverable_only';route='content'};Write-Utf8Json (Join-Path $bridgeLegacyDir 'task.json') $bridgeLegacyTask
    $bridgeExactDir=Join-Path $bridgeRuns 'run-bridge-exact';[IO.Directory]::CreateDirectory($bridgeExactDir)|Out-Null;$bridgeExactTask=[ordered]@{created_at=$bridgeNow.AddMinutes(-1).ToString('o');job_id='bridge-exact';event_key='slack:bridge-exact-source';client='Bridge';client_alias='Bridge Software';source_identity_keys=@('slack-channel:bridge-software-development');requested_output='Prepare the current local milestone checklist.';safe_execution='local_deliverable_only';route='project'};Write-Utf8Json (Join-Path $bridgeExactDir 'task.json') $bridgeExactTask
    $bridgeSync=Invoke-Script (Join-Path $PSScriptRoot 'Sync-AgentOsIntake.ps1') @('-SourceRunsPath',$bridgeRuns,'-CanonicalRoot',$bridgeIntakeRoot,'-InitialLookbackHours','24','-SemanticDedupeHours','72','-MutexName',('Global\CodexMarketingOsBridge'+[guid]::NewGuid().ToString('N')),'-Quiet');Add-ExitCheck 'intake:bridge-exact-source-guard' $bridgeSync;$bridgeIndex=Get-Content -LiteralPath (Join-Path $bridgeIntakeRoot 'intake\index.json') -Raw|ConvertFrom-Json;$bridgeQuarantine=@($bridgeIndex.items|Where-Object{$_.triageState-eq'quarantined'-and$_.quarantineReason-eq'exact-source-identity-required'});$bridgePending=@($bridgeIndex.items|Where-Object{$_.triageState-eq'pending'-and$_.clientId-eq'bridge-software'});Add-Check 'intake:bridge-label-only-quarantined' ($bridgeQuarantine.Count-eq1) ("quarantined={0}"-f$bridgeQuarantine.Count);Add-Check 'intake:bridge-exact-source-accepted' ($bridgePending.Count-eq1) ("pending={0}"-f$bridgePending.Count)

    # Access state is live, timestamp-fresh, and reviewed-code integrity bound.
    $coverageTemp=Join-Path $tempRoot 'access-registry.json'
    $coverageDoc=[ordered]@{clients=@(
        [ordered]@{id='fagan-painting';systems=@(
            [ordered]@{last_verified_at='2026-07-16T06:00:00Z';secret_ref='bw://item/00000000-0000-4000-8000-000000000001'},
            [ordered]@{last_verified_at='2025-01-01T00:00:00Z';secret_ref='bw://item/00000000-0000-4000-8000-000000000002'},
            [ordered]@{last_verified_at='not-a-date';secret_ref='bw://item/00000000-0000-4000-8000-000000000003'},
            [ordered]@{last_verified_at='2026-07-17T00:00:00Z';secret_ref='bw://item/00000000-0000-4000-8000-000000000004'}
        )},
        [ordered]@{id='bar-crawl-usa';systems=@([ordered]@{last_verified_at=$null;secret_ref='bw://item/00000000-0000-4000-8000-000000000005'})},
        [ordered]@{id='dillon-operations';systems=@(
            [ordered]@{id='bitwarden-password-manager';service='bitwarden';account_role='primary-codex-and-claude-client-vault';chrome_extension_state='installed-and-vault-open-in-persistent-chrome-account-identity-unverified'},
            [ordered]@{id='bitwarden-secondary-dillon-account';service='bitwarden';account_role='secondary-bitwarden-account';auth_method='disabled-retired-route';access_state='retired-by-owner-do-not-use';use_policy='prohibited-sole-authorized-vault-is-pollotharuler';allowed_capabilities=@();prohibited_capabilities=@('authentication.login','vault.autofill','credential.reference.read');retired_at='2026-07-16T06:30:00Z';remediation_status='deferred-by-owner';remediation_deferred_at='2026-07-16T06:45:00Z'}
        )}
    )};Write-Utf8Json $coverageTemp $coverageDoc
    $coverageStateTemp=Join-Path $tempRoot 'access-coverage.json';$coverageResult=Invoke-Script (Join-Path $PSScriptRoot 'Update-AccessCoverage.ps1') @('-OutputPath',$coverageStateTemp,'-AccessRegistryPath',$coverageTemp,'-AsOf','2026-07-16T07:00:00Z','-VerificationFreshnessDays','30');Add-ExitCheck 'access-coverage:timestamp-validation' $coverageResult;$coverage=Read-JsonOutput $coverageResult;Add-Check 'access-coverage:fresh-stale-invalid-separated' ([int]$coverage.summary.verifiedSystemCount-eq1-and[int]$coverage.summary.staleVerificationCount-eq1-and[int]$coverage.summary.invalidVerificationCount-eq2) ("fresh={0};stale={1};invalid={2}"-f$coverage.summary.verifiedSystemCount,$coverage.summary.staleVerificationCount,$coverage.summary.invalidVerificationCount)
    $singleSystemCoverage=@($coverage.clients|Where-Object{$_.clientId-eq'bar-crawl-usa'});Add-Check 'access-coverage:single-system-count' ($singleSystemCoverage.Count-eq1-and[int]$singleSystemCoverage[0].systemCount-eq1) ("rows={0};systems={1}"-f$singleSystemCoverage.Count,$singleSystemCoverage[0].systemCount)
    $hopeCoverage=@($coverage.clients|Where-Object{$_.clientId-eq'hope-wellness-center'});Add-Check 'access-coverage:explicit-not-required' ($hopeCoverage.Count-eq1-and-not[bool]$hopeCoverage[0].accessMappingRequired-and$hopeCoverage[0].coverageState-eq'not-required') ("rows={0};required={1};state={2}"-f$hopeCoverage.Count,$hopeCoverage[0].accessMappingRequired,$hopeCoverage[0].coverageState)
    Add-Check 'access-coverage:primary-vault-identity-gate' ($coverage.credentialVault.primaryVaultIdentityStatus-eq'unverified'-and$coverage.humanGate-match'primary Codex/Claude vault'-and$coverage.humanGate-notmatch'(?i)unlock|enrollment') ([string]$coverage.humanGate)
    $secondaryCoverage=$coverage.credentialVault.secondaryRoute;Add-Check 'access-coverage:secondary-route-state-propagated' ([int]$secondaryCoverage.routeCount-eq1-and$secondaryCoverage.id-eq'bitwarden-secondary-dillon-account'-and$secondaryCoverage.authMethod-eq'disabled-retired-route'-and$secondaryCoverage.accessState-eq'retired-by-owner-do-not-use'-and$secondaryCoverage.usePolicy-eq'prohibited-sole-authorized-vault-is-pollotharuler'-and[int]$secondaryCoverage.allowedCapabilityCount-eq0-and@($secondaryCoverage.prohibitedCapabilities).Count-eq3-and$secondaryCoverage.remediationStatus-eq'deferred-by-owner'-and$secondaryCoverage.remediationDeferredAt-eq'2026-07-16T06:45:00Z') ([string]$secondaryCoverage.accessState)
    $fakeBridge=Join-Path $tempRoot 'fake-bridge.ps1';Write-Utf8Text $fakeBridge "param([string]`$Operation)`n'{\"state\":\"unlocked\"}'`n"
    $healthMismatch=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge);Add-ExitCheck 'health:hash-mismatch-probe' $healthMismatch;$healthMismatchJson=Read-JsonOutput $healthMismatch;Add-Check 'health:refuse-unreviewed-bridge' (-not[bool]$healthMismatchJson.credentialBridge.integrityVerified-and$healthMismatchJson.credentialBridge.securityReview-eq'unverified-integrity-mismatch') ([string]$healthMismatchJson.credentialBridge.securityReview)
    $completedAccess=Join-Path $tempRoot 'completed-access-broker.ps1';Write-Utf8Text $completedAccess "param([string]`$Action)`n'{\"status\":\"valid\"}'`n"
    $healthCompleted=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$coverageStateTemp,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:completed-external-probe' $healthCompleted;$healthCompletedJson=Read-JsonOutput $healthCompleted;Add-Check 'health:completed-probe-exit-preserved' ([bool]$healthCompletedJson.accessBroker.valid-and-not[bool]$healthCompletedJson.accessBroker.timedOut) 'valid-non-timeout-exit-zero'
    $identityGateSet=@($healthCompletedJson.humanGates);$deferredActionSet=@($healthCompletedJson.deferredActions);Add-Check 'health:identity-confirmation-replaces-unlock' ('bitwarden_primary_vault_identity_confirmation'-in$identityGateSet-and'bitwarden_chrome_extension_unlock'-notin$identityGateSet-and'active_client_exact_bw_item_mapping'-in$identityGateSet-and'exact_bw_item_locator_mapping'-notin$identityGateSet-and'bitwarden_extension_timeout_policy_verification'-in$identityGateSet) ($identityGateSet-join',')
    Add-Check 'health:exact-retired-secondary-route-is-deferred' ('secondary_exposed_password_rotation'-notin$identityGateSet-and'secondary_exposed_password_rotation'-in$deferredActionSet) ("gates={0};deferred={1}"-f($identityGateSet-join','),($deferredActionSet-join','))
    $gmailHealth=$healthCompletedJson.communicationResearch.gmail
    Add-Check 'health:gmail-history-audit-visible' ([bool]$gmailHealth.valid-and$gmailHealth.status-eq'complete-exact-registry-plus-supplements'-and[int]$gmailHealth.canonicalClientsAudited-eq21-and[int]$gmailHealth.activeClientsPromotable-eq20-and[int]$gmailHealth.inactiveClientsPreserved-eq1-and[int]$gmailHealth.quarantinedClients-eq0-and[int]$gmailHealth.baseCanonicalClientsAudited-eq18-and[int]$gmailHealth.supplementalClientsAudited-eq3-and[int]$gmailHealth.globallyDeduplicatedMessages-eq2555-and[int]$gmailHealth.globallyDeduplicatedThreads-eq897-and[int]$gmailHealth.supplementalMessages-eq67-and[int]$gmailHealth.supplementalThreads-eq24) ([string]$gmailHealth.status)
    $bridgeHealthSupplement=@($gmailHealth.supplements|Where-Object{$_.clientId-eq'bridge-software'});$onsiteHealthSupplement=@($gmailHealth.supplements|Where-Object{$_.clientId-eq'onsite-concrete-landscape'});$bigOrangeHealthSupplement=@($gmailHealth.supplements|Where-Object{$_.clientId-eq'bigorange-marketing'});Add-Check 'health:gmail-exact-route-supplements-separated' ([int]$gmailHealth.supplementCount-eq3-and$bridgeHealthSupplement.Count-eq1-and[bool]$bridgeHealthSupplement[0].valid-and[int]$bridgeHealthSupplement[0].messages-eq27-and[int]$bridgeHealthSupplement[0].threads-eq5-and$onsiteHealthSupplement.Count-eq1-and[bool]$onsiteHealthSupplement[0].valid-and[int]$onsiteHealthSupplement[0].messages-eq3-and[int]$onsiteHealthSupplement[0].threads-eq1-and$bigOrangeHealthSupplement.Count-eq1-and[bool]$bigOrangeHealthSupplement[0].valid-and[int]$bigOrangeHealthSupplement[0].messages-eq37-and[int]$bigOrangeHealthSupplement[0].threads-eq18) ("bridge={0}/{1};onsite={2}/{3};bigorange={4}/{5}"-f$bridgeHealthSupplement[0].messages,$bridgeHealthSupplement[0].threads,$onsiteHealthSupplement[0].messages,$onsiteHealthSupplement[0].threads,$bigOrangeHealthSupplement[0].messages,$bigOrangeHealthSupplement[0].threads)
    Add-Check 'health:gmail-does-not-invent-combined-corpus-total' ($null-eq$gmailHealth.combinedCorpusMessages-and$null-eq$gmailHealth.combinedCorpusThreads-and$gmailHealth.countingNote-match'may also match a base client query') ([string]$gmailHealth.countingNote)
    $bridgeOnlySupplementPath=Join-Path $projectRoot 'state\client-history-research\gmail-bridge-software-history-2026-07-16.json';$healthBridgeOnly=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$coverageStateTemp,'-GmailSupplementPath',$bridgeOnlySupplementPath,'-ExternalProbeTimeoutSeconds','5'));Add-Check 'health:gmail-partial-supplement-set-fails-closed' (-not[bool]$healthBridgeOnly.communicationResearch.gmail.valid-and@($healthBridgeOnly.warnings|Where-Object{$_-match'cover the canonical registry exactly once'}).Count-eq1) ([string]$healthBridgeOnly.communicationResearch.gmail.status)
    $completeSlack=$healthCompletedJson.communicationResearch.slack;Add-Check 'health:slack-complete-live-visible' ([bool]$completeSlack.valid-and$completeSlack.status-eq'complete'-and-not[bool]$completeSlack.scopeUpgradeRequired-and'slack_connector_scope_upgrade'-notin$identityGateSet-and[bool]$completeSlack.readScopesVerified-and[bool]$completeSlack.allRelevantCursorsExhausted-and[int]$completeSlack.visibleConversationsTotal-eq106-and[int]$completeSlack.dillonAuthoredMessagesReviewed-eq1232) ("status={0};conversations={1};messages={2}"-f$completeSlack.status,$completeSlack.visibleConversationsTotal,$completeSlack.dillonAuthoredMessagesReviewed)
    Add-Check 'health:slack-upload-capability-live-probed' ($completeSlack.requestedUploadScope-eq'files:write'-and$completeSlack.requestedUploadScopeBasis-eq'live-probe-passed-no-file-created-or-shared'-and[bool]$completeSlack.filesWriteLiveProbeVerified) ([string]$completeSlack.requestedUploadScopeBasis)
    $slackBlockedPath=Join-Path $tempRoot 'slack-history-blocked.json';Write-Utf8Json $slackBlockedPath ([ordered]@{schemaVersion=1;artifactType='slack-client-history-audit';privacy=[ordered]@{redacted=$true;containsSecrets=$false;containsRawCommunications=$false;containsDirectIdentifiers=$false;storesOpaqueSlackLocatorsOnly=$true};status='blocked';coverage=[ordered]@{workspaceIdentityVerified=$true;conversationInventoryEstablished=$true;allRelevantCursorsExhausted=$false;visibleConversationsTotal=0;dillonAuthoredMessagesReviewed=0};connectorChecks=@();blocker=[ordered]@{type='insufficient_scope';reason='slack_missing_scope';requiredScopes=@('channels:read','groups:read','im:read','mpim:read')}});$healthBlocked=Read-JsonOutput (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$coverageStateTemp,'-SlackHistoryPath',$slackBlockedPath,'-ExternalProbeTimeoutSeconds','5'));$blockedGateSet=@($healthBlocked.humanGates);$requiredSlackScopeSet=@($healthBlocked.communicationResearch.slack.requiredReadScopes);$expectedSlackScopeSet=@('channels:read','groups:read','im:read','mpim:read');Add-Check 'health:slack-blocker-fixture-still-fails-closed' ([bool]$healthBlocked.communicationResearch.slack.valid-and$healthBlocked.communicationResearch.slack.status-eq'blocked'-and[bool]$healthBlocked.communicationResearch.slack.scopeUpgradeRequired-and'slack_connector_scope_upgrade'-in$blockedGateSet-and@($expectedSlackScopeSet|Where-Object{$_-notin$requiredSlackScopeSet}).Count-eq0) ("gates={0};scopes={1}"-f($blockedGateSet-join','),($requiredSlackScopeSet-join','))
    $deferredHealthPath=Join-Path $tempRoot 'system-state\deferred-health.json';Write-Utf8Json $deferredHealthPath $healthCompletedJson;$deferredControlPath=Join-Path $tempRoot 'system-state\deferred-CONTROL.md';Add-ExitCheck 'control:render-deferred-actions' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingControl.ps1') @('-QueuePath',$systemQueuePath,'-OutputPath',$deferredControlPath,'-HealthPath',$deferredHealthPath,'-AsOf',[string]$completedSystemQueue.updatedAt,'-InternalRender'));$deferredControl=Get-Content -LiteralPath $deferredControlPath -Raw -Encoding UTF8;Add-Check 'control:deferred-actions-visible' ($deferredControl-match'\*\*Deferred actions:\*\* `secondary_exposed_password_rotation`') 'secondary-remediation-rendered'
    $futureDeferredCoverage=Copy-JsonObject $coverage;$futureDeferredCoverage.credentialVault.secondaryRoute.remediationDeferredAt='2099-01-01T00:00:00Z';$futureDeferredCoveragePath=Join-Path $tempRoot 'access-coverage-future-deferred.json';Write-Utf8Json $futureDeferredCoveragePath $futureDeferredCoverage;$futureDeferredHealth=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$futureDeferredCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:future-deferred-timestamp-probe' $futureDeferredHealth;$futureDeferredHealthJson=Read-JsonOutput $futureDeferredHealth;Add-Check 'health:future-deferred-timestamp-fails-closed' ('secondary_exposed_password_rotation'-in@($futureDeferredHealthJson.humanGates)-and'secondary_exposed_password_rotation'-notin@($futureDeferredHealthJson.deferredActions)) (@($futureDeferredHealthJson.humanGates)-join',')
    $pendingRemediationCoverage=Copy-JsonObject $coverage;$pendingRemediationCoverage.credentialVault.secondaryRoute.remediationStatus='pending';$pendingRemediationCoveragePath=Join-Path $tempRoot 'access-coverage-pending-remediation.json';Write-Utf8Json $pendingRemediationCoveragePath $pendingRemediationCoverage;$pendingRemediationHealth=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$pendingRemediationCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:nondeferred-remediation-status-probe' $pendingRemediationHealth;$pendingRemediationHealthJson=Read-JsonOutput $pendingRemediationHealth;Add-Check 'health:nondeferred-remediation-status-fails-closed' ('secondary_exposed_password_rotation'-in@($pendingRemediationHealthJson.humanGates)-and'secondary_exposed_password_rotation'-notin@($pendingRemediationHealthJson.deferredActions)) (@($pendingRemediationHealthJson.humanGates)-join',')
    $activeSecondaryCoverage=Copy-JsonObject $coverage;$activeSecondaryCoverage.credentialVault.secondaryRoute.accessState='active';$activeSecondaryCoveragePath=Join-Path $tempRoot 'access-coverage-active-secondary.json';Write-Utf8Json $activeSecondaryCoveragePath $activeSecondaryCoverage;$activeSecondaryHealth=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$activeSecondaryCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:nonretired-secondary-route-probe' $activeSecondaryHealth;$activeSecondaryHealthJson=Read-JsonOutput $activeSecondaryHealth;Add-Check 'health:nonretired-secondary-route-fails-closed' ('secondary_exposed_password_rotation'-in@($activeSecondaryHealthJson.humanGates)-and'secondary_exposed_password_rotation'-notin@($activeSecondaryHealthJson.deferredActions)) (@($activeSecondaryHealthJson.humanGates)-join',')
    $requiredMissingCoveragePath=Join-Path $tempRoot 'access-coverage-required-missing.json';Write-Utf8Json $requiredMissingCoveragePath ([ordered]@{schemaVersion=2;summary=[ordered]@{exactBitwardenItemCount=1};priority=@([ordered]@{clientId='required-client';accessMappingRequired=$true;exactBitwardenItemCount=0});credentialVault=[ordered]@{primaryVaultIdentityStatus='verified';primaryExtensionTimeoutPolicy='on-browser-restart-lock-pin-enabled-master-password-on-restart-disabled'}});$healthRequiredMissing=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$requiredMissingCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:required-missing-route-probe' $healthRequiredMissing;$healthRequiredMissingJson=Read-JsonOutput $healthRequiredMissing;$requiredMissingGateSet=@($healthRequiredMissingJson.humanGates);Add-Check 'health:required-missing-route-gate' ('active_client_exact_bw_item_mapping'-in$requiredMissingGateSet-and'exact_bw_item_locator_mapping'-notin$requiredMissingGateSet-and'secondary_exposed_password_rotation'-in$requiredMissingGateSet) ($requiredMissingGateSet-join',')
    $fallbackCoveragePath=Join-Path $tempRoot 'access-coverage-fallback.json';Write-Utf8Json $fallbackCoveragePath ([ordered]@{schemaVersion=1;summary=[ordered]@{};priority=@()});$healthFallback=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$fallbackCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:unknown-vault-state-probe' $healthFallback;$healthFallbackJson=Read-JsonOutput $healthFallback;Add-Check 'health:unknown-vault-state-fails-closed' ('bitwarden_chrome_extension_unlock'-in@($healthFallbackJson.humanGates)-and'secondary_exposed_password_rotation'-in@($healthFallbackJson.humanGates)) (@($healthFallbackJson.humanGates)-join',')
    $verifiedCoveragePath=Join-Path $tempRoot 'access-coverage-verified.json';Write-Utf8Json $verifiedCoveragePath ([ordered]@{schemaVersion=2;summary=[ordered]@{};priority=@();credentialVault=[ordered]@{primaryVaultIdentityStatus='verified'}});$healthVerified=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$completedAccess,'-AccessCoveragePath',$verifiedCoveragePath,'-ExternalProbeTimeoutSeconds','5');Add-ExitCheck 'health:verified-vault-state-probe' $healthVerified;$healthVerifiedJson=Read-JsonOutput $healthVerified;$verifiedGateSet=@($healthVerifiedJson.humanGates);Add-Check 'health:verified-vault-removes-identity-gate' ('bitwarden_chrome_extension_unlock'-notin$verifiedGateSet-and'bitwarden_primary_vault_identity_confirmation'-notin$verifiedGateSet-and'exact_bw_item_locator_mapping'-in$verifiedGateSet-and'bitwarden_extension_timeout_policy_verification'-in$verifiedGateSet-and'secondary_exposed_password_rotation'-in$verifiedGateSet) ($verifiedGateSet-join',')
    $hangingAccess=Join-Path $tempRoot 'hanging-access-broker.ps1';Write-Utf8Text $hangingAccess "param([string]`$Action)`n& powershell.exe -NoProfile -NonInteractive -Command 'Start-Sleep -Seconds 10'`n'{}'`n"
    $healthTimeout=Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite','-CredentialBridgePath',$fakeBridge,'-AccessBrokerScriptPath',$hangingAccess,'-ExternalProbeTimeoutSeconds','1');Add-ExitCheck 'health:bounded-external-probe' $healthTimeout;$healthTimeoutJson=Read-JsonOutput $healthTimeout;Add-Check 'health:timeout-degrades-not-hangs' ([bool]$healthTimeoutJson.accessBroker.timedOut-and-not[bool]$healthTimeoutJson.accessBroker.valid-and$healthTimeoutJson.overall-eq'degraded') ([string]$healthTimeoutJson.overall)
    Add-ExitCheck 'health:live-probe' (Invoke-Script (Join-Path $PSScriptRoot 'Update-MarketingSystemHealth.ps1') @('-NoWrite'))
    Add-ExitCheck 'access-coverage:live-probe' (Invoke-Script (Join-Path $PSScriptRoot 'Update-AccessCoverage.ps1') @('-NoWrite'))

    Add-Check 'marketing-chief-agent' (Test-Path -LiteralPath 'C:\Users\dillo\.codex\agents\marketing_chief.toml') 'global-agent-definition'
    Add-Check 'voice-context' (Test-Path -LiteralPath (Join-Path $projectRoot 'context\DILLON_VOICE.md')) 'channel-voice-contract'
    Add-Check 'design-context' (Test-Path -LiteralPath (Join-Path $projectRoot 'context\DESIGN_STANDARD.md')) 'rendered-qa-contract'
}
catch{Add-Check 'test-harness-unhandled' $false $_.Exception.Message}
finally{Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue}

$checkArray=$checks.ToArray();$result=[pscustomobject][ordered]@{status=if($failed){'failed'}else{'passed'};checkedAt=[DateTimeOffset]::UtcNow.ToString('o');checkCount=$checks.Count;failedCount=@($checkArray|Where-Object{-not$_.passed}).Count;checks=$checkArray}
if($Detailed){$result|ConvertTo-Json -Depth 12}else{[pscustomobject]@{status=$result.status;checkedAt=$result.checkedAt;checkCount=$result.checkCount;failedCount=$result.failedCount}|ConvertTo-Json -Compress}
if($failed){exit 1}
