const chapters=[{title:'Start with the work.<br>Then add the AI.',body:'Before choosing an AI tool, map one recurring task. Write down its trigger, inputs, owner and expected result. A clear workflow is easier to improve than a vague ambition.',steps:[['discover','Find the repeating task','Look for a task with a clear beginning, consistent inputs and an outcome you can inspect.'],['qualify','Define a useful result','Describe what a good result contains and what would make it unusable.'],['guard','Keep an accountable owner','Name the person who reviews exceptions and decides what happens next.']]},{title:'Make the next step<br>unmistakable.',body:'An automation is only as useful as its handoff. Define what moves between people and tools, what needs review, and where incomplete work returns.',steps:[['route','Map the route','Show where inputs enter and which decision changes the next step.'],['connect','Agree on the inputs','List the fields and source material the next step needs.'],['handoff','Specify the exception','When information is missing, return a clear reason to a named owner.']]},{title:'Make improvement<br>observable.',body:'A working demo is a starting point. Compare real outputs with the result you defined, record exceptions, and adjust the workflow before extending it.',steps:[['measure','Inspect the result','Check whether the output meets the original acceptance criteria.'],['compose','Record what changed','Keep a concise note of the issue, correction and outcome.'],['publish','Expand deliberately','Carry a verified pattern to the next workflow only after the owner has reviewed it.']]}];
function icon(name){return `<svg class="icon" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><use href="assets/icons.svg#${name}"/></svg>`}
function showChapter(n){const c=chapters[n];document.querySelector('#chapter-number').textContent=String(n+1).padStart(2,'0');document.querySelector('#chapter-title').innerHTML=c.title;document.querySelector('#chapter-body').textContent=c.body;document.querySelector('#page-number').textContent=`${String(4+n*2).padStart(2,'0')} / Field guide`;document.querySelector('#chapter-steps').innerHTML=c.steps.map(([i,t,b])=>`<div class="step">${icon(i)}<div><h4>${t}</h4><p>${b}</p></div></div>`).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.chapter)===n)))}
document.querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>showChapter(Number(b.dataset.chapter))));showChapter(0);
const names=['discover','route','automate','qualify','connect','measure','publish','compose','guard','handoff'];document.querySelector('#icon-grid').innerHTML=names.map(n=>`<a class="icon-cell" href="assets/icon-${n}.svg" download>${icon(n)}<span>${n[0].toUpperCase()+n.slice(1)}</span><small>Download SVG</small></a>`).join('');
const motion=document.querySelector('#motion');motion.addEventListener('click',()=>{const paused=document.body.classList.toggle('paused');motion.setAttribute('aria-pressed',String(paused));motion.textContent=paused?'Resume motion':'Pause motion'});
document.querySelector('#replay').addEventListener('click',()=>{const card=document.querySelector('#endcard');card.classList.remove('play');void card.offsetWidth;card.classList.add('play')});document.querySelector('#print').addEventListener('click',()=>window.print());
document.querySelector('#sample-form').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#project');const name=input.value.trim();if(!name){input.setCustomValidity('Enter a workflow name.');input.reportValidity();return}input.setCustomValidity('');document.querySelector('#form-status').textContent=`For “${name}”, define the trigger, owner and expected result. Demo complete; nothing was sent or stored.`});document.querySelector('#project').addEventListener('input',e=>e.target.setCustomValidity(''));

const roleSets={agents:['research','writer','designer','analyst','planner','builder','reviewer','coordinator','support','automator','memory','handoff'],marketing:['search','paid-ads','email','social','content','video','landing-page','funnel','crm','campaign','audience','conversion','reporting','calendar','experiment','brand']};
for(const [group,items] of Object.entries(roleSets)){document.querySelector(group==='agents'?'#agent-grid':'#marketing-grid').innerHTML=items.map(n=>{const label=n==='crm'?'CRM':n.split('-').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');const svg=etched=>`<svg class="icon ${etched?'sb-icon-etched':''}" aria-hidden="true"><use href="assets/icons-${group}${etched?'-etched':''}.svg#${n}"/></svg>`;return `<a class="icon-cell sb-trace" href="assets/icon-${group}-${n}.svg" download><div class="sb-icon-sizes">${svg(false)}${svg(false)}${svg(true)}</div><span>${label}</span><small>24 / 32 / etched 44 px · SVG</small></a>`}).join('')}
document.querySelector('#replay-archive').addEventListener('click',()=>{for(const id of ['archive-title','reference-specimen']){const el=document.getElementById(id);el.classList.remove('play');void el.offsetWidth;el.classList.add('play')}document.getElementById('archive-title').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'})});
