(function(){
  'use strict';
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const menu=document.querySelector('.menu-button'),nav=document.getElementById('primary-nav');
  if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open')}));addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('is-open')){menu.click();menu.focus()}})}
  const tabs=[...document.querySelectorAll('[role=tab]')],panels=[...document.querySelectorAll('[role=tabpanel]')];
  function activate(tab,focus){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1});panels.forEach(p=>p.hidden=p.getAttribute('aria-labelledby')!==tab.id);if(focus)tab.focus()}
  tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab,false));tab.addEventListener('keydown',e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();activate(tabs[n],true)})});
  document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('details[open]').forEach(o=>{if(o!==d)o.open=false})}));
  const stage=document.querySelector('.scan-stage'),canvas=document.getElementById('scan-canvas');if(!stage||!canvas||reduced){stage?.classList.add('is-ready');return}
  const ctx=canvas.getContext('2d'),image=new Image();image.src=stage.dataset.logo;let points=[],start=0,raf=0;
  function size(){const r=stage.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0);return r}
  function build(){const r=size(),w=r.width,h=r.height,off=document.createElement('canvas'),o=off.getContext('2d');off.width=Math.ceil(w);off.height=Math.ceil(h);const ratio=image.width/image.height,dw=w*.74,dh=dw/ratio,ox=(w-dw)/2,oy=(h-dh)/2;o.drawImage(image,ox,oy,dw,dh);const data=o.getImageData(0,0,off.width,off.height).data;points=[];const step=Math.max(3,Math.round(w/210));for(let y=0;y<off.height;y+=step){for(let x=0;x<off.width;x+=step){if(data[(y*off.width+x)*4+3]>90&&Math.random()>.18)points.push({x,y,alpha:0,delay:(y/h)*1500+(x/w)*260})}}start=performance.now();cancelAnimationFrame(raf);draw(start)}
  function draw(now){const r=stage.getBoundingClientRect(),w=r.width,h=r.height,t=now-start,scan=Math.min(h,(t/1800)*h);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(244,119,33,.28)';ctx.lineWidth=1;for(let i=1;i<7;i++){ctx.beginPath();ctx.ellipse(w/2,h/2,w*.13+i*18,h*.18+i*11,0,0,Math.PI*2);ctx.stroke()}ctx.strokeStyle='rgba(244,119,33,.9)';ctx.beginPath();ctx.moveTo(0,scan);ctx.lineTo(w,scan);ctx.stroke();for(const p of points){p.alpha=Math.min(1,Math.max(0,(t-p.delay)/420));ctx.fillStyle=`rgba(244,119,33,${p.alpha})`;ctx.beginPath();ctx.arc(p.x,p.y,1.15,0,Math.PI*2);ctx.fill()}if(t>2300)stage.classList.add('is-ready');if(t<5200)raf=requestAnimationFrame(draw)}
  image.onload=build;let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(build,180)},{passive:true});
})();
