export const period = "July 1–31, 2026";
export const observedAt = "August 2, 2026";
export const leadAccounting = "Google Ads conversion events are counted as leads in this client-facing package. Lead counts are shown as whole integers; when Google reports fractional attribution, the display rounds to the nearest whole lead and preserves the raw value in the supporting note. Platform leads remain separate from qualified, booked, or revenue outcomes.";

export const reports = [
  {
    id: "kimberly-james-bridal",
    observedAt: "August 3, 2026",
    client: "Kimberly James Bridal",
    descriptor: "Paid media and appointment measurement",
    logo: "kimberly-james-bridal.png",
    logoBackground: "light",
    accent: "#E6C85C",
    accentBright: "#F5D978",
    status: "July Google and Meta results are complete; August focus is lead quality and bridal appointments",
    signal: "July generated eight leads: one Google form lead and seven Meta form leads. The new Higher Intent Meta form is in place to improve lead quality while Google continues building Philadelphia visibility and site traffic.",
    goal: "Connect July leads to bridal appointments, improve the quality of incoming inquiries, and keep the strongest Philadelphia search and Meta traffic moving toward booked consultations.",
    kpis: [
      ["Google spend", "$570.89", "Every July spending campaign"],
      ["Google clicks", "906", "2.57% account CTR"],
      ["Blended Google CPC", "$0.63", "$570.89 ÷ 906 clicks"],
      ["Platform leads", "8", "1 Google + 7 Meta"],
    ],
    work: [
      "Mapped the appointment journey from ad click to form submission and booked consultation so August reporting can focus on the inquiries most likely to become appointments.",
      "Prepared the GA4 and appointment-tracking plan, including a clean submission ID and same-window appointment match.",
      "Built the Philadelphia Search replacement with stronger negative keywords, location controls, Search Partners review, and AI Max controls.",
      "Published the Meta Higher Intent form with SMS verification, four qualification questions, and four approved images.",
    ],
    platforms: [
      {
        name: "Google Ads",
        state: "July performance",
        note: "Google delivered 35,258 impressions and 906 clicks on $570.89 across the two campaigns that spent, for a $0.63 blended CPC. Google also generated one form lead during July.",
        metrics: [["Spend", "$570.89"], ["Clicks", "906"], ["Blended CPC", "$0.63"], ["Google leads", "1"]],
        rows: [["KJB Search · Local Bridal · Philadelphia", "Enabled", "$96.23", "559 impressions", "30 clicks · 0 direction actions"], ["Campaign #1 · Performance Max", "Paused", "$474.65", "34,699 impressions", "876 clicks · 1 form lead"]],
      },
      {
        name: "Meta Ads",
        state: "July lead results",
        note: "Meta generated seven form leads at $7.37 per lead and 335 landing-page views at $0.46 each. The new Higher Intent form adds SMS verification and qualification questions to support stronger appointment quality in August.",
        metrics: [["Form leads", "7"], ["Cost / form lead", "$7.37"], ["Landing Page Views", "335"], ["Cost / LPV", "$0.46"]],
        rows: [["Qualified Form · Philadelphia", "Active", "Pending", "Pending", "7 Leads (Form)"], ["Website Carousel · Philadelphia", "Off", "Pending", "Pending", "335 Landing Page Views"]],
      },
    ],
    outcome: {
      platform: "Eight platform-reported leads: 1 Google Submit lead form conversion event plus 7 native Meta form leads. Meta also recorded 335 LPVs.",
      business: "The August focus is connecting these eight leads to consultations so campaign decisions reflect appointment quality as well as lead volume.",
      measurement: "Google conversion events count as leads in this report. August reporting will connect each form submission to the appointment record using source and timestamp.",
    },
    workstreams: [["Appointments", "Lead-to-consultation reporting plan", "Prepared"], ["Search", "Philadelphia Search controls and learning review", "Active"], ["Meta", "Higher Intent lead form and creative package", "Published"], ["Creative", "Four approved images and lead-quality questions", "Ready"]],
    wins: ["Google and Meta generated eight total July leads.", "The Higher Intent Meta form adds SMS verification and qualification questions before follow-up."],
    augustFocus: ["Connect July inquiries to booked bridal consultations.", "Keep improving Philadelphia search quality and the new Meta form based on appointment feedback."],
    nextMoves: [["Reconcile", "Dillon / Kim", "Match the Google form event and Meta submissions to July appointments", "This week"], ["Tighten", "Paid media", "Review Search terms, negatives, and location quality after learning stabilizes", "Next 7 days"], ["Decide", "Client + Momentum", "Keep or adjust the Meta lead form after first qualified-submission review", "After lead review"]],
    sources: ["Live Google Ads exact-account UI readback · July 1–31 · observed Aug 2", "Live Meta Ads campaign table · July 1–31 · observed Aug 2", "clients/kimberly-james-bridal/paid-media/measurement-plan-2026-07-16-google-appointments.md", "clients/kimberly-james-bridal/paid-media/meta-qualified-lead-campaign-2026-07-27.md", "Gmail and Slack searches · Kimberly James Bridal · July 1–31"],
  },
  {
    id: "onsite-concrete-landscape",
    observedAt: "August 3, 2026",
    client: "Onsite Concrete & Landscape",
    descriptor: "Google Ads, lead quality, and local content",
    logo: "onsite-concrete-landscape.png",
    logoBackground: "dark",
    accent: "#F45B4D",
    accentBright: "#FF8B7F",
    status: "Google Ads lead count complete; qualified-estimate reconciliation remains open",
    signal: "July produced 44 Google-reported leads after rounding Google’s 43.99 attributed conversion total to a whole client-facing count. The work now moves from lead volume to identifying which forms and calls became qualified estimates.",
    goal: "Build a trustworthy form-and-call measurement path that can guide budget around qualified estimates and booked work.",
    kpis: [["Google spend", "$247.07", "Every July spending campaign"], ["Google clicks", "1,353", "2.95% CTR"], ["Blended Google CPC", "$0.18", "$247.07 ÷ 1,353 clicks"], ["Google leads", "44", "43.99 raw attribution · rounded"]],
    work: [
      "Completed the conversion-deduplication correction packet for form, call, CRM, and imported-event overlap.",
      "Completed three Search Console-informed service drafts for review, then completed a separate client-approved July 20 batch on pool decks, retaining walls, and drainage.",
      "Reviewed local-search intent, service-area coverage, and the relationship between paid lead events and qualified estimate outcomes.",
      "Prepared a verified logo, service-reference pack, and motion-ad production direction; no final motion render is claimed.",
    ],
    platforms: [{
      name: "Google Ads",
      state: "Verified · exact July UI readback",
      note: "The account delivered 45,802 impressions and 1,353 clicks on $247.07 across both campaigns that spent, for a $0.18 blended CPC. The Leads Performance Max row showed 43.99 attributed Google conversion events: 11.99 Web Contact Form and 31.99 Web Phone Calls. This report counts them as 44 whole-number Google leads. No Get Directions Click action row was recorded.",
      metrics: [["Spend", "$247.07"], ["Clicks", "1,353"], ["Blended CPC", "$0.18"], ["Google leads", "44"]],
      rows: [["Onsite Concrete & Landscape · Smart", "Paused", "$125.19", "43,710 impressions", "1,056 clicks · 0 direction actions"], ["Leads · Performance Max", "Paused", "$121.88", "2,092 impressions", "297 clicks · 44 leads"]],
    }, {
      name: "Organic search and content",
      state: "July work completed",
      note: "The content lane built Vacaville service-area answers and supporting internal-link opportunities. July content is review-ready; measured ranking and booking outcomes remain separate from production completion.",
      metrics: [["July service blogs", "3"], ["Approved follow-up blogs", "3"], ["Primary market", "Vacaville"], ["Outcome state", "Pending validation"]],
      rows: [["July service content", "Review-ready", "—", "3 pieces", "Concrete, drainage, landscape"], ["Approved batch · Jul 20", "Ready", "—", "3 pieces", "Pool deck, retaining wall, drainage"]],
    }],
    outcome: {platform: "Google reported 43.99 attributed conversion events on the Leads PMax path. Under this package’s lead definition, that is displayed as 44 Google leads, with the raw value retained in the supporting note.", business: "Qualified estimates, booked work, and revenue were not reconciled to the July Google leads in the reviewed source window.", measurement: "Google conversion events count as leads. Qualified-estimate and revenue reporting remains pending validation; deduplicate form, call, CRM, and imported events before using the lead count for scale."},
    workstreams: [["Paid search", "Exact account readback and campaign split review", "Verified"], ["Measurement", "Deduplication and contact-reconciliation specification", "Completed locally"], ["Content", "Three review-ready drafts plus three approved July 20 drafts; none published", "Ready"], ["Creative", "Reference pack and motion production direction", "Prepared"]],
    wins: ["The account has a clear traffic-versus-action campaign split.", "July content maps directly to Vacaville service intent."],
    watchouts: ["The 44 Google-reported leads are not the same as 44 qualified estimates.", "Phone and form leads still need a business-outcome join."],
    nextMoves: [["Reconcile", "Dillon + Onsite", "Match each July form and call to a named contact and estimate status", "This week"], ["Launch", "Content", "Publish the approved content after final client review and metadata check", "Next 7 days"], ["Tune", "Paid media", "Use qualified-estimate mix, not raw platform value, for budget decisions", "After reconciliation"]],
    sources: ["Live Google Ads exact-account UI readback · July 1–31 · observed Aug 2", "clients/onsite-concrete-landscape/paid-media/correction-packet-2026-07-16-conversion-deduplication.md", "clients/onsite-concrete-landscape/content/blogs/2026-07/README.md", "clients/onsite-concrete-landscape/deliverables/2026-07-26-weekly-performance-dashboard/source-data.json", "Gmail and Slack searches · Onsite Concrete & Landscape · July 1–31"],
  },
  {
    id: "omega-landscaping",
    observedAt: "August 3, 2026",
    client: "Omega Landscaping and Concrete",
    descriptor: "Google Ads, GBP content, and lead reconciliation",
    logo: "omega-landscaping.png",
    logoBackground: "dark",
    accent: "#4B82D8",
    accentBright: "#8CB7FF",
    status: "Full-July Google lead total verified; identity and quality remain the decision layer",
    signal: "Omega recorded five Google leads in the exact July 1–31 account view: two calls from ads and three form submissions. Lead identity remains the next decision layer.",
    goal: "Tie Google-counted events to named calls, forms, inbox records, and qualified projects before changing budget or rebuilding Search.",
    kpis: [["Google spend", "$1,473.45", "Every July spending campaign"], ["Google clicks", "697", "2.96% CTR"], ["Blended Google CPC", "$2.11", "$1,473.45 ÷ 697 clicks"], ["Google leads", "5", "2 calls + 3 forms"]],
    work: ["Reviewed the Colorado Springs Performance Max account and the smaller high-intent Search row without overstating its creation date.", "Built the qualified-opportunity tracking file and published Google lead-form asset 400863777374 with the More qualified setting.", "Verified four Google Business Profile posts live and produced a second four-post creative package whose publication remains pending verification.", "Documented the Standard-role limitation blocking automatic Zapier and Sheets lead export."],
    platforms: [{name: "Google Ads", state: "Verified · exact July UI readback", note: "The account delivered 23,552 impressions and 697 clicks on $1,473.45 across both campaigns that spent, for a $2.11 blended CPC. The exact conversion-action breakdown recorded five Google leads: two Calls from ads and three Form Submission events. No Get Directions Click action row was recorded.", metrics: [["Spend", "$1,473.45"], ["Clicks", "697"], ["Blended CPC", "$2.11"], ["Google leads", "5"]], rows: [["Colorado Springs · Performance Max", "Paused", "$1,460.13", "23,503 impressions", "694 clicks · 5 leads"], ["High-intent Search", "Enabled", "$13.32", "49 impressions", "3 clicks · 0 direction actions"], ["Qualified lead-form asset", "Published · under review", "—", "Asset 400863777374", "More qualified"]]}, {name: "Google Business Profile", state: "Four live · four produced", note: "The July 14–20 batch was verified live. The July 24–30 package was produced and scheduled, but the canonical README does not prove all four posts published.", metrics: [["Verified live posts", "4"], ["Additional produced", "4"], ["Market", "Colorado Springs"], ["Outcome state", "Pending validation"]], rows: [["Jul 14–20 batch", "Verified live", "—", "4 posts", "Driveway, turf, spotlight, drainage"], ["Jul 24–30 batch", "Produced", "—", "4 graphics", "Walls, details, patio, design"]]}],
    outcome: {platform: "Google conversion events count as leads: five Google leads were recorded in the exact July 1–31 account view, comprising two calls from ads and three form submissions.", business: "Named lead, qualified project, booked work, and revenue reconciliation remains pending.", measurement: "Google-reported leads are validated as platform lead counts. Qualified-project and revenue reporting remains pending validation; use the qualified-opportunity tracking file and source-specific call/form review before optimization."},
    workstreams: [["Paid search", "PMax and high-intent Search account readback", "Verified"], ["Lead capture", "Qualified tracking and Google lead-form asset", "Published"], ["GBP", "Four verified-live posts plus four produced posts", "Mixed state"], ["Export", "Zapier and Sheets automation", "Blocked by role"]],
    wins: ["The account remains concentrated in the intended active campaign.", "GBP production now has a reusable project-proof rhythm."],
    watchouts: ["The five Google leads still need named call and form reconciliation.", "Google-reported leads are not a proxy for qualified landscaping work."],
    nextMoves: [["Identify", "Dillon + Omega", "Match July events to calls, forms, inbox, and CRM records", "This week"], ["Publish", "Content", "Release the approved GBP batch with exact service and project captions", "Next 7 days"], ["Decide", "Paid media", "Change budget only after project quality is visible", "After reconciliation"]],
    sources: ["Live Google Ads exact-account UI readback · July 1–31 · observed Aug 2", "clients/omega-landscaping/paid-media/correction-packet-2026-07-16-qualified-lead-reconciliation.md", "clients/omega-landscaping/paid-media/measurement/qualified-opportunity-ledger-2026-07-16.json", "clients/omega-landscaping/content/google-business-profile/2026-07-14-20-live-batch/README.md", "Gmail and Slack searches · Omega Landscaping · July 1–31"],
  },
  {
    id: "fagan-painting",
    client: "Fagan Painting",
    descriptor: "Historical July Meta baseline; AEO and SEO active",
    logo: "fagan-painting.png",
    logoBackground: "light",
    accent: "#9BB3C5",
    accentBright: "#C8DAE7",
    observedAt: "August 3, 2026",
    measurementHeading: "Meta lead-form conversion events count as platform leads; qualified business outcomes remain separate.",
    leadAccounting: "Meta-reported lead-form conversion events count as platform leads and are shown as whole integers. Platform leads remain separate from qualified estimates, booked work, and revenue outcomes.",
    status: "Meta advertising is no longer running; AEO and SEO work is active",
    signal: "Meta advertising is no longer running. July closed with $1,320.11 in historical Meta spend, 40,028 impressions, and 16 lead-form conversions; the current growth lane is implementation of the AEO and SEO feedback.",
    goal: "Apply the AEO and SEO feedback to priority service pages, homeowner FAQs, local painting topics, and internal links, then establish the first organic and AI-search visibility baseline.",
    kpis: [["Meta spend", "$1,320.11", "All July campaign spend"], ["Meta impressions", "40,028", "July 1–31"], ["Meta leads", "16", "Lead-form conversions"], ["All-spend CPL", "$82.51", "Total spend ÷ 16 leads"]],
    work: ["Completed the full July Meta summary for the Fagan Painting LLC account.", "Summarized all four campaigns with July spend: $1,320.11, 40,028 impressions, and 16 Meta form leads.", "Recorded 16 form leads on $726.98 from the lead-driving campaign at a reported $45.44 CPL.", "Closed the Meta advertising lane; all campaigns are now off.", "Prepared the AEO and SEO feedback around service pages, homeowner FAQs, local painting topics, and internal links.", "Completed the July 31 organic-search offer package for the August growth phase."],
    platforms: [{name: "Meta Ads", state: "Historical July baseline · no longer running", note: "Meta advertising is no longer running. July closed with $1,320.11 in spend, 40,028 impressions, and 16 lead-form conversions across four campaigns.", metrics: [["July spend", "$1,320.11"], ["Impressions", "40,028"], ["Meta leads", "16"], ["All-spend CPL", "$82.51"]], rows: [["Pittsburgh 25mi Lead Campaign · Copy", "Historical · now off", "$726.98", "18,457 impressions", "16 form leads · $45.44 CPL"], ["Primary First Optimized Lead Campaign", "Historical · now off", "$488.31", "16,062 impressions", "Traffic delivery"], ["WebsiteOnly · NoInstantForm", "Historical · now off", "$98.00", "5,375 impressions", "Traffic delivery"], ["New Leads Campaign", "Historical · now off", "$6.82", "134 impressions", "Traffic delivery"]]}, {name: "AEO and SEO", state: "Active", note: "The active growth lane applies the AEO and SEO feedback to service-page answers, homeowner FAQs, local painting topics, and structured internal links.", metrics: [["Program status", "Active"], ["Primary focus", "AEO + SEO"], ["First lane", "Service + FAQ"], ["Baseline", "August"]], rows: [["Answer-ready service pages", "Feedback implementation", "—", "—", "August work"], ["Homeowner FAQ system", "Question inventory", "—", "—", "First sprint"]]}],
    outcome: {platform: "July Meta activity generated 16 form leads and 40,028 impressions on $1,320.11 in spend. All Meta campaigns are now off.", business: "August shifts the growth program to AEO and SEO improvements across priority services, FAQs, local topics, and internal links.", measurement: "August reporting will track organic visibility, AI-search citations, service-page engagement, and new inquiries as the improvements are published."},
    workstreams: [["Meta", "Historical July closeout; advertising is no longer running", "Closed"], ["Organic", "AEO and SEO feedback implementation", "Active"], ["Content", "Service-page and homeowner FAQ priorities", "Ready"], ["Measurement", "Organic and AI-search visibility baseline", "Pending"]],
    wins: ["July Meta activity generated 16 form leads before the campaigns were turned off.", "The AEO and SEO feedback package is ready to guide the next growth phase."],
    augustFocus: ["Apply the AEO and SEO feedback to the highest-priority service pages.", "Build the first homeowner FAQ and local painting topic sprint, then measure visibility and inquiries."],
    nextMoves: [["Implement", "SEO + content", "Apply the AEO and SEO feedback to the priority service pages", "This week"], ["Build", "Content", "Create the first homeowner FAQ and local-topic sprint", "Next 7 days"], ["Baseline", "SEO", "Record organic rankings, AI-search visibility, and citation coverage", "After implementation"]],
    sources: ["clients/fagan-painting/evidence/2026-08-03-july-meta-ads-readback.json", "Live Meta Ads Manager · Fagan Painting LLC account · July 1–31 · observed Aug 3", "clients/fagan-painting/evidence/2026-07-16-meta-lead-routing-verification.json", "clients/fagan-painting/organic-search/2026-07-27-aeo-seo-transition-plan.md", "clients/fagan-painting/deliverables/2026-07-31-aeo-geo-upsell/README.md", "Live Slack and Gmail searches · Fagan Painting · July 1–31"],
  },
  {
    id: "fresh-blends-kwik-trip",
    client: "Fresh Blends / Kwik Trip",
    descriptor: "Google Ads delivery status",
    logo: "fresh-blends.png",
    logoBackground: "dark",
    accent: "#F5A24A",
    accentBright: "#FFC77C",
    status: "Google Ads readback complete; Ice Box campaigns paused",
    signal: "Fresh Blends stayed cleanly separated from Replenish in July. The four Ice Box campaigns were reviewed as their own lane and remained paused pending launch authority, store scope, and measurement confirmation.",
    goal: "Protect brand and budget separation until the new store scope and restart measurement are explicitly approved.",
    kpis: [["Google impressions", "19,362", "Four Fresh rows only"], ["Google clicks", "375", "1.94% CTR"], ["Google spend", "$156.43", "USD · July 1–31"], ["Ice Box campaigns", "4", "Current status paused"]],
    work: ["Separated Fresh Blends reporting from the shared Replenish child account and documented the brand boundary.", "Reviewed the four Ice Box PMax rows: stores #1110, #1161, #573, and #633.", "Kept Replenish store rows out of the Fresh Blends totals and kept Fresh Blends out of Replenish client reporting.", "Verified all four Fresh Blends rows remained paused; exact future location scope, authority, and measurement still require confirmation."],
    platforms: [{name: "Google Ads", state: "Verified · exact Fresh rows in shared child account", note: "The four Fresh Blends rows totaled 19,362 impressions, 375 clicks, 1.94% CTR, and $156.43. The reviewed row snapshot supports delivery and status reporting; a defensible Fresh-only Google lead count remains pending measurement confirmation. Current campaign status is paused.", metrics: [["Spend", "$156.43"], ["Impressions", "19,362"], ["Clicks", "375"], ["CTR", "1.94%"]], rows: [["Kwik Trip #1110 · Ice Box · PMax", "Paused", "Included", "Included", "Lead reporting pending"], ["Kwik Trip #1161 / #573 / #633", "Paused", "Included", "Included", "Lead reporting pending"]]}, {name: "Brand separation", state: "Control verified", note: "The shared account is a billing and routing detail, not permission to blend client results. Replenish location campaigns remain excluded from every Fresh Blends figure.", metrics: [["Fresh rows", "4"], ["Replenish rows", "Excluded"], ["Current delivery", "Paused"], ["Outcome state", "Pending validation"]], rows: [["Fresh Blends / Kwik Trip", "Separate lane", "$156.43", "19,362", "July readback"], ["Replenish / 7-Eleven", "Separate report", "Excluded", "Excluded", "Do not blend"]]}],
    outcome: {platform: "The Fresh rows support July delivery, spend, and pause-state reporting. Google conversion events will count as leads when a defensible Fresh-only event total is available from the confirmed measurement scope.", business: "Store-level lift, purchase, and qualified action outcomes were not reconciled in the reviewed July source window.", measurement: "Lead reporting is pending validation. Confirm the named launch scope and measurement definition before restarting any campaign."},
    workstreams: [["Account hygiene", "Shared child account mapped without blending brands", "Verified"], ["Campaign review", "Four Ice Box rows and status review", "Completed"], ["Launch control", "Exact future location scope and restart authority", "Pending approval"], ["Measurement", "Store-level action definition", "Pending"]],
    wins: ["Fresh Blends has a distinct July reporting lane.", "The campaign pause prevented a restart from being represented as active delivery."],
    watchouts: ["A shared Google child account can make brand blending easy; every report keeps it separate.", "The reviewed Fresh-only snapshot does not yet support a defensible lead total."],
    nextMoves: [["Authorize", "Client + Momentum", "Confirm launch authority, locations, and threshold", "Before restart"], ["Define", "Measurement", "Name the store-level action and deduplication rule", "Before launch"], ["Restart", "Paid media", "Re-enable only the approved rows after QA", "After approval"]],
    sources: ["Live Google Ads exact-account UI readback · Fresh rows · July 1–31 · observed Aug 2", "clients/fresh-blends-kwik-trip/deliverables/2026-07-26-weekly-performance-dashboard/source-data.json", "clients/fresh-blends-kwik-trip/paid-media/launch-config.json", "Official Fresh Blends logo · freshblends.com · retrieved Aug 2", "Live Slack and Gmail searches · Fresh Blends · July 1–31"],
  },
  {
    id: "replenish-7-eleven",
    client: "Replenish / 7-Eleven",
    descriptor: "Google Ads, location pacing, and billing reconciliation",
    logo: "replenish-7-eleven.png",
    logoBackground: "light",
    accent: "#11A06C",
    accentBright: "#48D597",
    status: "Replenish-only Google lead count complete; billing and event-category reconciliation remain open",
    signal: "July produced 13 Google-reported leads across the Replenish-only rows while the operating work tightened caps, location isolation, and billing evidence. Lead categories and business outcomes remain the next reconciliation layer.",
    goal: "Keep location pacing and billing decisions grounded in the verified Replenish rows, not blended account totals or ambiguous event labels.",
    kpis: [["Google impressions", "125,127", "Replenish rows only"], ["Google clicks", "4,301", "3.44% CTR"], ["Google spend", "$1,966.90", "USD · July 1–31"], ["Google leads", "13", "All conversion events counted"]],
    work: ["Reviewed Replenish-only July rows and kept Fresh Blends / Kwik Trip excluded from the totals.", "Launched and monitored San Diego location campaigns for Solana Beach, Miramar, Torrey Del Mar, and Carmel Mountain.", "Verified lifetime-cap pause behavior, location isolation, CPC pacing, and campaign-row sums in the weekly reporting packet.", "Completed the July 29 balance reconciliation: gross costs, credits, retained payments, chargebacks, and the remaining confirmation questions."],
    platforms: [{name: "Google Ads", state: "Verified · Replenish-only exact July rows", note: "Replenish rows totaled 125,127 impressions, 4,301 clicks, 3.44% CTR, and $1,966.90. The account summary showed 13 Google conversion events across Purchase, Get directions, and Page view configuration. All 13 count as Google leads in this package; the categories are not represented as confirmed purchases or store visits.", metrics: [["Spend", "$1,966.90"], ["Impressions", "125,127"], ["Clicks", "4,301"], ["Google leads", "13"]], rows: [["Miami / Coral Springs / Pampano / Boca", "Paused", "Included", "Included", "July rows"], ["Torrey / Miramar / Carmel / Solana", "Enabled", "Included", "Included", "July rows"]]}, {name: "Location and billing controls", state: "Reviewed in July", note: "The weekly source also showed 69 modeled clicked directions for Jul 20–26. That model is displayed separately from Google leads and from business outcomes. Billing reconciliation remains open around four chargebacks and credit allocation.", metrics: [["Modeled directions", "69"], ["Modeled window", "Jul 20–26"], ["Chargebacks", "4"], ["Billing state", "Pending confirmation"]], rows: [["San Diego launch", "Reviewed", "$93.47", "4 campaigns", "Location QA"], ["Balance reconciliation", "Open", "Pending", "4 chargebacks", "Credit allocation"]]}],
    outcome: {platform: "Google showed 13 conversion events in the Replenish-only summary, counted here as 13 Google leads. The 69 clicked-directions figure is modeled from verified clicks for Jul 20–26 and remains separate from the lead total.", business: "Store visits, purchases, and revenue were not reconciled to the July Google leads in the reviewed source window.", measurement: "Google conversion events count as leads. Purchase, Get directions, Page view, modeled directions, and business outcomes remain separately labeled while downstream reporting is validated."},
    workstreams: [["Location rollout", "Seven-city program and San Diego launch QA", "Reviewed"], ["Pacing", "CPC, caps, pause verification, location isolation", "Completed"], ["Reporting", "Replenish-only weekly deck and campaign rows", "Verified"], ["Billing", "Balance, chargebacks, credits, and caps", "Open"]],
    wins: ["Replenish and Fresh Blends remain separate despite the shared child account.", "The July billing packet makes the open confirmation questions explicit."],
    watchouts: ["The 13 Google leads use mixed action definitions.", "The final payable amount and chargeback intent still require confirmation."],
    nextMoves: [["Confirm", "Mia + Momentum", "Validate the four July chargebacks and issuer reasons", "This week"], ["Reconcile", "Billing", "Allocate Google credits and confirm approved location ceilings", "Before payment"], ["Pace", "Paid media", "Use verified row-level delivery and named actions for next budget decision", "After billing"]],
    sources: ["Live Google Ads exact-account UI readback · Replenish-only rows · July 1–31 · observed Aug 2", "clients/replenish-7-eleven/deliverables/2026-07-26-weekly-performance-presentation/source-data.json", "clients/replenish-7-eleven/deliverables/2026-07-29-google-ads-balance-reconciliation/source-data.json", "clients/replenish-7-eleven/paid-media/2026-07-26-lifetime-cap-pause-verification.json", "Live Slack and Gmail searches · Replenish · July 1–31"],
  },
  {
    id: "nkcdc",
    client: "NKCDC",
    descriptor: "Phase Two growth proposal and Google Grants direction",
    logo: "nkcdc.png",
    logoBackground: "light",
    accent: "#A4AD4D",
    accentBright: "#C9D36A",
    status: "Proposal and QA complete; one Google lead observed in the selected account; client approval remains open",
    signal: "July turned the Phase Two proposal into a broader growth program and recorded one Google-reported lead in the selected account. The account result remains separate from the proposed Google Grants program.",
    goal: "Move from a reviewed 12-page proposal to an approved Phase Two scope, budget, and follow-up screenshare.",
    kpis: [["Google CTR", "3.37%", "Exact July account UI"], ["Google spend", "$120", "USD · July 1–31"], ["Avg. CPC", "$8.54", "Exact July account UI"], ["Google leads", "1", "Selected account · not Grants"]],
    work: ["Reframed the proposal from an SEO / AI-only document into a full Phase Two growth plan.", "Added SEO/GEO content, Google Grants, social, cold email, webinar promotion, and ChatGPT Ads as coordinated options.", "Rebranded the proposal from 360 to Momentum Digital and applied the Momentum Digital color system.", "Updated the custom package to $1,750 per month, showing $300 savings against the $2,050 a la carte total, then completed 12-page QA."],
    platforms: [{name: "Google Ads / Grants direction", state: "Account readback observed · proposal-led strategy", note: "The selected Google account showed a 3.37% CTR, $8.54 average CPC, $120 spend, and one Google conversion event for July, counted here as one Google lead. This readback is kept separate from the proposed Google Grants program and is not treated as a grant result.", metrics: [["Spend", "$120"], ["CTR", "3.37%"], ["Avg. CPC", "$8.54"], ["Google leads", "1"]], rows: [["Google account", "Observed", "$120", "Pending", "1 Google lead"], ["Google Grants direction", "Proposed", "—", "—", "Approval pending"]]}, {name: "Phase Two proposal", state: "QA complete", note: "The deliverable is ready for review. Final approval, pilot scope, and follow-up screenshare are the next decision gates.", metrics: [["Pages QA’d", "12"], ["Package", "$1,750 / month"], ["A la carte", "$2,050 / month"], ["Savings", "$300 / month"]], rows: [["Growth plan", "Ready for review", "$1,750", "12 pages", "Momentum Digital"], ["Follow-up", "Pending", "—", "—", "Screenshare"]]}],
    outcome: {platform: "The selected Google account recorded one conversion event, counted here as one Google lead, alongside $120 spend, 3.37% CTR, and $8.54 average CPC.", business: "No client-approved Phase Two scope, grant outcome, or downstream growth result was verified in the July source window.", measurement: "Google conversion events count as leads. Any Google Grants outcome reporting remains pending validation until the grant route, goals, and reporting owner are approved."},
    workstreams: [["Strategy", "Full Phase Two growth plan and service options", "Complete"], ["Brand", "Momentum Digital rebrand and color QA", "Complete"], ["Commercial", "$1,750 custom package and savings logic", "Complete"], ["Approval", "Mac / client review and follow-up screenshare", "Open"]],
    wins: ["The proposal now matches the broader growth conversation.", "The 12-page package was QA’d and the price logic is explicit."],
    watchouts: ["Google account activity and Google Grants strategy are different evidence lanes.", "Approval is still the gate for implementation and budget."],
    nextMoves: [["Review", "Mac + NKCDC", "Collect final proposal feedback and approve the direction", "This week"], ["Scope", "Momentum", "Define the Phase Two pilot, owners, and measurement contract", "After review"], ["Schedule", "Dillon", "Hold the follow-up screenshare and close open decisions", "Next 7 days"]],
    sources: ["Live Google Ads exact-account UI readback · July 1–31 · observed Aug 2", "clients/nkcdc/deliverables/2026-07-21-NKCDC-Phase-Two-Growth-Proposal-QA.md", "clients/nkcdc/deliverables/phase-two-growth-strategy/deliverables/QA.md", "Live Slack search · #nkcdc · July 1–31", "Gmail search · NKCDC · July 1–31"],
  },
  {
    id: "hope-wellness-center",
    client: "Hope Wellness Center",
    descriptor: "Search, site architecture, and brand film",
    logo: "hope-wellness-center.png",
    logoBackground: "light",
    accent: "#75C96A",
    accentBright: "#9AE88C",
    status: "Deeper analysis and brand reel complete; implementation decisions pending",
    signal: "July clarified the Hope Wellness growth path: tighten the search and conversion architecture, make the brand feel human, and queue the highest-impact site fixes before measurement expansion.",
    goal: "Convert the deeper analysis into an approved P0 implementation queue and confirm the measurement routes for search, booking, and GBP.",
    kpis: [["Deep analysis", "1", "July 15 deliverable"], ["Implementation items", "15", "5 P0 · 6 P1 · 4 P2"], ["Leadership decisions", "7", "Approval and ownership gates"], ["Brand reel", "60 sec", "Completed in July"]],
    work: ["Completed the deeper website and search analysis covering site architecture, conversion paths, content duplication, and local-search presentation.", "Produced a 15-item implementation queue: five P0, six P1, and four P2 items.", "Separated seven leadership decisions from the implementation backlog so approvals and production work are not conflated.", "Completed the 60-second vertical brand reel, 17-illustration visual library, and therapist video system."],
    platforms: [{name: "Google search and local surfaces", state: "Strategy review · platform access pending", note: "The July work covered search architecture, conversion paths, content duplication, booking, and GBP questions. Exact Google Ads, GBP, ranking, and booking metrics were not available in the reviewed source window.", metrics: [["Paid media", "Not mapped"], ["Rankings", "Pending"], ["GBP", "Pending"], ["Booking", "Pending"]], rows: [["Search architecture", "Audited", "—", "—", "Priority fixes"], ["Conversion path", "Audited", "—", "—", "Measurement pending"]]}, {name: "Brand and content", state: "Production complete", note: "The brand reel and visual kit are finished for review. Content priorities now connect the identity work to the site and search implementation queue.", metrics: [["Brand reel", "60 sec"], ["Analysis", "Complete"], ["P0 queue", "Ready"], ["Client review", "Open"]], rows: [["Vertical brand reel", "Complete", "—", "60 sec", "Review"], ["Implementation queue", "Ready", "—", "7 decisions", "Release after approval"]]}],
    outcome: {platform: "No exact July Google or Meta delivery metric was verified for this report.", business: "Booking, GBP, search visibility, and implementation outcomes remain pending access, analytics, and client decisions.", measurement: "Conversion reporting is pending validation. Release the P0 queue only after the measurement owner and destination paths are confirmed."},
    workstreams: [["Analysis", "Website, search, architecture, and conversion review", "Complete"], ["Content", "Therapist video and content priorities", "Reviewed"], ["Brand", "60-second reel and 17-illustration visual system", "Complete"], ["Implementation", "15-item queue plus seven leadership decisions", "Pending approval"]],
    wins: ["The work produced a prioritized 15-item implementation queue with five P0 actions.", "The completed brand reel and visual library give the client a reusable human-centered creative system."],
    watchouts: ["No live Google or Meta account was mapped for July reporting.", "Implementation should not outrun measurement and booking-path confirmation."],
    nextMoves: [["Decide", "Joseph + Momentum", "Resolve the seven leadership decisions", "This week"], ["Measure", "Analytics owner", "Confirm GA4, GBP, ranking, form, and booking access", "Before implementation"], ["Release", "Dillon", "Release the five P0 items after approvals and route checks", "After review"]],
    sources: ["clients/hope-wellness-center/deliverables/2026-07-15-hope-wellness-deeper-analysis.html", "clients/hope-wellness-center/deliverables/2026-07-15-hope-wellness-implementation-queue.csv", "clients/hope-wellness-center/CLIENT.md", "Live Slack and Gmail searches · Hope Wellness Center · July 1–31", "Official Hope Wellness Center logo · local verified reference"],
  },
  {
    id: "bar-crawl-usa",
    client: "Bar Crawl USA",
    descriptor: "WordPress SEO and event-inventory control",
    logo: "bar-crawl-usa.webp",
    logoBackground: "dark",
    accent: "#D8A85A",
    accentBright: "#F0C77A",
    status: "July Halloween SEO is complete; the August evergreen-page plan is ready",
    signal: "July completed a 12-page Boos & Booze SEO program across confirmed live event pages. Eleven page updates are complete, and Portland is the final Elementor carryover before the next ten-page August cycle begins.",
    goal: "Complete July carryover, then deliver the exact next ten evergreen WordPress pages already sent to the client for August without repeating the June or July Halloween work.",
    kpis: [["Pages optimized", "12", "Existing Boos & Booze pages"], ["Pages completed", "11", "Portland is the carryover"], ["New July listings", "2", "Added to the inventory"], ["Google spend", "$0.00", "No July ad spend"]],
    work: ["Optimized 12 existing Boos & Booze event pages across titles, descriptions, supporting copy, quick facts, FAQs, and internal links.", "Completed the supporting page updates on 11 pages; Portland retains its updated metadata and is the final Elementor body carryover.", "Added Beltline Bubbles & Bites and Alpharetta Bubbles & Bites to the current July event inventory.", "Rebuilt the July SEO plan around current WordPress pages and the live Boos & Booze event list."],
    platforms: [{name: "Google Ads", state: "No July ad spend", note: "No Google Ads ran in July, so the August growth work stays focused on the next ten existing WordPress pages rather than a new advertising launch.", metrics: [["Spend", "$0.00"], ["Impressions", "0"], ["Clicks", "0"], ["August ads", "Not planned"]], rows: [["Google Ads", "No July activity", "$0.00", "0", "SEO focus"], ["Organic search", "August plan ready", "—", "—", "Next 10 pages"]]}, {name: "WordPress SEO", state: "July page work complete", note: "The organic plan uses current pages and approved live events, keeping each optimization aligned to the event calendar.", metrics: [["July pages", "12"], ["Page updates", "11 complete"], ["August pages", "10"], ["Plan", "Sent"]], rows: [["Boos & Booze pages", "July complete", "12 pages", "11 complete", "Portland carryover"], ["Evergreen pages", "August planned", "10 pages", "Ordered list", "Weekly review"]]}],
    outcome: {platform: "July focused on organic search rather than paid advertising: $0.00 in Google Ads spend and 12 Boos & Booze pages moved through the SEO program.", business: "The August plan shifts to ten evergreen WordPress pages that can support fall and holiday events through stronger search visibility and internal links.", measurement: "After each August page is updated, request indexing and review page and query movement weekly, then connect organic landing-page activity to ticket outcomes."},
    workstreams: [["July pages", "Boos & Booze titles, descriptions, copy, FAQs, and internal links", "Complete"], ["Portland", "Final Elementor body update", "First in August"], ["August pages", "Next ten evergreen WordPress pages", "Planned"], ["Reporting", "Indexing and weekly page and query review", "Ongoing"]],
    wins: ["Twelve existing Halloween event pages moved through the July SEO program.", "Eleven page updates are complete, and the next ten-page August plan has already been sent."],
    augustFocus: ["Finish the Portland Elementor carryover and correct the Birmingham and Atlanta schema details.", "Optimize the ten evergreen pages in the agreed order, request indexing, and review movement weekly."],
    nextMoves: [["Complete", "SEO", "Finish Portland's Elementor body update and correct the Birmingham and Atlanta schema details", "First"], ["Optimize", "SEO + content", "Work through the next ten evergreen WordPress pages in the approved order", "August"], ["Measure", "Analytics", "Request indexing and review page and query movement each week", "Weekly"]],
    augustScopeCallout: {
      value: "10 evergreen pages",
      title: "August on-page SEO plan already sent to the client",
      detail: "Each page receives title and description improvements, one clear H1, direct-answer copy, useful FAQs, stronger local detail, internal links to approved live events, and accurate supported schema where appropriate.",
      items: ["What Is a Bar Crawl?", "Macon Bar Crawls", "Atlanta Bar Crawls", "Columbia Bar Crawls", "Duluth Bar Crawls", "Greenville Bar Crawls", "Alpharetta Bar Crawls", "Sarasota Bar Crawls", "St. Pete Bar Crawls", "Gainesville Bar Crawls"],
    },
    sources: ["Live Google Ads exact-account UI readback · July 1–31 · observed Aug 2", "clients/bar-crawl-usa/context/operating-context.md", "state/client-history-research/gmail-client-history-2026-07-16.json · client=bar-crawl-usa", "Live Slack and Gmail searches · Bar Crawl USA · July 1–31", "Official Bar Crawl USA letter logo · barcrawlusa.com · retrieved Aug 2"],
  },
  {
    id: "va-claims-edge",
    client: "VA Claims Edge",
    descriptor: "Portal UX, signup flow, and booking routing",
    logo: "va-claims-edge.png",
    logoBackground: "light",
    accent: "#C94343",
    accentBright: "#F07474",
    status: "Phase Two UX deployed successfully; booking-rule alignment remains open",
    signal: "July turned the VA Claims Edge direction into a coherent product surface and a verified production deployment; the remaining implementation risk is the booking configuration, not deployment access.",
    goal: "Correct the four booking-rule mismatches, instrument the production journey, and connect approved UI states to real claimant data.",
    kpis: [["Signup flow", "2 steps", "Secure account + claimant profile"], ["Phase Two", "1", "UI handoff bundle"], ["Review surface", "1", "Unified portal review"], ["Paid media", "Not mapped", "No KPI claim"]],
    work: ["Built the initial signup wireframe with the exact VA Claims Edge logo, shield artwork, Epilogue typography, and navy, red, ivory, and cyan system.", "Completed the Phase Two UI handoff covering the client portal, dashboard, secure files, messaging, and internal operations workspace.", "Resolved the initial Vercel access blocker and verified the approved Phase Two login in production.", "Integrated three dashboard refinements and documented four material booking-rule mismatches."],
    platforms: [{name: "Google and Meta information", state: "No paid-media route mapped", note: "No exact Google Ads or Meta Ads account was mapped to VA Claims Edge in the reviewed July source window. The report therefore makes no paid-media performance claim.", metrics: [["Google Ads", "Not mapped"], ["Meta Ads", "Not mapped"], ["Attribution", "Pending"], ["Business outcomes", "Pending"]], rows: [["Paid-media accounts", "Not mapped", "—", "—", "No KPI claim"], ["Search / analytics", "Pending", "—", "—", "Access needed"]]}, {name: "Product and portal", state: "Verified production deployment", note: "The initial Vercel access blocker was resolved and public readback confirmed the approved Phase Two login. Four booking-rule mismatches remain open.", metrics: [["Signup steps", "2"], ["Dashboard refinements", "3"], ["Booking mismatches", "4"], ["Deployment", "Verified live"]], rows: [["Phase Two UI handoff", "Complete", "—", "—", "Deployed"], ["Production login", "Verified live", "—", "—", "Booking QA open"]]}],
    outcome: {platform: "No July paid-media platform metrics were verified for VA Claims Edge.", business: "The Phase Two login is verified in production; booking completion and claimant-progress outcomes remain pending because four routing rules do not match the approved flow.", measurement: "Conversion reporting is pending validation. Correct booking configuration and instrument the production journey before adding ad or funnel claims."},
    workstreams: [["Brand", "Exact logo, shield, and type system", "Complete"], ["UX", "Signup, dashboard, files, messaging, workspace", "Complete"], ["Review", "Unified portal feedback surface", "Complete"], ["Implementation", "Deployment access and booking rules", "Open"]],
    wins: ["The client has one coherent review surface for the product journey.", "Brand fidelity and dashboard feedback were carried into the handoff."],
    watchouts: ["Production deployment is live, but sample dashboard values must not be treated as real claimant metrics.", "Booking routing still violates four approved business rules."],
    nextMoves: [["Correct", "Web owner", "Apply the four booking-rule corrections", "This week"], ["Verify", "David + Momentum", "Test advance notice, horizon, owner availability, and duration", "After correction"], ["Instrument", "Engineering", "Map analytics to the verified production and booking routes", "After QA"]],
    sources: ["clients/va-claims-edge/deliverables/2026-07-17-phase-two-ui-handoff/README.md", "clients/va-claims-edge/deliverables/2026-07-17-phase-two-ui-handoff/preflight-report.md", "clients/va-claims-edge/evidence/2026-07-25-booking-routing-verification.json", "Live Slack and Gmail searches · VA Claims Edge · July 1–31", "Local established VA Claims Edge logo used on light plaque"],
  },
  {
    id: "revive-systems",
    client: "Revive Systems",
    descriptor: "AEO/GEO/SEO content and ads readiness",
    logo: "revive-systems.png",
    logoBackground: "dark",
    accent: "#F06A3A",
    accentBright: "#FF9B6D",
    status: "Organic acquisition package complete; paid media remains approval-gated",
    signal: "July built the organic foundation first: a five-blog AEO/GEO/SEO cluster, an acquisition and sitemap package, and a clear ads-readiness checklist that keeps live account changes behind exact approval.",
    goal: "Publish the approved organic package, establish the first visibility baseline, and map the exact paid-media and pixel route before activation.",
    kpis: [["Blog cluster", "5", "AEO / GEO / SEO pieces"], ["Acquisition package", "1", "Organic + sitemap plan"], ["Ads readiness", "1", "Assessment complete"], ["Live ad KPI", "Not mapped", "Approval-gated"]],
    work: ["Completed a five-blog content cluster covering weight-loss programs, coaching roles, routines, strength training, and local health coaching.", "Created the organic acquisition and sitemap package for the public site and supporting funnel hosts.", "Reviewed the live website and application pages in the July operating context.", "Prepared the ads-readiness assessment covering Meta access, pixel verification, remarketing readiness, and the approval gates for future paid work."],
    platforms: [{name: "Google and Meta information", state: "Organic-first · paid route pending", note: "The July source set contains an ads-readiness assessment, not a live paid-media performance export. Google and Meta remain secondary until the exact route, pixel, and approval are confirmed.", metrics: [["Google Ads", "Not mapped"], ["Meta Ads", "Readiness only"], ["Pixel", "Pending"], ["Live spend", "Not claimed"]], rows: [["Paid-media route", "Approval-gated", "—", "—", "No live KPI claim"], ["Remarketing readiness", "Assessment", "—", "—", "Pixel verification pending"]]}, {name: "AEO, GEO, and SEO", state: "Production complete", note: "The content and sitemap package is ready for the next controlled publication step. Publishing and measured citation outcomes remain separate from the writing completion state.", metrics: [["Blog pieces", "5"], ["Site hosts", "2"], ["Sitemap plan", "Ready"], ["Baseline", "Next review"]], rows: [["AEO/GEO/SEO cluster", "Complete", "—", "5 pieces", "Review and publish"], ["Organic acquisition", "Ready", "—", "—", "Baseline pending"]]}],
    outcome: {platform: "No live July Google or Meta performance metric was verified for Revive Systems.", business: "Organic rankings, citations, leads, and revenue were not measured in the reviewed July source window.", measurement: "Conversion reporting is pending validation. Establish the organic baseline and exact paid route before using campaign language or scaling claims."},
    workstreams: [["Content", "Five-piece AEO/GEO/SEO cluster", "Complete"], ["Organic", "Acquisition and sitemap package", "Ready"], ["Website", "Public site and funnel review", "Reviewed"], ["Paid readiness", "Meta access, pixel, remarketing checklist", "Pending"]],
    wins: ["The content system is specific enough to publish and measure.", "Paid-media readiness is separated from live performance claims."],
    watchouts: ["No CMS upload, sitemap publication, or live ad action is claimed for July.", "The exact HighLevel and advertising route still needs mapping."],
    nextMoves: [["Publish", "Mike + Momentum", "Approve and publish the organic cluster and sitemap package", "This week"], ["Baseline", "SEO", "Record initial rankings, citations, and organic landing-page signals", "Next 7 days"], ["Map", "Paid media", "Confirm exact Meta / Google route and pixel before activation", "Before ads"]],
    sources: ["clients/revive-systems/deliverables/2026-07-16-aeo-geo-seo-blog-cluster/01-completion-manifest.md", "clients/revive-systems/deliverables/2026-07-16-organic-acquisition-and-sitemap-package.md", "clients/revive-systems/deliverables/2026-07-19-ads-readiness-response/ads-readiness-assessment.md", "Live Slack and Gmail searches · Revive Systems · July 1–31", "Local Revive Systems source logo"],
  },
];

export const portfolio = reports.map((report) => ({ id: report.id, client: report.client, logo: report.logo, status: report.status }));
